// ACQUISITION COPY — the ONE place the council / chapter / outreach words live (Lee, 2026-09-17).
//
// "STOP making the council/chapter acquisition experience revolve around 'Exam 1 is free.' Exam 1 may be almost
// over when these links are shared." Everything here is evergreen: Survive has short cram videos + practice
// exams, specific to the school's course; a council sends ONE portal link; a chair picks their chapter and shares
// its page; students can study free. Once a student is inside /learn, the product can still say "Exam 1".
//
// Pure and client-safe. NO link building here: every URL is generated by the existing link helpers
// (outreach-links linkFor / shortPath, share-url buildShareUrl, learn-paths councilChairsPath) and passed in, so
// referral ids, council ids and attribution are exactly what they were.
//
// Consumers: outreach-v2 DM_TEMPLATES (every admin Copy DM — /admin/dm-v2, /admin/growth/links, the cold-outreach
// boards and schedule, the DM console), LearnChapterBar chapterGroupMe, chair-promo councilChairPost /
// chairGroupMe, ChapterShare groupMeMessage, partners' council posts, rep-shared share text, and the /learn exec
// heroes and chapter strip.

/** A course code for copy; "intro accounting" only when the school has none on file. */
export const courseFor = (code: string | null | undefined): string => (code ?? "").trim() || "intro accounting";
/** The same, capitalised for the start of a headline. */
const courseHeadline = (code: string | null | undefined): string => (code ?? "").trim() || "Intro accounting";

// ── the cold DMs (admin Copy DM) ──────────────────────────────────────────────────────────────
// Templates, not functions, because outreach-v2's renderOutreachDm fills them and reports a missing field
// instead of pasting a placeholder. {{courseCode}} {{campusShorthand}} {{greekLetters}} {{outreachLink}}.
export const COLD_DM_TEMPLATES = {
  // Council exec — LEE'S COPY, VERBATIM (2026-09-17). Not Exam-1-specific.
  council: [
    "Hey y’all,",
    "",
    "I’m Lee Ingram, an accounting professor at Ole Miss and the tutor behind Survive Accounting. I’ve helped 1,000+ students with Intro Accounting.",
    "",
    "I put together {{courseCode}} cram videos + practice exams for {{campusShorthand}} students.",
    "",
    "Would you mind passing this along to your chapters’ scholarship chairs or presidents? They can pick their chapter and get a ready-to-share page for their members:",
    "",
    "{{outreachLink}}",
    "",
    "If you have questions, feel free to text or call me at 601-201-8759.",
    "",
    "Really appreciate it!",
    "",
    "Lee",
  ].join("\n"),
  // Chapter exec — LEE'S COPY, VERBATIM (2026-09-17). "{{greekLetters}} members taking", never "letters's in".
  chapter: [
    "Hey! I’m Lee — an accounting tutor and professor, and I’ve helped 1,000+ students get through Intro Accounting.",
    "",
    "I set up a page specifically for {{greekLetters}} members taking {{courseCode}}, with short cram videos and practice exams.",
    "",
    "They can study for free here:",
    "{{outreachLink}}",
    "",
    "I’d be happy to hop on a quick 5-minute call and show you how it works. Just text me at 601-201-8759.",
    "",
    "Happy to answer any questions!",
    "",
    "— Lee",
  ].join("\n"),
} as const;

// ── what execs paste ──────────────────────────────────────────────────────────────────────────

/** Council exec → scholarship chairs. Survive Accounting provides the pages; the council only forwards the link. */
export function councilShareMessage(o: { courseCode: string | null | undefined; councilLink: string }): string {
  const c = courseFor(o.courseCode);
  return [
    `Scholarship chairs — Survive Accounting set up ${c} study pages for every chapter, with short cram videos + practice exams. Students can start free.`,
    "",
    "Pick your chapter here to get your member link, GroupMe post, and flyer:",
    o.councilLink,
  ].join("\n");
}

/** Chapter exec (or member) → the house GroupMe. No Exam 1, no GPA line. */
export function chapterGroupMePost(o: { courseCode: string | null | undefined; chapterLink: string }): string {
  const c = courseFor(o.courseCode);
  return [
    `Hey everyone — Survive Accounting set up a page for our chapter with short ${c} cram videos + practice exams.`,
    "",
    `If you're in ${c}, you can study for free here:`,
    o.chapterLink,
  ].join("\n");
}

/** The same post when no chapter is known yet (the campus page, where a reader picks their chapter). */
export function campusGroupMePost(o: { courseCode: string | null | undefined; link: string }): string {
  const c = courseFor(o.courseCode);
  return [
    `Hey everyone — Survive Accounting set up ${c} study pages for every chapter, with short cram videos + practice exams.`,
    "",
    `If you're in ${c}, pick your chapter and study for free here:`,
    o.link,
  ].join("\n");
}

/** A council post that lists every chapter's own link (the partners campaign). */
export function councilChapterListIntro(courseCode: string | null | undefined): string {
  return `Hey all — Survive Accounting set up ${courseFor(courseCode)} study pages for every chapter, with short cram videos + practice exams. Each chapter has its own link:`;
}

/** The council portal post (partners campaign): one link, each chapter finds itself. */
export function councilPortalLines(courseCode: string | null | undefined): string[] {
  const c = courseFor(courseCode);
  return [
    `${c} study pages for every chapter — short cram videos + practice exams. Students can start free.`,
    ``,
    `Built by a tutor who's worked with 1,000+ students.`,
    ``,
    `Your chapter finds itself here:`,
  ];
}

/** A rep's one-line share (rep dashboard). */
export function repShareLine(o: { courseCode: string | null | undefined; chapterName: string | null; shortUrl: string }): string {
  const who = o.chapterName ? `${o.chapterName} — ` : "";
  return `${who}short ${courseFor(o.courseCode)} cram videos + practice exams from Survive Accounting, made for this course. Students can study free: ${o.shortUrl}`;
}

/** A rep's email to a chapter (rep dashboard mailto). */
export function repShareEmail(o: { campusName: string | null; chapterName: string | null; courseCode: string | null | undefined; shortUrl: string }): { subject: string; body: string } {
  const c = (o.courseCode ?? "").trim() || "Intro Accounting";
  return {
    subject: `${c} study page for ${o.chapterName ?? "your chapter"}`,
    body: `Hey!\n\nWanted to pass this along for the chapter — Survive Accounting set up ${c} study pages at ${o.campusName ?? "our school"}: short cram videos + practice exams, by a tutor who's helped 1,000+ students.\n\nStudents can study free here: ${o.shortUrl}\n\nWorth dropping in the group chat.`,
  };
}

// ── the /learn exec heroes ────────────────────────────────────────────────────────────────────

export const COUNCIL_STEPS = ["Send one link", "Chair picks their chapter", "They share with members"] as const;
export const COUNCIL_CHIPS = ["One link for every chapter", "No setup required", "Ready-to-share materials"] as const;

export function councilHero(o: { courseCode: string | null | undefined; schoolName: string }): { headline: string; sub: string; primary: string } {
  return {
    headline: `${courseHeadline(o.courseCode)} prep for every chapter.`,
    sub: `Short cram videos + practice exams for ${o.schoolName} students. Send one link to your scholarship chairs — they pick their chapter and get everything they need to share it with members.`,
    primary: "Send to chapter chairs",
  };
}

export function chairHero(o: { courseCode: string | null | undefined; chapter: string | null }): { headline: string; sub: string; primary: string; secondary: string } {
  const code = (o.courseCode ?? "").trim();
  return {
    headline: code ? `Your ${code} study page is ready.` : "Your chapter's study page is ready.",
    sub: `Short cram videos + practice exams for ${o.chapter ? `${o.chapter} members` : "your members"}. Students can start free — just send the page to the house.`,
    primary: "Copy GroupMe post",
    secondary: "Preview member page",
  };
}

// ── social proof ──────────────────────────────────────────────────────────────────────────────

/** "12 ΒΘΠ members are cramming" / "1 ΒΘΠ member is cramming" — or null. No social proof until there is some. */
export function membersCrammingLine(letters: string | null | undefined, members: number | null | undefined): string | null {
  const n = typeof members === "number" && Number.isFinite(members) ? Math.floor(members) : 0;
  if (n <= 0) return null;
  const who = (letters ?? "").trim();
  return `${n} ${who ? `${who} ` : ""}member${n === 1 ? " is" : "s are"} cramming`;
}

/** The line under a flyer's QR code (print flyer, dark flyer). */
export function flyerCaption(courseCode: string | null | undefined): string {
  return `Short ${courseFor(courseCode)} cram videos + practice exams.`;
}

/** A council officer's email to chapter presidents (partners campaign). */
export function councilPresidentEmailBody(o: { courseCode: string | null | undefined; schoolName: string }): string {
  const c = courseFor(o.courseCode);
  return `${c} hits a lot of our members at once. Survive Accounting makes short ${c} cram videos and practice exams for ${o.schoolName} students, and members can study free — no cost to the chapter.`;
}

/** The one-line group-chat message for a council presidents' chat (link appended by the caller). */
export function councilGroupLine(courseCode: string | null | undefined): string {
  return `${courseFor(courseCode)} study pages for the house ⚡ short cram videos + practice exams, free to study. Each chapter has its own page — find yours:`;
}

/** The DM a campus rep copies for a chapter (the tracked link appended). */
export function repChapterDm(o: { chapterName: string; courseCode: string | null | undefined; shortUrl: string }): string {
  return `Hey! I'm the Survive Accounting rep on campus — we make short ${courseFor(o.courseCode)} cram videos + practice exams for this course. ${o.chapterName} members can study free. Would you share it with the chapter? ${o.shortUrl}`;
}
