// LINK-PREVIEW META — the ONE builder for og:/twitter: tag sets.
//
// Every route that wants a card calls ogMeta() instead of hand-writing the fifteen tags, so a
// page can be missing a card entirely or have a complete one — never a half set that renders as
// a bare grey link in iMessage. TanStack Start dedupes head() meta by name/property with the
// deepest route winning (verified in SSR HTML), so these cleanly override the __root defaults.
//
// ABSOLUTE URLS ONLY. og:url and og:image silently fail in iMessage when relative — that is not
// a style rule, it is the bug this module exists to prevent. Paths go in, absolute comes out.

export const SITE_ORIGIN = "https://surviveaccounting.com";

/** The HOME copy — also the universal fallback when a dynamic page is missing the data its own
 *  template needs. A generic-but-correct card always beats "Survive your {COURSE_CODE} exams." */
export const HOME_OG = {
  title: "Survive your Intro Accounting exams.",
  description:
    "Cram videos + practice exams for intro accounting. Get help from a tutor who's helped 1,000+ students. Start for free, no account needed.",
};

export const DEFAULT_OG_IMAGE = `${SITE_ORIGIN}/og-card.png`;

/** Absolute URL for a campus variant card. The file set is generated by scripts/og-cards.mjs and
 *  committed to public/og/campus/ — one per school in schools.generated. */
export const campusOgImage = (schoolSlug: string) => `${SITE_ORIGIN}/og/campus/${schoolSlug}.png`;

export function ogMeta(o: { title: string; description: string; path: string; image?: string }): Array<Record<string, string>> {
  // THE BRACE GUARD. A template token that survives to production ("Survive your {COURSE_CODE}
  // exams.") is worse than a generic card — fall back to HOME copy and the default image rather
  // than ever shipping one.
  const broken = o.title.includes("{") || o.description.includes("{");
  const title = broken ? HOME_OG.title : o.title;
  const description = broken ? HOME_OG.description : o.description;
  const image = broken ? DEFAULT_OG_IMAGE : (o.image ?? DEFAULT_OG_IMAGE);
  const url = `${SITE_ORIGIN}${o.path}`;
  return [
    { title },
    { name: "description", content: description },
    { property: "og:title", content: title },
    { property: "og:description", content: description },
    { property: "og:type", content: "website" },
    { property: "og:site_name", content: "Survive Accounting" },
    { property: "og:url", content: url },
    { property: "og:image", content: image },
    { property: "og:image:width", content: "1200" },
    { property: "og:image:height", content: "630" },
    { property: "og:image:type", content: "image/png" },
    { name: "twitter:card", content: "summary_large_image" },
    { name: "twitter:title", content: title },
    { name: "twitter:description", content: description },
    { name: "twitter:image", content: image },
  ];
}
