// LINK-PREVIEW META — the ONE builder for og:/twitter: tag sets.
//
// Every route that wants a card calls ogMeta() instead of hand-writing the fifteen tags, so a
// page can be missing a card entirely or have a complete one — never a half set that renders as
// a bare grey link in iMessage. TanStack Start dedupes head() meta by name/property with the
// deepest route winning (verified in SSR HTML), so these cleanly override the __root defaults.
//
// ABSOLUTE URLS ONLY. og:url and og:image silently fail in iMessage when relative — that is not
// a style rule, it is the bug this module exists to prevent. Paths go in, absolute comes out.

export const SITE_ORIGIN = "https://surviveaccounting.com";

/** The HOME copy — also the universal fallback when a dynamic page is missing the data its own
 *  template needs. A generic-but-correct card always beats "Survive your {COURSE_CODE} exams." */
export const HOME_OG = {
  // MATCHES THE PAGE. "Survive your Intro Accounting exams." is not a line that appears anywhere on
  // the site any more, and the preview is the first thing a student reads when a friend texts them
  // the link — it should say what the page says.
  title: "Cram what's on your exam.",
  description: "Cram videos and practice exams for intro accounting. Exam 1 is free.",
};

/** The browser-tab and search-result title for the root and every non-campus page. Longer than the
 *  og:title on purpose: a preview wants the promise, a search result wants the brand with it. */
export const HOME_TITLE = "Survive Accounting — Cram what's on your exam.";

export const DEFAULT_OG_IMAGE = `${SITE_ORIGIN}/og-card.png`;

/** Absolute URL for a campus variant card. The file set is generated by scripts/og-cards.mjs and
 *  committed to public/og/campus/ — one per school in schools.generated. */
export const campusOgImage = (schoolSlug: string) => `${SITE_ORIGIN}/og/campus/${schoolSlug}.png`;


/** VERSION STAMP. Every platform caches a preview by image URL — GroupMe and iMessage for weeks,
 *  with no purge tool between them — so a redesign that reuses the same URL simply never reaches
 *  anyone who has already seen the link. Bump this and every card is a new URL. */
export const OG_IMAGE_VERSION = "1";

/** A campus's prerendered card, version-stamped. The PNGs live in public/og/campus and are
 *  regenerated by scripts/og-cards.mjs; see campusOgImage above for why they are prerendered. */
export const campusOgImageV = (schoolSlug: string) => `${campusOgImage(schoolSlug)}?v=${OG_IMAGE_VERSION}`;

/** A chapter's card, rendered per request (roughly 2,270 letter × colourway combinations is far
 *  too much to commit) and version-stamped the same way. */
export const chapterOgImage = (schoolSlug: string, chapterSlug: string) =>
  `${SITE_ORIGIN}/api/og/${schoolSlug}/${chapterSlug}?v=${OG_IMAGE_VERSION}`;

/** THE SHARE COPY. The title is the half that renders as real text at full size and is often all
 *  that shows beside the image, so it has to stand on its own without the card. */
export const campusShareOg = (courseCode: string | null, campusShort: string) =>
  courseCode
    ? {
        title: `Free ${courseCode} prep at ${campusShort}`,
        description: `Cram videos and practice questions for the whole first exam. Nothing to buy. Built by a tutor who's worked with 1,000+ students.`,
      }
    : HOME_OG;

export const chapterShareOg = (courseCode: string | null, orgShort: string) =>
  courseCode
    ? {
        title: `Free ${courseCode} prep for ${orgShort}`,
        description: `Cram videos and practice questions for the whole first exam — free for every member. Built by a tutor who's worked with 1,000+ students.`,
      }
    : HOME_OG;

export function ogMeta(o: { title: string; description: string; path: string; image?: string }): Array<Record<string, string>> {
  // THE BRACE GUARD. A template token that survives to production ("Survive your {COURSE_CODE}
  // exams.") is worse than a generic card — fall back to HOME copy and the default image rather
  // than ever shipping one.
  const broken = o.title.includes("{") || o.description.includes("{");
  const title = broken ? HOME_OG.title : o.title;
  const description = broken ? HOME_OG.description : o.description;
  const image = broken ? DEFAULT_OG_IMAGE : (o.image ?? DEFAULT_OG_IMAGE);
  const url = `${SITE_ORIGIN}${o.path}`;
  return [
    { title },
    { name: "description", content: description },
    { property: "og:title", content: title },
    { property: "og:description", content: description },
    { property: "og:type", content: "website" },
    { property: "og:site_name", content: "Survive Accounting" },
    { property: "og:url", content: url },
    { property: "og:image", content: image },
    { property: "og:image:width", content: "1200" },
    { property: "og:image:height", content: "630" },
    { property: "og:image:type", content: "image/png" },
    { name: "twitter:card", content: "summary_large_image" },
    { name: "twitter:title", content: title },
    { name: "twitter:description", content: description },
    { name: "twitter:image", content: image },
  ];
}
