// GENERATED by migration/supabase-migrations/gen_schools.ts -- DO NOT EDIT BY HAND.
// The database is the source of truth. Regenerate after any campus seed change.
// 119 campuses (16 SEC). SEC colours come from brand.tsx by design -- see the generator header.
// Aliases source: seed CSV (search_aliases column not yet applied).

export type GeneratedSchool = {
  id: string; campusId: string; slug: string; name: string;
  isSec: boolean; courseCode: string | null;
  c1: string | null; c2: string | null;
  /** Matched in search, NEVER displayed. */
  aliases: string[];
};

export const GENERATED_SCHOOLS: GeneratedSchool[] = [
  {
    "id": "alabama",
    "campusId": "b3af67c6-99a5-4677-83d5-aa7d11a89c17",
    "slug": "university-of-alabama",
    "name": "Alabama",
    "isSec": true,
    "courseCode": "AC 210",
    "c1": "#9E1B32",
    "c2": "#F1F2F3",
    "aliases": [
      "Bama",
      "Roll Tide",
      "Crimson Tide",
      "UA",
      "University of Alabama"
    ]
  },
  {
    "id": "albany-state-university",
    "campusId": "03ce5ea1-240d-4a8a-a7a6-c35e76aeb549",
    "slug": "albany-state-university",
    "name": "Albany State University",
    "isSec": false,
    "courseCode": "ACCT 2101",
    "c1": "#FFD700",
    "c2": "#000080",
    "aliases": []
  },
  {
    "id": "american-university",
    "campusId": "bfdddcff-55b3-4446-82c3-fa31be4c3224",
    "slug": "american-university",
    "name": "American University",
    "isSec": false,
    "courseCode": "ACCT 240",
    "c1": "#C8102E",
    "c2": "#003A70",
    "aliases": []
  },
  {
    "id": "arizona",
    "campusId": "cfd87c76-6af7-4e32-b53a-6c091f19f179",
    "slug": "university-of-arizona",
    "name": "Arizona",
    "isSec": false,
    "courseCode": "ACCT 200",
    "c1": "#AB0520",
    "c2": "#FFFFFF",
    "aliases": [
      "U of A",
      "University of Arizona"
    ]
  },
  {
    "id": "arizona-state",
    "campusId": "45315cbf-6a35-4067-bdcf-0ec418fac4f9",
    "slug": "arizona-state-university",
    "name": "Arizona State",
    "isSec": false,
    "courseCode": "ACC 231",
    "c1": "#8C1D40",
    "c2": "#FFC627",
    "aliases": [
      "ASU",
      "Arizona State University"
    ]
  },
  {
    "id": "arkansas",
    "campusId": "e631c8de-37a3-4aae-a948-a64bd20ea4c5",
    "slug": "university-of-arkansas",
    "name": "Arkansas",
    "isSec": true,
    "courseCode": "ACCT 2013",
    "c1": "#9D2235",
    "c2": "#FFFFFF",
    "aliases": [
      "Razorbacks",
      "Fayetteville",
      "University of Arkansas"
    ]
  },
  {
    "id": "arkansas-state-university",
    "campusId": "78604ee3-811c-4b88-8bdd-3f198fa7df10",
    "slug": "arkansas-state-university",
    "name": "Arkansas State University",
    "isSec": false,
    "courseCode": "ACCT 2023",
    "c1": "#CC092F",
    "c2": "#000000",
    "aliases": []
  },
  {
    "id": "auburn",
    "campusId": "e330e87c-5467-4c05-9d3d-6cd2398de036",
    "slug": "auburn-university",
    "name": "Auburn",
    "isSec": true,
    "courseCode": "ACCT 2110",
    "c1": "#0C2340",
    "c2": "#E87722",
    "aliases": [
      "AU",
      "War Eagle",
      "Tigers",
      "Auburn University"
    ]
  },
  {
    "id": "ball-state-university",
    "campusId": "2567ae60-6898-4652-a62a-13a73c18e2c5",
    "slug": "ball-state-university",
    "name": "Ball State University",
    "isSec": false,
    "courseCode": "ACC 201",
    "c1": "#BA0C2F",
    "c2": "#FFFFFF",
    "aliases": []
  },
  {
    "id": "baylor",
    "campusId": "30dd76fa-6908-407a-b8d4-dcd75a9cfd47",
    "slug": "baylor-university",
    "name": "Baylor",
    "isSec": false,
    "courseCode": "ACC 2303",
    "c1": "#154734",
    "c2": "#FFB81C",
    "aliases": [
      "BU",
      "Baylor University"
    ]
  },
  {
    "id": "binghamton-university",
    "campusId": "d7abb1b4-197e-4556-88fd-b2fc800951a9",
    "slug": "binghamton-university",
    "name": "Binghamton University",
    "isSec": false,
    "courseCode": "ACCT 211",
    "c1": "#00703C",
    "c2": "#FFFFFF",
    "aliases": []
  },
  {
    "id": "brandeis-university",
    "campusId": "f8cd97cd-6ba9-4282-abf1-2c2828fb627c",
    "slug": "brandeis-university",
    "name": "Brandeis University",
    "isSec": false,
    "courseCode": "BUS 6a",
    "c1": "#003478",
    "c2": "#FFFFFF",
    "aliases": []
  },
  {
    "id": "cal-poly",
    "campusId": "9fcd2964-e58e-496b-9b14-63b9892506cd",
    "slug": "california-polytechnic-state-university",
    "name": "Cal Poly",
    "isSec": false,
    "courseCode": "BUS 2214",
    "c1": "#154734",
    "c2": "#BD8B13",
    "aliases": [
      "Cal Poly SLO",
      "cal poly san luis obispo",
      "California Polytechnic State University"
    ]
  },
  {
    "id": "campbell-university",
    "campusId": "c3dd686d-977b-4495-9565-1b38202941c7",
    "slug": "campbell-university",
    "name": "Campbell University",
    "isSec": false,
    "courseCode": "ACCT 215",
    "c1": "#FF6600",
    "c2": "#000000",
    "aliases": []
  },
  {
    "id": "cincinnati",
    "campusId": "018d6b9d-f168-4e59-9df1-cdc8563ef577",
    "slug": "university-of-cincinnati",
    "name": "Cincinnati",
    "isSec": false,
    "courseCode": "ACCT 2081",
    "c1": "#E00122",
    "c2": "#000000",
    "aliases": [
      "University of Cincinnati"
    ]
  },
  {
    "id": "clemson",
    "campusId": "b35abe46-764e-4b10-9cb4-d3523dd1a2ee",
    "slug": "clemson-university",
    "name": "Clemson",
    "isSec": false,
    "courseCode": "ACCT 2010",
    "c1": "#F56600",
    "c2": "#522D80",
    "aliases": [
      "Clemson University"
    ]
  },
  {
    "id": "cleveland-state-university",
    "campusId": "c0aa702e-76fa-422a-86ba-13ab222dd072",
    "slug": "cleveland-state-university",
    "name": "Cleveland State University",
    "isSec": false,
    "courseCode": "ACT 221",
    "c1": "#0F2044",
    "c2": "#FFFFFF",
    "aliases": []
  },
  {
    "id": "colorado",
    "campusId": "be0aadc8-b5e3-4af6-a75f-7284af0885f3",
    "slug": "university-of-colorado-boulder",
    "name": "Colorado",
    "isSec": false,
    "courseCode": "BCOR 2203",
    "c1": "#CFB87C",
    "c2": "#000000",
    "aliases": [
      "CU Boulder",
      "University of Colorado Boulder"
    ]
  },
  {
    "id": "colorado-state",
    "campusId": "90f8fda4-8901-441f-8c0d-3b1d69c60e63",
    "slug": "colorado-state-university",
    "name": "Colorado State",
    "isSec": false,
    "courseCode": "ACT 210",
    "c1": "#1E4D2B",
    "c2": "#C8C372",
    "aliases": [
      "Colorado State University"
    ]
  },
  {
    "id": "delaware",
    "campusId": "134547c6-fcf2-4a0f-9c0c-6612fb4408dc",
    "slug": "university-of-delaware",
    "name": "Delaware",
    "isSec": false,
    "courseCode": "ACCT 207",
    "c1": "#00539F",
    "c2": "#FFD200",
    "aliases": [
      "University of Delaware"
    ]
  },
  {
    "id": "drexel-university",
    "campusId": "71d2787f-9b4b-41c9-bd67-270890fb5db8",
    "slug": "drexel-university",
    "name": "Drexel University",
    "isSec": false,
    "courseCode": "ACCT 115",
    "c1": "#07294D",
    "c2": "#FFC600",
    "aliases": []
  },
  {
    "id": "eastern-michigan-university",
    "campusId": "f3b7ae70-62da-4b7c-886b-db819d133472",
    "slug": "eastern-michigan-university",
    "name": "Eastern Michigan University",
    "isSec": false,
    "courseCode": "ACC 240",
    "c1": "#006633",
    "c2": "#FFFFFF",
    "aliases": []
  },
  {
    "id": "florida",
    "campusId": "4c5126b1-3fe0-48fe-a1db-1e41d06e4642",
    "slug": "university-of-florida",
    "name": "Florida",
    "isSec": true,
    "courseCode": "ACG 2021",
    "c1": "#0021A5",
    "c2": "#FA4616",
    "aliases": [
      "UF",
      "Gators",
      "University of Florida"
    ]
  },
  {
    "id": "florida-atlantic-university",
    "campusId": "42c3eddd-939e-48ae-ba21-2d04bdadb84e",
    "slug": "florida-atlantic-university",
    "name": "Florida Atlantic University",
    "isSec": false,
    "courseCode": "ACG 2021",
    "c1": "#003366",
    "c2": "#C8102E",
    "aliases": []
  },
  {
    "id": "florida-international-university",
    "campusId": "a20b5f96-7a39-4a87-8fc8-30a577bac114",
    "slug": "florida-international-university",
    "name": "Florida International University",
    "isSec": false,
    "courseCode": "ACG 2021",
    "c1": "#081E3F",
    "c2": "#B6862C",
    "aliases": []
  },
  {
    "id": "florida-state",
    "campusId": "63662ceb-5770-4dad-8c3f-0021f3924b98",
    "slug": "florida-state-university",
    "name": "Florida State",
    "isSec": false,
    "courseCode": "ACG 2021",
    "c1": "#782F40",
    "c2": "#CEB888",
    "aliases": [
      "FSU",
      "Florida State University"
    ]
  },
  {
    "id": "furman-university",
    "campusId": "c16a3be6-feed-4831-b038-35b4e1aacc63",
    "slug": "furman-university",
    "name": "Furman University",
    "isSec": false,
    "courseCode": "ACC 111",
    "c1": "#663399",
    "c2": "#FFFFFF",
    "aliases": []
  },
  {
    "id": "george-mason-university",
    "campusId": "60e3b6bc-611e-4254-8b7c-7e8b45412159",
    "slug": "george-mason-university",
    "name": "George Mason University",
    "isSec": false,
    "courseCode": "ACCT 203",
    "c1": "#006633",
    "c2": "#FFCC33",
    "aliases": []
  },
  {
    "id": "george-washington-university",
    "campusId": "99b33713-d32a-4089-b16b-87a59166d2ed",
    "slug": "george-washington-university",
    "name": "George Washington University",
    "isSec": false,
    "courseCode": "ACCY 2001",
    "c1": "#033C5A",
    "c2": "#AA9868",
    "aliases": []
  },
  {
    "id": "georgia",
    "campusId": "3f570e37-5394-4058-baab-508948befedb",
    "slug": "university-of-georgia",
    "name": "Georgia",
    "isSec": true,
    "courseCode": "ACCT 2101",
    "c1": "#BA0C2F",
    "c2": "#000000",
    "aliases": [
      "UGA",
      "Bulldogs",
      "University of Georgia"
    ]
  },
  {
    "id": "georgia-state-university",
    "campusId": "fea35ec6-5a55-4e27-9fe0-021c0a583253",
    "slug": "georgia-state-university",
    "name": "Georgia State University",
    "isSec": false,
    "courseCode": "ACCT 2101",
    "c1": "#0039A6",
    "c2": "#8B0000",
    "aliases": []
  },
  {
    "id": "georgia-tech",
    "campusId": "497c0c67-8e6a-4d5c-a1f2-2e7b78bce77f",
    "slug": "georgia-institute-of-technology",
    "name": "Georgia Tech",
    "isSec": false,
    "courseCode": "ACCT 2101",
    "c1": "#B3A369",
    "c2": "#003057",
    "aliases": [
      "Georgia Institute of Technology"
    ]
  },
  {
    "id": "houston",
    "campusId": "9aad4852-d3b1-4091-8157-acf427d8c88a",
    "slug": "university-of-houston",
    "name": "Houston",
    "isSec": false,
    "courseCode": "ACCT 2301",
    "c1": "#C8102E",
    "c2": "#FFFFFF",
    "aliases": [
      "UH",
      "University of Houston"
    ]
  },
  {
    "id": "howard-university",
    "campusId": "0b7532ee-e905-4012-b835-ab99faf022d6",
    "slug": "howard-university",
    "name": "Howard University",
    "isSec": false,
    "courseCode": "ACCT 201",
    "c1": "#003A63",
    "c2": "#CC092F",
    "aliases": []
  },
  {
    "id": "illinois",
    "campusId": "f56a0047-8688-48a1-b671-22ebcf12eb28",
    "slug": "university-of-illinois-urbana-champaign",
    "name": "Illinois",
    "isSec": false,
    "courseCode": "ACCY 201",
    "c1": "#FF5F05",
    "c2": "#13294B",
    "aliases": [
      "UIUC",
      "U of I",
      "university of illinois",
      "University of Illinois Urbana-Champaign"
    ]
  },
  {
    "id": "indiana",
    "campusId": "feab5578-893a-48c1-88c4-f4dc7616ac79",
    "slug": "indiana-university-bloomington",
    "name": "Indiana",
    "isSec": false,
    "courseCode": "BUS-A 201",
    "c1": "#990000",
    "c2": "#FFFFFF",
    "aliases": [
      "IU",
      "Indiana University",
      "Indiana University Bloomington"
    ]
  },
  {
    "id": "iowa",
    "campusId": "39e11bf9-6201-41d5-8c50-489b8259032a",
    "slug": "university-of-iowa",
    "name": "Iowa",
    "isSec": false,
    "courseCode": "ACCT:2100",
    "c1": "#FFCD00",
    "c2": "#000000",
    "aliases": [
      "University of Iowa"
    ]
  },
  {
    "id": "iowa-state",
    "campusId": "4782ef17-0a49-4e4b-8856-40e748fe6004",
    "slug": "iowa-state-university",
    "name": "Iowa State",
    "isSec": false,
    "courseCode": "ACCT 2840",
    "c1": "#C8102E",
    "c2": "#F1BE48",
    "aliases": [
      "Iowa State University"
    ]
  },
  {
    "id": "jacksonville-state-university",
    "campusId": "01668df5-a744-4307-b733-2db6e8cde542",
    "slug": "jacksonville-state-university",
    "name": "Jacksonville State University",
    "isSec": false,
    "courseCode": "ACC 200",
    "c1": "#CC092F",
    "c2": "#FFFFFF",
    "aliases": []
  },
  {
    "id": "james-madison",
    "campusId": "7d89723d-6d46-46c6-a059-e5875ff118a7",
    "slug": "james-madison-university",
    "name": "James Madison",
    "isSec": false,
    "courseCode": "COB 241",
    "c1": "#450084",
    "c2": "#CBB677",
    "aliases": [
      "JMU",
      "James Madison University"
    ]
  },
  {
    "id": "kansas",
    "campusId": "da89805a-e508-4bda-948c-e546dc78b110",
    "slug": "university-of-kansas",
    "name": "Kansas",
    "isSec": false,
    "courseCode": "ACCT 200",
    "c1": "#0051BA",
    "c2": "#E8000D",
    "aliases": [
      "KU",
      "University of Kansas"
    ]
  },
  {
    "id": "kansas-state",
    "campusId": "4dde3052-393d-4161-98da-23dde61901dd",
    "slug": "kansas-state-university",
    "name": "Kansas State",
    "isSec": false,
    "courseCode": "ACCTG 241",
    "c1": "#512888",
    "c2": "#FFFFFF",
    "aliases": [
      "K-State",
      "Kansas State University"
    ]
  },
  {
    "id": "kentucky",
    "campusId": "ae339230-577e-4569-a7d1-d1e45d1cfe91",
    "slug": "university-of-kentucky",
    "name": "Kentucky",
    "isSec": true,
    "courseCode": "ACC 201",
    "c1": "#0033A0",
    "c2": "#FFFFFF",
    "aliases": [
      "UK",
      "Wildcats",
      "University of Kentucky"
    ]
  },
  {
    "id": "lamar-university",
    "campusId": "503ab8f8-7be1-496d-9b82-2e4392bfd188",
    "slug": "lamar-university",
    "name": "Lamar University",
    "isSec": false,
    "courseCode": "ACCT 2301",
    "c1": "#C8102E",
    "c2": "#000000",
    "aliases": []
  },
  {
    "id": "louisville",
    "campusId": "abad6121-4309-4f35-a13c-beba333d56dc",
    "slug": "university-of-louisville",
    "name": "Louisville",
    "isSec": false,
    "courseCode": "ACCT 201",
    "c1": "#AD0000",
    "c2": "#FFFFFF",
    "aliases": [
      "UofL",
      "University of Louisville"
    ]
  },
  {
    "id": "loyola-university-chicago",
    "campusId": "ce1c0370-a602-4ae8-94a5-a45ab40cf0d2",
    "slug": "loyola-university-chicago",
    "name": "Loyola University Chicago",
    "isSec": false,
    "courseCode": "ACCT 201",
    "c1": "#862633",
    "c2": "#FFC72A",
    "aliases": []
  },
  {
    "id": "lsu",
    "campusId": "698dd98f-dd92-46c1-8f28-e930568cb15d",
    "slug": "louisiana-state-university",
    "name": "LSU",
    "isSec": true,
    "courseCode": "ACCT 2001",
    "c1": "#461D7C",
    "c2": "#FDD023",
    "aliases": [
      "Louisiana State",
      "Tigers",
      "Baton Rouge",
      "Louisiana State University"
    ]
  },
  {
    "id": "maryland",
    "campusId": "b2c34d1b-f623-4206-99e3-287f52e82fcd",
    "slug": "university-of-maryland",
    "name": "Maryland",
    "isSec": false,
    "courseCode": "BMGT 220",
    "c1": "#E21833",
    "c2": "#FFD200",
    "aliases": [
      "UMD",
      "University of Maryland"
    ]
  },
  {
    "id": "miami",
    "campusId": "c2dbd5ac-8dbd-4488-92da-546c361fd88e",
    "slug": "university-of-miami",
    "name": "Miami",
    "isSec": false,
    "courseCode": "ACC 211",
    "c1": "#F47321",
    "c2": "#005030",
    "aliases": [
      "Miami FL",
      "University of Miami"
    ]
  },
  {
    "id": "miami-oh",
    "campusId": "cc8d19b7-6f88-4162-af9b-629c9c9b91c0",
    "slug": "miami-university-ohio",
    "name": "Miami (OH)",
    "isSec": false,
    "courseCode": "ACC 221",
    "c1": "#C8102E",
    "c2": "#FFFFFF",
    "aliases": [
      "Miami Ohio",
      "Miami University"
    ]
  },
  {
    "id": "michigan-state",
    "campusId": "efe5a52b-cca0-43c5-b655-7e2d758945d8",
    "slug": "michigan-state-university",
    "name": "Michigan State",
    "isSec": false,
    "courseCode": "ACC 201",
    "c1": "#18453B",
    "c2": "#FFFFFF",
    "aliases": [
      "Michigan State University"
    ]
  },
  {
    "id": "minnesota",
    "campusId": "6a03001e-d222-4c4e-9437-1cab7241feaa",
    "slug": "university-of-minnesota",
    "name": "Minnesota",
    "isSec": false,
    "courseCode": "ACCT 2051",
    "c1": "#7A0019",
    "c2": "#FFCC33",
    "aliases": [
      "UMN",
      "University of Minnesota"
    ]
  },
  {
    "id": "mississippi-state",
    "campusId": "95246fc8-1ce6-409e-b454-d03c82766719",
    "slug": "mississippi-state-university",
    "name": "Mississippi State",
    "isSec": true,
    "courseCode": "ACC 2013",
    "c1": "#660000",
    "c2": "#C8C8C8",
    "aliases": [
      "MSU",
      "Miss State",
      "Bulldogs",
      "Starkville",
      "Mississippi State University"
    ]
  },
  {
    "id": "mizzou",
    "campusId": "f16686c2-edc6-43f8-9638-6890f52c829a",
    "slug": "university-of-missouri",
    "name": "Mizzou",
    "isSec": true,
    "courseCode": "ACCTCY 2026",
    "c1": "#F1B82D",
    "c2": "#000000",
    "aliases": [
      "Missouri",
      "MU",
      "Tigers",
      "University of Missouri"
    ]
  },
  {
    "id": "morehouse-college",
    "campusId": "22af1952-1da1-45e4-8128-b977774a7936",
    "slug": "morehouse-college",
    "name": "Morehouse College",
    "isSec": false,
    "courseCode": "HBA 201",
    "c1": "#800020",
    "c2": "#FFFFFF",
    "aliases": []
  },
  {
    "id": "nc-state",
    "campusId": "26fec746-f7a8-48d0-8ac6-3bda7c78d82f",
    "slug": "north-carolina-state-university",
    "name": "NC State",
    "isSec": false,
    "courseCode": "ACC 210",
    "c1": "#CC0000",
    "c2": "#FFFFFF",
    "aliases": [
      "NCSU",
      "North Carolina State University"
    ]
  },
  {
    "id": "nebraska",
    "campusId": "2e0aaa41-7bd2-453d-9a9d-32c53074cc9c",
    "slug": "university-of-nebraska-lincoln",
    "name": "Nebraska",
    "isSec": false,
    "courseCode": "ACCT 201",
    "c1": "#D00000",
    "c2": "#F5F1E7",
    "aliases": [
      "university of nebraska",
      "University of Nebraska-Lincoln"
    ]
  },
  {
    "id": "new-york-university",
    "campusId": "62f42404-8006-4fa6-9068-516683198e09",
    "slug": "new-york-university",
    "name": "New York University",
    "isSec": false,
    "courseCode": "ACCT-UB 1",
    "c1": "#57068c",
    "c2": "#ffffff",
    "aliases": []
  },
  {
    "id": "north-carolina",
    "campusId": "ffef200f-6667-455f-a599-08987f16e7fa",
    "slug": "university-of-north-carolina-at-chapel-hill",
    "name": "North Carolina",
    "isSec": false,
    "courseCode": "BUSI 407",
    "c1": "#4B9CD3",
    "c2": "#13294B",
    "aliases": [
      "UNC",
      "university of north carolina",
      "University of North Carolina at Chapel Hill"
    ]
  },
  {
    "id": "north-dakota-state-university",
    "campusId": "247b6ca0-f442-4b46-9093-595086f24a23",
    "slug": "north-dakota-state-university",
    "name": "North Dakota State University",
    "isSec": false,
    "courseCode": "ACCT 200",
    "c1": "#006633",
    "c2": "#FFCC33",
    "aliases": []
  },
  {
    "id": "northeastern-university",
    "campusId": "3d62ef87-3f1a-4060-826c-97586e2d3ede",
    "slug": "northeastern-university",
    "name": "Northeastern University",
    "isSec": false,
    "courseCode": "ACCT 1201",
    "c1": "#C8102E",
    "c2": "#000000",
    "aliases": []
  },
  {
    "id": "northwestern",
    "campusId": "d0190710-b330-4159-9927-65a9c37409eb",
    "slug": "northwestern-university",
    "name": "Northwestern",
    "isSec": false,
    "courseCode": "ACCOUNT 201",
    "c1": "#4E2A84",
    "c2": "#FFFFFF",
    "aliases": [
      "NU",
      "Northwestern University"
    ]
  },
  {
    "id": "ohio-state",
    "campusId": "1e6b6504-3a9c-44e2-81a9-ee961f66563a",
    "slug": "ohio-state-university",
    "name": "Ohio State",
    "isSec": false,
    "courseCode": "ACCTMIS 2200",
    "c1": "#BA0C2F",
    "c2": "#A7B1B7",
    "aliases": [
      "tOSU",
      "Ohio State University"
    ]
  },
  {
    "id": "oklahoma",
    "campusId": "91e62f9c-43b0-41f3-a84d-002824754da6",
    "slug": "university-of-oklahoma",
    "name": "Oklahoma",
    "isSec": true,
    "courseCode": "ACCT 2113",
    "c1": "#841617",
    "c2": "#FDF9D8",
    "aliases": [
      "OU",
      "Sooners",
      "University of Oklahoma"
    ]
  },
  {
    "id": "oklahoma-state",
    "campusId": "d8ed77fe-4aac-444b-9815-261642ee1052",
    "slug": "oklahoma-state-university",
    "name": "Oklahoma State",
    "isSec": false,
    "courseCode": "ACCT 2103",
    "c1": "#FE5C00",
    "c2": "#000000",
    "aliases": [
      "Okie State",
      "Oklahoma State University"
    ]
  },
  {
    "id": "old-dominion-university",
    "campusId": "18f4bb62-8715-4e8f-941d-748768316b75",
    "slug": "old-dominion-university",
    "name": "Old Dominion University",
    "isSec": false,
    "courseCode": "ACCT 201",
    "c1": "#003366",
    "c2": "#C5C5C5",
    "aliases": []
  },
  {
    "id": "ole-miss",
    "campusId": "7b92a320-b196-43f2-a241-77a0805816fe",
    "slug": "university-of-mississippi",
    "name": "Ole Miss",
    "isSec": true,
    "courseCode": "ACCY 201",
    "c1": "#14213D",
    "c2": "#CE1126",
    "aliases": [
      "University of Mississippi",
      "UM",
      "OM",
      "Rebels",
      "Oxford"
    ]
  },
  {
    "id": "oregon",
    "campusId": "62187d7a-6154-4167-9c3d-04fecdc57354",
    "slug": "university-of-oregon",
    "name": "Oregon",
    "isSec": false,
    "courseCode": "BA 211Z",
    "c1": "#007030",
    "c2": "#FEE11A",
    "aliases": [
      "UO",
      "University of Oregon"
    ]
  },
  {
    "id": "oregon-state",
    "campusId": "0f207a42-7b5b-46f3-8d9b-7b753a0451fe",
    "slug": "oregon-state-university",
    "name": "Oregon State",
    "isSec": false,
    "courseCode": "BA 211Z",
    "c1": "#D73F09",
    "c2": "#000000",
    "aliases": [
      "Oregon State University"
    ]
  },
  {
    "id": "penn-state",
    "campusId": "afb9cd13-7cd5-48fb-8416-e358d02bc2ae",
    "slug": "pennsylvania-state-university",
    "name": "Penn State",
    "isSec": false,
    "courseCode": "ACCTG 211",
    "c1": "#001E44",
    "c2": "#FFFFFF",
    "aliases": [
      "PSU",
      "Penn St",
      "Pennsylvania State University"
    ]
  },
  {
    "id": "pittsburgh",
    "campusId": "2668a8b5-52c6-4a41-b2df-a83f29330d3b",
    "slug": "university-of-pittsburgh",
    "name": "Pittsburgh",
    "isSec": false,
    "courseCode": "BUSACC 0030",
    "c1": "#003594",
    "c2": "#FFB81C",
    "aliases": [
      "Pitt",
      "University of Pittsburgh"
    ]
  },
  {
    "id": "purdue",
    "campusId": "0da1dbed-01e6-4e98-a023-38bf102e8853",
    "slug": "purdue-university",
    "name": "Purdue",
    "isSec": false,
    "courseCode": "ACCT 20000",
    "c1": "#CFB991",
    "c2": "#000000",
    "aliases": [
      "Purdue University"
    ]
  },
  {
    "id": "rochester-institute-of-technology",
    "campusId": "82ddec8e-3ba1-43c1-a445-7efee49786e8",
    "slug": "rochester-institute-of-technology",
    "name": "Rochester Institute of Technology",
    "isSec": false,
    "courseCode": "ACCT 110",
    "c1": "#F76902",
    "c2": "#594236",
    "aliases": []
  },
  {
    "id": "rutgers",
    "campusId": "f2bb9523-3512-405c-bcc1-ee2ae517f08c",
    "slug": "rutgers-university",
    "name": "Rutgers",
    "isSec": false,
    "courseCode": "33:010:272",
    "c1": "#CC0033",
    "c2": "#FFFFFF",
    "aliases": [
      "Rutgers University"
    ]
  },
  {
    "id": "sam-houston-state-university",
    "campusId": "9619e982-14a0-4a2a-b768-75a1443715ff",
    "slug": "sam-houston-state-university",
    "name": "Sam Houston State University",
    "isSec": false,
    "courseCode": "ACCT 2301",
    "c1": "#FF6A00",
    "c2": "#FFFFFF",
    "aliases": []
  },
  {
    "id": "san-diego-state",
    "campusId": "7325256b-319c-4948-b5a0-5f2016f38dca",
    "slug": "san-diego-state-university",
    "name": "San Diego State",
    "isSec": false,
    "courseCode": "ACCTG 201",
    "c1": "#A6192E",
    "c2": "#FFFFFF",
    "aliases": [
      "SDSU",
      "San Diego State University"
    ]
  },
  {
    "id": "san-francisco-state-university",
    "campusId": "599b6c9e-4316-48a3-a647-7e0a782e7ed2",
    "slug": "san-francisco-state-university",
    "name": "San Francisco State University",
    "isSec": false,
    "courseCode": "ACCT 100",
    "c1": "#4A2C7C",
    "c2": "#FFB81C",
    "aliases": []
  },
  {
    "id": "savannah-state-university",
    "campusId": "acde21cd-fdf6-410a-a141-a09eaaf24bac",
    "slug": "savannah-state-university",
    "name": "Savannah State University",
    "isSec": false,
    "courseCode": "ACCT 2101",
    "c1": "#003366",
    "c2": "#FF6600",
    "aliases": []
  },
  {
    "id": "smu",
    "campusId": "fb5f2ade-df5d-4e16-9557-33d1232ffaba",
    "slug": "southern-methodist-university",
    "name": "SMU",
    "isSec": false,
    "courseCode": "ACCT 2301",
    "c1": "#CC0035",
    "c2": "#FFFFFF",
    "aliases": [
      "Southern Methodist University"
    ]
  },
  {
    "id": "south-carolina",
    "campusId": "5f5bd18d-b92f-4d56-aced-23bce4c983d5",
    "slug": "university-of-south-carolina",
    "name": "South Carolina",
    "isSec": true,
    "courseCode": "ACCT 225",
    "c1": "#73000A",
    "c2": "#000000",
    "aliases": [
      "USC",
      "South Carolina Gamecocks",
      "Gamecocks",
      "University of South Carolina"
    ]
  },
  {
    "id": "stephen-f-austin-state-university",
    "campusId": "fefc04a6-4fad-4a75-a7ff-1bf58ff91bec",
    "slug": "stephen-f-austin-state-university",
    "name": "Stephen F. Austin State University",
    "isSec": false,
    "courseCode": "ACCT 2301",
    "c1": "#663399",
    "c2": "#FFFFFF",
    "aliases": []
  },
  {
    "id": "suffolk-university",
    "campusId": "ac82bfcf-5d9d-45a3-a652-89b5f992485f",
    "slug": "suffolk-university",
    "name": "Suffolk University",
    "isSec": false,
    "courseCode": "ACCT 201",
    "c1": "#003DA5",
    "c2": "#FFD100",
    "aliases": []
  },
  {
    "id": "syracuse",
    "campusId": "4528bb03-6544-43ad-bb02-17a0f21130f9",
    "slug": "syracuse-university",
    "name": "Syracuse",
    "isSec": false,
    "courseCode": "ACC 151",
    "c1": "#F76900",
    "c2": "#000E54",
    "aliases": [
      "Syracuse University"
    ]
  },
  {
    "id": "tcu",
    "campusId": "8a987f3f-ef08-4f2f-be5c-d18e032b6796",
    "slug": "texas-christian-university",
    "name": "TCU",
    "isSec": false,
    "courseCode": "ACCT 20353",
    "c1": "#4D1979",
    "c2": "#FFFFFF",
    "aliases": [
      "Texas Christian University"
    ]
  },
  {
    "id": "tennessee",
    "campusId": "9c4775be-7d82-4a3e-840c-349c5e15d8e8",
    "slug": "university-of-tennessee-knoxville",
    "name": "Tennessee",
    "isSec": true,
    "courseCode": "ACCT 200",
    "c1": "#FF8200",
    "c2": "#FFFFFF",
    "aliases": [
      "UT Knoxville",
      "Vols",
      "Volunteers",
      "University of Tennessee, Knoxville"
    ]
  },
  {
    "id": "texas",
    "campusId": "faad6039-be72-4f5c-8ad5-ca7b95e2889f",
    "slug": "university-of-texas-at-austin",
    "name": "Texas",
    "isSec": true,
    "courseCode": "ACC 311",
    "c1": "#BF5700",
    "c2": "#FFFFFF",
    "aliases": [
      "UT Austin",
      "UT",
      "Longhorns",
      "University of Texas at Austin"
    ]
  },
  {
    "id": "texas-aandm",
    "campusId": "92e4a5d9-eeb3-4065-ac8a-5a4390fbc584",
    "slug": "texas-aandm-university",
    "name": "Texas A&M",
    "isSec": true,
    "courseCode": "ACCT 229",
    "c1": "#500000",
    "c2": "#FFFFFF",
    "aliases": [
      "A&M",
      "TAMU",
      "Aggies",
      "College Station",
      "Texas A&M University"
    ]
  },
  {
    "id": "texas-state-university",
    "campusId": "1ad51593-c384-497f-9c1d-ea8afb34d5b5",
    "slug": "texas-state-university",
    "name": "Texas State University",
    "isSec": false,
    "courseCode": "ACC 2361",
    "c1": "#501214",
    "c2": "#6A2C91",
    "aliases": []
  },
  {
    "id": "texas-tech",
    "campusId": "e7fff2aa-78fe-459f-9211-2584fae1f5ee",
    "slug": "texas-tech-university",
    "name": "Texas Tech",
    "isSec": false,
    "courseCode": "ACCT 2300",
    "c1": "#E90802",
    "c2": "#000000",
    "aliases": [
      "TTU",
      "Texas Tech University"
    ]
  },
  {
    "id": "the-university-of-texas-at-arlington",
    "campusId": "c34899c1-0fcd-4a20-b9a9-5cec52734b70",
    "slug": "the-university-of-texas-at-arlington",
    "name": "The University of Texas at Arlington",
    "isSec": false,
    "courseCode": "ACCT 2301",
    "c1": "#003366",
    "c2": "#FF6600",
    "aliases": []
  },
  {
    "id": "the-university-of-texas-at-dallas",
    "campusId": "408b44a5-1704-40d5-965d-dc02cb78f55c",
    "slug": "the-university-of-texas-at-dallas",
    "name": "The University of Texas at Dallas",
    "isSec": false,
    "courseCode": "ACCT 2301",
    "c1": "#C75B12",
    "c2": "#00703C",
    "aliases": []
  },
  {
    "id": "the-university-of-texas-at-san-antonio",
    "campusId": "980fcc26-676e-4e05-883e-8ab55867020a",
    "slug": "the-university-of-texas-at-san-antonio",
    "name": "The University of Texas at San Antonio",
    "isSec": false,
    "courseCode": "ACC 2013",
    "c1": "#F15A22",
    "c2": "#0C2340",
    "aliases": []
  },
  {
    "id": "troy-university",
    "campusId": "4d5deb87-3fe2-4437-9c93-4830ca167366",
    "slug": "troy-university",
    "name": "Troy University",
    "isSec": false,
    "courseCode": "ACT 2291",
    "c1": "#8B0000",
    "c2": "#C0C0C0",
    "aliases": []
  },
  {
    "id": "ucf",
    "campusId": "9fc579bc-bed2-4e8b-9c89-0958f7edda42",
    "slug": "university-of-central-florida",
    "name": "UCF",
    "isSec": false,
    "courseCode": "ACG 2021",
    "c1": "#000000",
    "c2": "#FFC904",
    "aliases": [
      "University of Central Florida"
    ]
  },
  {
    "id": "university-of-colorado-colorado-springs",
    "campusId": "85e0b395-ec04-418c-a583-3a1e88df2c7c",
    "slug": "university-of-colorado-colorado-springs",
    "name": "University of Colorado Colorado Springs",
    "isSec": false,
    "courseCode": "ACCT 2010",
    "c1": "#CFB87C",
    "c2": "#1E4D72",
    "aliases": []
  },
  {
    "id": "university-of-idaho",
    "campusId": "fa9fb190-4098-47eb-8dce-5ef934435b3d",
    "slug": "university-of-idaho",
    "name": "University of Idaho",
    "isSec": false,
    "courseCode": "ACCT 201",
    "c1": "#FFB300",
    "c2": "#8B8B8B",
    "aliases": []
  },
  {
    "id": "university-of-illinois-chicago",
    "campusId": "9af2ea11-48be-4d06-b454-7949013dbe14",
    "slug": "university-of-illinois-chicago",
    "name": "University of Illinois Chicago",
    "isSec": false,
    "courseCode": "ACTG 210",
    "c1": "#C8102E",
    "c2": "#001E62",
    "aliases": []
  },
  {
    "id": "university-of-massachusetts-dartmouth",
    "campusId": "b7b28289-86f4-4cdc-90da-39211bcd1cc3",
    "slug": "university-of-massachusetts-dartmouth",
    "name": "University of Massachusetts Dartmouth",
    "isSec": false,
    "courseCode": "ACT 211",
    "c1": "#003DA5",
    "c2": "#FFD100",
    "aliases": []
  },
  {
    "id": "university-of-massachusetts-lowell",
    "campusId": "b1e37925-8407-4abd-9826-11c8191a905a",
    "slug": "university-of-massachusetts-lowell",
    "name": "University of Massachusetts Lowell",
    "isSec": false,
    "courseCode": "ACCT.2010",
    "c1": "#003F7F",
    "c2": "#C8102E",
    "aliases": []
  },
  {
    "id": "university-of-north-carolina-at-charlotte",
    "campusId": "7f9727f8-72ca-414d-9192-c8b52566450f",
    "slug": "university-of-north-carolina-at-charlotte",
    "name": "University of North Carolina at Charlotte",
    "isSec": false,
    "courseCode": "ACCT 2121",
    "c1": "#00703C",
    "c2": "#B3A369",
    "aliases": []
  },
  {
    "id": "university-of-north-carolina-at-greensboro",
    "campusId": "4762f036-6410-449b-8251-87eac11624d9",
    "slug": "university-of-north-carolina-at-greensboro",
    "name": "University of North Carolina at Greensboro",
    "isSec": false,
    "courseCode": "ACC 201",
    "c1": "#003366",
    "c2": "#FFD700",
    "aliases": []
  },
  {
    "id": "university-of-north-texas",
    "campusId": "48d46940-2cd8-4cfd-a9a3-b4c00bd3f9bc",
    "slug": "university-of-north-texas",
    "name": "University of North Texas",
    "isSec": false,
    "courseCode": "ACCT 2010",
    "c1": "#00853E",
    "c2": "#FFFFFF",
    "aliases": []
  },
  {
    "id": "university-of-pennsylvania",
    "campusId": "d1a63c43-c944-4ed3-a377-40e899ce290e",
    "slug": "university-of-pennsylvania",
    "name": "University of Pennsylvania",
    "isSec": false,
    "courseCode": "ACCT 1010",
    "c1": "#011F5B",
    "c2": "#990000",
    "aliases": []
  },
  {
    "id": "university-of-south-florida",
    "campusId": "ae2ba2d1-a457-42b0-840d-83d83a6ad39b",
    "slug": "university-of-south-florida",
    "name": "University of South Florida",
    "isSec": false,
    "courseCode": "ACG 2021",
    "c1": "#00471B",
    "c2": "#CFC493",
    "aliases": []
  },
  {
    "id": "university-of-southern-mississippi",
    "campusId": "2dedca50-1bac-4bb5-9820-9aa41c1617fb",
    "slug": "university-of-southern-mississippi",
    "name": "University of Southern Mississippi",
    "isSec": false,
    "courseCode": "ACC 200",
    "c1": "#FFCC00",
    "c2": "#000000",
    "aliases": []
  },
  {
    "id": "university-of-texas-at-el-paso",
    "campusId": "8258c5bb-9425-4e60-9996-61f5713e9f2b",
    "slug": "university-of-texas-at-el-paso",
    "name": "University of Texas at El Paso",
    "isSec": false,
    "courseCode": "ACCT 2301",
    "c1": "#FF8200",
    "c2": "#041E42",
    "aliases": []
  },
  {
    "id": "university-of-toledo",
    "campusId": "94f67099-2561-4fd8-92af-ed730e8db5ac",
    "slug": "university-of-toledo",
    "name": "University of Toledo",
    "isSec": false,
    "courseCode": "ACCT 2100",
    "c1": "#003E7E",
    "c2": "#FFD700",
    "aliases": []
  },
  {
    "id": "university-of-vermont",
    "campusId": "47d4b417-0631-4081-ae04-95578efb9f62",
    "slug": "university-of-vermont",
    "name": "University of Vermont",
    "isSec": false,
    "courseCode": "BUS 1610",
    "c1": "#005640",
    "c2": "#FFB500",
    "aliases": []
  },
  {
    "id": "university-of-wisconsin-milwaukee",
    "campusId": "398c1e45-85ba-4330-97e8-04d7c88c9cde",
    "slug": "university-of-wisconsinmilwaukee",
    "name": "University of Wisconsin–Milwaukee",
    "isSec": false,
    "courseCode": "BUS ADM 201",
    "c1": "#003366",
    "c2": "#FFD700",
    "aliases": []
  },
  {
    "id": "usc",
    "campusId": "bb80faac-ecaf-418a-abe3-46582214289e",
    "slug": "university-of-southern-california",
    "name": "USC",
    "isSec": false,
    "courseCode": "BUAD 280",
    "c1": "#990000",
    "c2": "#FFCC00",
    "aliases": [
      "Southern Cal",
      "University of Southern California"
    ]
  },
  {
    "id": "utah",
    "campusId": "9fbac3ba-bd9c-4fa9-bbf3-6f2580d78616",
    "slug": "university-of-utah",
    "name": "Utah",
    "isSec": false,
    "courseCode": "ACCTG 2600",
    "c1": "#BE0000",
    "c2": "#FFFFFF",
    "aliases": [
      "University of Utah"
    ]
  },
  {
    "id": "vanderbilt",
    "campusId": "972451c3-bc5e-48d7-9f88-868a55378efa",
    "slug": "vanderbilt-university",
    "name": "Vanderbilt",
    "isSec": true,
    "courseCode": "BUS 1100",
    "c1": "#1B1B1B",
    "c2": "#C9A227",
    "aliases": [
      "Vandy",
      "Commodores",
      "Vanderbilt University"
    ]
  },
  {
    "id": "virginia",
    "campusId": "a71aeefa-4c87-4ac3-ad74-e321c0b91615",
    "slug": "university-of-virginia",
    "name": "Virginia",
    "isSec": false,
    "courseCode": "COMM 2010",
    "c1": "#E57200",
    "c2": "#232D4B",
    "aliases": [
      "UVA",
      "University of Virginia"
    ]
  },
  {
    "id": "virginia-tech",
    "campusId": "0bba23e3-06ae-438a-af5f-1a7f1f178f15",
    "slug": "virginia-tech",
    "name": "Virginia Tech",
    "isSec": false,
    "courseCode": "ACIS 2115",
    "c1": "#861F41",
    "c2": "#E5751F",
    "aliases": []
  },
  {
    "id": "washington",
    "campusId": "79d3cbc6-a7c7-4192-87ee-200fee33ff1c",
    "slug": "university-of-washington",
    "name": "Washington",
    "isSec": false,
    "courseCode": "ACCTG 215",
    "c1": "#4B2E83",
    "c2": "#B7A57A",
    "aliases": [
      "University of Washington"
    ]
  },
  {
    "id": "west-virginia",
    "campusId": "3ad2e7cb-9d47-434f-899f-37cabe4fcba8",
    "slug": "west-virginia-university",
    "name": "West Virginia",
    "isSec": false,
    "courseCode": "ACCT 201",
    "c1": "#002855",
    "c2": "#EAAA00",
    "aliases": [
      "WVU",
      "West Virginia University"
    ]
  },
  {
    "id": "western-kentucky-university",
    "campusId": "9961c567-684f-4fc4-bfea-f701a46b101d",
    "slug": "western-kentucky-university",
    "name": "Western Kentucky University",
    "isSec": false,
    "courseCode": "ACCT 200",
    "c1": "#C8102E",
    "c2": "#FFFFFF",
    "aliases": []
  },
  {
    "id": "winston-salem-state-university",
    "campusId": "21fab442-05d9-42ac-a3bd-5edbd0731cb1",
    "slug": "winston-salem-state-university",
    "name": "Winston-Salem State University",
    "isSec": false,
    "courseCode": "ACC 2316",
    "c1": "#A71930",
    "c2": "#FFD700",
    "aliases": []
  },
  {
    "id": "wisconsin",
    "campusId": "1757afcf-5163-49f0-9e94-131c666882bc",
    "slug": "university-of-wisconsin-madison",
    "name": "Wisconsin",
    "isSec": false,
    "courseCode": "AIS 100",
    "c1": "#C5050C",
    "c2": "#FFFFFF",
    "aliases": [
      "university of wisconsin",
      "University of Wisconsin-Madison"
    ]
  }
];
