// GENERATED by migration/supabase-migrations/gen_schools.ts -- DO NOT EDIT BY HAND.
// The database is the source of truth. Regenerate after any campus seed change.
// 66 campuses (16 SEC). SEC colours come from brand.tsx by design -- see the generator header.
// Aliases source: seed CSV (search_aliases column not yet applied).

export type GeneratedSchool = {
  id: string; campusId: string; slug: string; name: string;
  isSec: boolean; courseCode: string | null;
  c1: string | null; c2: string | null;
  /** Matched in search, NEVER displayed. */
  aliases: string[];
};

export const GENERATED_SCHOOLS: GeneratedSchool[] = [
  {
    "id": "alabama",
    "campusId": "b3af67c6-99a5-4677-83d5-aa7d11a89c17",
    "slug": "university-of-alabama",
    "name": "Alabama",
    "isSec": true,
    "courseCode": "AC 210",
    "c1": "#9E1B32",
    "c2": "#F1F2F3",
    "aliases": [
      "Bama",
      "Roll Tide",
      "Crimson Tide",
      "UA",
      "University of Alabama"
    ]
  },
  {
    "id": "arizona",
    "campusId": "cfd87c76-6af7-4e32-b53a-6c091f19f179",
    "slug": "university-of-arizona",
    "name": "Arizona",
    "isSec": false,
    "courseCode": "ACCT 200",
    "c1": "#AB0520",
    "c2": "#FFFFFF",
    "aliases": [
      "U of A",
      "University of Arizona"
    ]
  },
  {
    "id": "arizona-state",
    "campusId": "45315cbf-6a35-4067-bdcf-0ec418fac4f9",
    "slug": "arizona-state-university",
    "name": "Arizona State",
    "isSec": false,
    "courseCode": "ACC 231",
    "c1": "#8C1D40",
    "c2": "#FFC627",
    "aliases": [
      "ASU",
      "Arizona State University"
    ]
  },
  {
    "id": "arkansas",
    "campusId": "e631c8de-37a3-4aae-a948-a64bd20ea4c5",
    "slug": "university-of-arkansas",
    "name": "Arkansas",
    "isSec": true,
    "courseCode": "ACCT 2013",
    "c1": "#9D2235",
    "c2": "#FFFFFF",
    "aliases": [
      "Razorbacks",
      "Fayetteville",
      "University of Arkansas"
    ]
  },
  {
    "id": "auburn",
    "campusId": "e330e87c-5467-4c05-9d3d-6cd2398de036",
    "slug": "auburn-university",
    "name": "Auburn",
    "isSec": true,
    "courseCode": "ACCT 2110",
    "c1": "#0C2340",
    "c2": "#E87722",
    "aliases": [
      "AU",
      "War Eagle",
      "Tigers",
      "Auburn University"
    ]
  },
  {
    "id": "baylor",
    "campusId": "30dd76fa-6908-407a-b8d4-dcd75a9cfd47",
    "slug": "baylor-university",
    "name": "Baylor",
    "isSec": false,
    "courseCode": "ACC 2303",
    "c1": "#154734",
    "c2": "#FFB81C",
    "aliases": [
      "BU",
      "Baylor University"
    ]
  },
  {
    "id": "cal-poly",
    "campusId": "9fcd2964-e58e-496b-9b14-63b9892506cd",
    "slug": "california-polytechnic-state-university",
    "name": "Cal Poly",
    "isSec": false,
    "courseCode": "BUS 2214",
    "c1": "#154734",
    "c2": "#BD8B13",
    "aliases": [
      "Cal Poly SLO",
      "cal poly san luis obispo",
      "California Polytechnic State University"
    ]
  },
  {
    "id": "cincinnati",
    "campusId": "018d6b9d-f168-4e59-9df1-cdc8563ef577",
    "slug": "university-of-cincinnati",
    "name": "Cincinnati",
    "isSec": false,
    "courseCode": "ACCT 2081",
    "c1": "#E00122",
    "c2": "#000000",
    "aliases": [
      "University of Cincinnati"
    ]
  },
  {
    "id": "clemson",
    "campusId": "b35abe46-764e-4b10-9cb4-d3523dd1a2ee",
    "slug": "clemson-university",
    "name": "Clemson",
    "isSec": false,
    "courseCode": "ACCT 2010",
    "c1": "#F56600",
    "c2": "#522D80",
    "aliases": [
      "Clemson University"
    ]
  },
  {
    "id": "colorado",
    "campusId": "be0aadc8-b5e3-4af6-a75f-7284af0885f3",
    "slug": "university-of-colorado-boulder",
    "name": "Colorado",
    "isSec": false,
    "courseCode": "BCOR 2203",
    "c1": "#CFB87C",
    "c2": "#000000",
    "aliases": [
      "CU Boulder",
      "University of Colorado Boulder"
    ]
  },
  {
    "id": "colorado-state",
    "campusId": "90f8fda4-8901-441f-8c0d-3b1d69c60e63",
    "slug": "colorado-state-university",
    "name": "Colorado State",
    "isSec": false,
    "courseCode": "ACT 210",
    "c1": "#1E4D2B",
    "c2": "#C8C372",
    "aliases": [
      "Colorado State University"
    ]
  },
  {
    "id": "delaware",
    "campusId": "134547c6-fcf2-4a0f-9c0c-6612fb4408dc",
    "slug": "university-of-delaware",
    "name": "Delaware",
    "isSec": false,
    "courseCode": "ACCT 207",
    "c1": "#00539F",
    "c2": "#FFD200",
    "aliases": [
      "University of Delaware"
    ]
  },
  {
    "id": "florida",
    "campusId": "4c5126b1-3fe0-48fe-a1db-1e41d06e4642",
    "slug": "university-of-florida",
    "name": "Florida",
    "isSec": true,
    "courseCode": "ACG 2021",
    "c1": "#0021A5",
    "c2": "#FA4616",
    "aliases": [
      "UF",
      "Gators",
      "University of Florida"
    ]
  },
  {
    "id": "florida-state",
    "campusId": "63662ceb-5770-4dad-8c3f-0021f3924b98",
    "slug": "florida-state-university",
    "name": "Florida State",
    "isSec": false,
    "courseCode": "ACG 2021",
    "c1": "#782F40",
    "c2": "#CEB888",
    "aliases": [
      "FSU",
      "Florida State University"
    ]
  },
  {
    "id": "georgia",
    "campusId": "3f570e37-5394-4058-baab-508948befedb",
    "slug": "university-of-georgia",
    "name": "Georgia",
    "isSec": true,
    "courseCode": "ACCT 2101",
    "c1": "#BA0C2F",
    "c2": "#000000",
    "aliases": [
      "UGA",
      "Bulldogs",
      "University of Georgia"
    ]
  },
  {
    "id": "georgia-tech",
    "campusId": "497c0c67-8e6a-4d5c-a1f2-2e7b78bce77f",
    "slug": "georgia-institute-of-technology",
    "name": "Georgia Tech",
    "isSec": false,
    "courseCode": "ACCT 2101",
    "c1": "#B3A369",
    "c2": "#003057",
    "aliases": [
      "Georgia Institute of Technology"
    ]
  },
  {
    "id": "houston",
    "campusId": "9aad4852-d3b1-4091-8157-acf427d8c88a",
    "slug": "university-of-houston",
    "name": "Houston",
    "isSec": false,
    "courseCode": "ACCT 2301",
    "c1": "#C8102E",
    "c2": "#FFFFFF",
    "aliases": [
      "UH",
      "University of Houston"
    ]
  },
  {
    "id": "illinois",
    "campusId": "f56a0047-8688-48a1-b671-22ebcf12eb28",
    "slug": "university-of-illinois-urbana-champaign",
    "name": "Illinois",
    "isSec": false,
    "courseCode": "ACCY 201",
    "c1": "#FF5F05",
    "c2": "#13294B",
    "aliases": [
      "UIUC",
      "U of I",
      "university of illinois",
      "University of Illinois Urbana-Champaign"
    ]
  },
  {
    "id": "indiana",
    "campusId": "feab5578-893a-48c1-88c4-f4dc7616ac79",
    "slug": "indiana-university-bloomington",
    "name": "Indiana",
    "isSec": false,
    "courseCode": "BUS-A 201",
    "c1": "#990000",
    "c2": "#FFFFFF",
    "aliases": [
      "IU",
      "Indiana University",
      "Indiana University Bloomington"
    ]
  },
  {
    "id": "iowa",
    "campusId": "39e11bf9-6201-41d5-8c50-489b8259032a",
    "slug": "university-of-iowa",
    "name": "Iowa",
    "isSec": false,
    "courseCode": "ACCT:2100",
    "c1": "#FFCD00",
    "c2": "#000000",
    "aliases": [
      "University of Iowa"
    ]
  },
  {
    "id": "iowa-state",
    "campusId": "4782ef17-0a49-4e4b-8856-40e748fe6004",
    "slug": "iowa-state-university",
    "name": "Iowa State",
    "isSec": false,
    "courseCode": "ACCT 2840",
    "c1": "#C8102E",
    "c2": "#F1BE48",
    "aliases": [
      "Iowa State University"
    ]
  },
  {
    "id": "james-madison",
    "campusId": "7d89723d-6d46-46c6-a059-e5875ff118a7",
    "slug": "james-madison-university",
    "name": "James Madison",
    "isSec": false,
    "courseCode": "COB 241",
    "c1": "#450084",
    "c2": "#CBB677",
    "aliases": [
      "JMU",
      "James Madison University"
    ]
  },
  {
    "id": "kansas",
    "campusId": "da89805a-e508-4bda-948c-e546dc78b110",
    "slug": "university-of-kansas",
    "name": "Kansas",
    "isSec": false,
    "courseCode": "ACCT 200",
    "c1": "#0051BA",
    "c2": "#E8000D",
    "aliases": [
      "KU",
      "University of Kansas"
    ]
  },
  {
    "id": "kansas-state",
    "campusId": "4dde3052-393d-4161-98da-23dde61901dd",
    "slug": "kansas-state-university",
    "name": "Kansas State",
    "isSec": false,
    "courseCode": "ACCTG 241",
    "c1": "#512888",
    "c2": "#FFFFFF",
    "aliases": [
      "K-State",
      "Kansas State University"
    ]
  },
  {
    "id": "kentucky",
    "campusId": "ae339230-577e-4569-a7d1-d1e45d1cfe91",
    "slug": "university-of-kentucky",
    "name": "Kentucky",
    "isSec": true,
    "courseCode": "ACC 201",
    "c1": "#0033A0",
    "c2": "#FFFFFF",
    "aliases": [
      "UK",
      "Wildcats",
      "University of Kentucky"
    ]
  },
  {
    "id": "louisville",
    "campusId": "abad6121-4309-4f35-a13c-beba333d56dc",
    "slug": "university-of-louisville",
    "name": "Louisville",
    "isSec": false,
    "courseCode": "ACCT 201",
    "c1": "#AD0000",
    "c2": "#FFFFFF",
    "aliases": [
      "UofL",
      "University of Louisville"
    ]
  },
  {
    "id": "lsu",
    "campusId": "698dd98f-dd92-46c1-8f28-e930568cb15d",
    "slug": "louisiana-state-university",
    "name": "LSU",
    "isSec": true,
    "courseCode": "ACCT 2001",
    "c1": "#461D7C",
    "c2": "#FDD023",
    "aliases": [
      "Louisiana State",
      "Tigers",
      "Baton Rouge",
      "Louisiana State University"
    ]
  },
  {
    "id": "maryland",
    "campusId": "b2c34d1b-f623-4206-99e3-287f52e82fcd",
    "slug": "university-of-maryland",
    "name": "Maryland",
    "isSec": false,
    "courseCode": "BMGT 220",
    "c1": "#E21833",
    "c2": "#FFD200",
    "aliases": [
      "UMD",
      "University of Maryland"
    ]
  },
  {
    "id": "miami",
    "campusId": "c2dbd5ac-8dbd-4488-92da-546c361fd88e",
    "slug": "university-of-miami",
    "name": "Miami",
    "isSec": false,
    "courseCode": "ACC 211",
    "c1": "#F47321",
    "c2": "#005030",
    "aliases": [
      "Miami FL",
      "University of Miami"
    ]
  },
  {
    "id": "miami-oh",
    "campusId": "cc8d19b7-6f88-4162-af9b-629c9c9b91c0",
    "slug": "miami-university-ohio",
    "name": "Miami (OH)",
    "isSec": false,
    "courseCode": "ACC 221",
    "c1": "#C8102E",
    "c2": "#FFFFFF",
    "aliases": [
      "Miami Ohio",
      "Miami University"
    ]
  },
  {
    "id": "michigan-state",
    "campusId": "efe5a52b-cca0-43c5-b655-7e2d758945d8",
    "slug": "michigan-state-university",
    "name": "Michigan State",
    "isSec": false,
    "courseCode": "ACC 201",
    "c1": "#18453B",
    "c2": "#FFFFFF",
    "aliases": [
      "Michigan State University"
    ]
  },
  {
    "id": "minnesota",
    "campusId": "6a03001e-d222-4c4e-9437-1cab7241feaa",
    "slug": "university-of-minnesota",
    "name": "Minnesota",
    "isSec": false,
    "courseCode": "ACCT 2051",
    "c1": "#7A0019",
    "c2": "#FFCC33",
    "aliases": [
      "UMN",
      "University of Minnesota"
    ]
  },
  {
    "id": "mississippi-state",
    "campusId": "95246fc8-1ce6-409e-b454-d03c82766719",
    "slug": "mississippi-state-university",
    "name": "Mississippi State",
    "isSec": true,
    "courseCode": "ACC 2013",
    "c1": "#660000",
    "c2": "#C8C8C8",
    "aliases": [
      "MSU",
      "Miss State",
      "Bulldogs",
      "Starkville",
      "Mississippi State University"
    ]
  },
  {
    "id": "mizzou",
    "campusId": "f16686c2-edc6-43f8-9638-6890f52c829a",
    "slug": "university-of-missouri",
    "name": "Mizzou",
    "isSec": true,
    "courseCode": "ACCTCY 2026",
    "c1": "#F1B82D",
    "c2": "#000000",
    "aliases": [
      "Missouri",
      "MU",
      "Tigers",
      "University of Missouri"
    ]
  },
  {
    "id": "nc-state",
    "campusId": "26fec746-f7a8-48d0-8ac6-3bda7c78d82f",
    "slug": "north-carolina-state-university",
    "name": "NC State",
    "isSec": false,
    "courseCode": "ACC 210",
    "c1": "#CC0000",
    "c2": "#FFFFFF",
    "aliases": [
      "NCSU",
      "North Carolina State University"
    ]
  },
  {
    "id": "nebraska",
    "campusId": "2e0aaa41-7bd2-453d-9a9d-32c53074cc9c",
    "slug": "university-of-nebraska-lincoln",
    "name": "Nebraska",
    "isSec": false,
    "courseCode": "ACCT 201",
    "c1": "#D00000",
    "c2": "#F5F1E7",
    "aliases": [
      "university of nebraska",
      "University of Nebraska-Lincoln"
    ]
  },
  {
    "id": "north-carolina",
    "campusId": "ffef200f-6667-455f-a599-08987f16e7fa",
    "slug": "university-of-north-carolina-at-chapel-hill",
    "name": "North Carolina",
    "isSec": false,
    "courseCode": "BUSI 407",
    "c1": "#4B9CD3",
    "c2": "#13294B",
    "aliases": [
      "UNC",
      "university of north carolina",
      "University of North Carolina at Chapel Hill"
    ]
  },
  {
    "id": "northwestern",
    "campusId": "d0190710-b330-4159-9927-65a9c37409eb",
    "slug": "northwestern-university",
    "name": "Northwestern",
    "isSec": false,
    "courseCode": "ACCOUNT 201",
    "c1": "#4E2A84",
    "c2": "#FFFFFF",
    "aliases": [
      "NU",
      "Northwestern University"
    ]
  },
  {
    "id": "ohio-state",
    "campusId": "1e6b6504-3a9c-44e2-81a9-ee961f66563a",
    "slug": "ohio-state-university",
    "name": "Ohio State",
    "isSec": false,
    "courseCode": "ACCTMIS 2200",
    "c1": "#BA0C2F",
    "c2": "#A7B1B7",
    "aliases": [
      "tOSU",
      "Ohio State University"
    ]
  },
  {
    "id": "oklahoma",
    "campusId": "91e62f9c-43b0-41f3-a84d-002824754da6",
    "slug": "university-of-oklahoma",
    "name": "Oklahoma",
    "isSec": true,
    "courseCode": "ACCT 2113",
    "c1": "#841617",
    "c2": "#FDF9D8",
    "aliases": [
      "OU",
      "Sooners",
      "University of Oklahoma"
    ]
  },
  {
    "id": "oklahoma-state",
    "campusId": "d8ed77fe-4aac-444b-9815-261642ee1052",
    "slug": "oklahoma-state-university",
    "name": "Oklahoma State",
    "isSec": false,
    "courseCode": "ACCT 2103",
    "c1": "#FE5C00",
    "c2": "#000000",
    "aliases": [
      "Okie State",
      "Oklahoma State University"
    ]
  },
  {
    "id": "ole-miss",
    "campusId": "7b92a320-b196-43f2-a241-77a0805816fe",
    "slug": "university-of-mississippi",
    "name": "Ole Miss",
    "isSec": true,
    "courseCode": "ACCY 201",
    "c1": "#14213D",
    "c2": "#CE1126",
    "aliases": [
      "University of Mississippi",
      "UM",
      "OM",
      "Rebels",
      "Oxford"
    ]
  },
  {
    "id": "oregon",
    "campusId": "62187d7a-6154-4167-9c3d-04fecdc57354",
    "slug": "university-of-oregon",
    "name": "Oregon",
    "isSec": false,
    "courseCode": "BA 211Z",
    "c1": "#007030",
    "c2": "#FEE11A",
    "aliases": [
      "UO",
      "University of Oregon"
    ]
  },
  {
    "id": "oregon-state",
    "campusId": "0f207a42-7b5b-46f3-8d9b-7b753a0451fe",
    "slug": "oregon-state-university",
    "name": "Oregon State",
    "isSec": false,
    "courseCode": "BA 211Z",
    "c1": "#D73F09",
    "c2": "#000000",
    "aliases": [
      "Oregon State University"
    ]
  },
  {
    "id": "penn-state",
    "campusId": "afb9cd13-7cd5-48fb-8416-e358d02bc2ae",
    "slug": "pennsylvania-state-university",
    "name": "Penn State",
    "isSec": false,
    "courseCode": "ACCTG 211",
    "c1": "#001E44",
    "c2": "#FFFFFF",
    "aliases": [
      "PSU",
      "Penn St",
      "Pennsylvania State University"
    ]
  },
  {
    "id": "pittsburgh",
    "campusId": "2668a8b5-52c6-4a41-b2df-a83f29330d3b",
    "slug": "university-of-pittsburgh",
    "name": "Pittsburgh",
    "isSec": false,
    "courseCode": "BUSACC 0030",
    "c1": "#003594",
    "c2": "#FFB81C",
    "aliases": [
      "Pitt",
      "University of Pittsburgh"
    ]
  },
  {
    "id": "purdue",
    "campusId": "0da1dbed-01e6-4e98-a023-38bf102e8853",
    "slug": "purdue-university",
    "name": "Purdue",
    "isSec": false,
    "courseCode": "ACCT 20000",
    "c1": "#CFB991",
    "c2": "#000000",
    "aliases": [
      "Purdue University"
    ]
  },
  {
    "id": "rutgers",
    "campusId": "f2bb9523-3512-405c-bcc1-ee2ae517f08c",
    "slug": "rutgers-university",
    "name": "Rutgers",
    "isSec": false,
    "courseCode": "33:010:272",
    "c1": "#CC0033",
    "c2": "#FFFFFF",
    "aliases": [
      "Rutgers University"
    ]
  },
  {
    "id": "san-diego-state",
    "campusId": "7325256b-319c-4948-b5a0-5f2016f38dca",
    "slug": "san-diego-state-university",
    "name": "San Diego State",
    "isSec": false,
    "courseCode": "ACCTG 201",
    "c1": "#A6192E",
    "c2": "#FFFFFF",
    "aliases": [
      "SDSU",
      "San Diego State University"
    ]
  },
  {
    "id": "smu",
    "campusId": "fb5f2ade-df5d-4e16-9557-33d1232ffaba",
    "slug": "southern-methodist-university",
    "name": "SMU",
    "isSec": false,
    "courseCode": "ACCT 2301",
    "c1": "#CC0035",
    "c2": "#FFFFFF",
    "aliases": [
      "Southern Methodist University"
    ]
  },
  {
    "id": "south-carolina",
    "campusId": "5f5bd18d-b92f-4d56-aced-23bce4c983d5",
    "slug": "university-of-south-carolina",
    "name": "South Carolina",
    "isSec": true,
    "courseCode": "ACCT 225",
    "c1": "#73000A",
    "c2": "#000000",
    "aliases": [
      "USC",
      "South Carolina Gamecocks",
      "Gamecocks",
      "University of South Carolina"
    ]
  },
  {
    "id": "syracuse",
    "campusId": "4528bb03-6544-43ad-bb02-17a0f21130f9",
    "slug": "syracuse-university",
    "name": "Syracuse",
    "isSec": false,
    "courseCode": "ACC 151",
    "c1": "#F76900",
    "c2": "#000E54",
    "aliases": [
      "Syracuse University"
    ]
  },
  {
    "id": "tcu",
    "campusId": "8a987f3f-ef08-4f2f-be5c-d18e032b6796",
    "slug": "texas-christian-university",
    "name": "TCU",
    "isSec": false,
    "courseCode": "ACCT 20353",
    "c1": "#4D1979",
    "c2": "#FFFFFF",
    "aliases": [
      "Texas Christian University"
    ]
  },
  {
    "id": "tennessee",
    "campusId": "9c4775be-7d82-4a3e-840c-349c5e15d8e8",
    "slug": "university-of-tennessee-knoxville",
    "name": "Tennessee",
    "isSec": true,
    "courseCode": "ACCT 200",
    "c1": "#FF8200",
    "c2": "#FFFFFF",
    "aliases": [
      "UT Knoxville",
      "Vols",
      "Volunteers",
      "University of Tennessee, Knoxville"
    ]
  },
  {
    "id": "texas",
    "campusId": "faad6039-be72-4f5c-8ad5-ca7b95e2889f",
    "slug": "university-of-texas-at-austin",
    "name": "Texas",
    "isSec": true,
    "courseCode": "ACC 311",
    "c1": "#BF5700",
    "c2": "#FFFFFF",
    "aliases": [
      "UT Austin",
      "UT",
      "Longhorns",
      "University of Texas at Austin"
    ]
  },
  {
    "id": "texas-aandm",
    "campusId": "92e4a5d9-eeb3-4065-ac8a-5a4390fbc584",
    "slug": "texas-aandm-university",
    "name": "Texas A&M",
    "isSec": true,
    "courseCode": "ACCT 229",
    "c1": "#500000",
    "c2": "#FFFFFF",
    "aliases": [
      "A&M",
      "TAMU",
      "Aggies",
      "College Station",
      "Texas A&M University"
    ]
  },
  {
    "id": "texas-tech",
    "campusId": "e7fff2aa-78fe-459f-9211-2584fae1f5ee",
    "slug": "texas-tech-university",
    "name": "Texas Tech",
    "isSec": false,
    "courseCode": "ACCT 2300",
    "c1": "#E90802",
    "c2": "#000000",
    "aliases": [
      "TTU",
      "Texas Tech University"
    ]
  },
  {
    "id": "ucf",
    "campusId": "9fc579bc-bed2-4e8b-9c89-0958f7edda42",
    "slug": "university-of-central-florida",
    "name": "UCF",
    "isSec": false,
    "courseCode": "ACG 2021",
    "c1": "#000000",
    "c2": "#FFC904",
    "aliases": [
      "University of Central Florida"
    ]
  },
  {
    "id": "usc",
    "campusId": "bb80faac-ecaf-418a-abe3-46582214289e",
    "slug": "university-of-southern-california",
    "name": "USC",
    "isSec": false,
    "courseCode": "BUAD 280",
    "c1": "#990000",
    "c2": "#FFCC00",
    "aliases": [
      "Southern Cal",
      "University of Southern California"
    ]
  },
  {
    "id": "utah",
    "campusId": "9fbac3ba-bd9c-4fa9-bbf3-6f2580d78616",
    "slug": "university-of-utah",
    "name": "Utah",
    "isSec": false,
    "courseCode": "ACCTG 2600",
    "c1": "#BE0000",
    "c2": "#FFFFFF",
    "aliases": [
      "University of Utah"
    ]
  },
  {
    "id": "vanderbilt",
    "campusId": "972451c3-bc5e-48d7-9f88-868a55378efa",
    "slug": "vanderbilt-university",
    "name": "Vanderbilt",
    "isSec": true,
    "courseCode": "BUS 1100",
    "c1": "#1B1B1B",
    "c2": "#C9A227",
    "aliases": [
      "Vandy",
      "Commodores",
      "Vanderbilt University"
    ]
  },
  {
    "id": "virginia",
    "campusId": "a71aeefa-4c87-4ac3-ad74-e321c0b91615",
    "slug": "university-of-virginia",
    "name": "Virginia",
    "isSec": false,
    "courseCode": "COMM 2010",
    "c1": "#E57200",
    "c2": "#232D4B",
    "aliases": [
      "UVA",
      "University of Virginia"
    ]
  },
  {
    "id": "virginia-tech",
    "campusId": "0bba23e3-06ae-438a-af5f-1a7f1f178f15",
    "slug": "virginia-tech",
    "name": "Virginia Tech",
    "isSec": false,
    "courseCode": "ACIS 2115",
    "c1": "#861F41",
    "c2": "#E5751F",
    "aliases": []
  },
  {
    "id": "washington",
    "campusId": "79d3cbc6-a7c7-4192-87ee-200fee33ff1c",
    "slug": "university-of-washington",
    "name": "Washington",
    "isSec": false,
    "courseCode": "ACCTG 215",
    "c1": "#4B2E83",
    "c2": "#B7A57A",
    "aliases": [
      "University of Washington"
    ]
  },
  {
    "id": "west-virginia",
    "campusId": "3ad2e7cb-9d47-434f-899f-37cabe4fcba8",
    "slug": "west-virginia-university",
    "name": "West Virginia",
    "isSec": false,
    "courseCode": "ACCT 201",
    "c1": "#002855",
    "c2": "#EAAA00",
    "aliases": [
      "WVU",
      "West Virginia University"
    ]
  },
  {
    "id": "wisconsin",
    "campusId": "1757afcf-5163-49f0-9e94-131c666882bc",
    "slug": "university-of-wisconsin-madison",
    "name": "Wisconsin",
    "isSec": false,
    "courseCode": "AIS 100",
    "c1": "#C5050C",
    "c2": "#FFFFFF",
    "aliases": [
      "university of wisconsin",
      "University of Wisconsin-Madison"
    ]
  }
];
