// GENERATED by migration/supabase-migrations/gen_schools.ts -- DO NOT EDIT BY HAND.
// The database is the source of truth. Regenerate after any campus seed change.
// 197 campuses. By conference: SEC 16, Big Ten 14, Big 12 14, ACC 12, Other 141. SEC colours come from brand.tsx by design -- see the generator header.
// Aliases source: seed CSV (search_aliases column not yet applied).

export type GeneratedSchool = {
  id: string; campusId: string; slug: string; name: string;
  isSec: boolean;
  /** "SEC" | "Big Ten" | "Big 12" | "ACC" | "Other" — the picker's grouping. */
  conference: string;
  courseCode: string | null;
  c1: string | null; c2: string | null;
  /** Matched in search, NEVER displayed. */
  aliases: string[];
};

export const GENERATED_SCHOOLS: GeneratedSchool[] = [
  {
    "id": "alabama",
    "campusId": "b3af67c6-99a5-4677-83d5-aa7d11a89c17",
    "slug": "university-of-alabama",
    "name": "Alabama",
    "isSec": true,
    "conference": "SEC",
    "courseCode": "AC 210",
    "c1": "#9E1B32",
    "c2": "#F1F2F3",
    "aliases": [
      "Bama",
      "Roll Tide",
      "Crimson Tide",
      "UA",
      "University of Alabama"
    ]
  },
  {
    "id": "alabama-state-university",
    "campusId": "ea7f5b3c-4903-4c05-aff5-328a1c1de292",
    "slug": "alabama-state-university",
    "name": "Alabama State University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACT 211",
    "c1": "#000000",
    "c2": "#FFD700",
    "aliases": []
  },
  {
    "id": "albany-state-university",
    "campusId": "03ce5ea1-240d-4a8a-a7a6-c35e76aeb549",
    "slug": "albany-state-university",
    "name": "Albany State University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 2101",
    "c1": "#FFD700",
    "c2": "#000080",
    "aliases": []
  },
  {
    "id": "american-university",
    "campusId": "bfdddcff-55b3-4446-82c3-fa31be4c3224",
    "slug": "american-university",
    "name": "American University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 240",
    "c1": "#C8102E",
    "c2": "#003A70",
    "aliases": []
  },
  {
    "id": "angelo-state-university",
    "campusId": "ee901356-b1fa-4471-aae0-156e1a0ba81f",
    "slug": "angelo-state-university",
    "name": "Angelo State University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 2301",
    "c1": "#003366",
    "c2": "#FFD700",
    "aliases": []
  },
  {
    "id": "arizona",
    "campusId": "cfd87c76-6af7-4e32-b53a-6c091f19f179",
    "slug": "university-of-arizona",
    "name": "Arizona",
    "isSec": false,
    "conference": "Big 12",
    "courseCode": "ACCT 200",
    "c1": "#AB0520",
    "c2": "#FFFFFF",
    "aliases": [
      "U of A",
      "University of Arizona"
    ]
  },
  {
    "id": "arizona-state",
    "campusId": "45315cbf-6a35-4067-bdcf-0ec418fac4f9",
    "slug": "arizona-state-university",
    "name": "Arizona State",
    "isSec": false,
    "conference": "Big 12",
    "courseCode": "ACC 231",
    "c1": "#8C1D40",
    "c2": "#FFC627",
    "aliases": [
      "ASU",
      "Arizona State University"
    ]
  },
  {
    "id": "arkansas",
    "campusId": "e631c8de-37a3-4aae-a948-a64bd20ea4c5",
    "slug": "university-of-arkansas",
    "name": "Arkansas",
    "isSec": true,
    "conference": "SEC",
    "courseCode": "ACCT 2013",
    "c1": "#9D2235",
    "c2": "#FFFFFF",
    "aliases": [
      "Razorbacks",
      "Fayetteville",
      "University of Arkansas"
    ]
  },
  {
    "id": "arkansas-state-university",
    "campusId": "78604ee3-811c-4b88-8bdd-3f198fa7df10",
    "slug": "arkansas-state-university",
    "name": "Arkansas State University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 2023",
    "c1": "#CC092F",
    "c2": "#000000",
    "aliases": []
  },
  {
    "id": "auburn",
    "campusId": "e330e87c-5467-4c05-9d3d-6cd2398de036",
    "slug": "auburn-university",
    "name": "Auburn",
    "isSec": true,
    "conference": "SEC",
    "courseCode": "ACCT 2110",
    "c1": "#0C2340",
    "c2": "#E87722",
    "aliases": [
      "AU",
      "War Eagle",
      "Tigers",
      "Auburn University"
    ]
  },
  {
    "id": "augsburg-university",
    "campusId": "5190a915-add2-421e-aaa6-cc49c69b9e63",
    "slug": "augsburg-university",
    "name": "Augsburg University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACC 221",
    "c1": "#862633",
    "c2": "#CCCCCC",
    "aliases": []
  },
  {
    "id": "azusa-pacific-university",
    "campusId": "fb93f711-f809-465c-a02d-6b9d5969e806",
    "slug": "azusa-pacific-university",
    "name": "Azusa Pacific University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 210",
    "c1": "#8B2538",
    "c2": "#FFD700",
    "aliases": []
  },
  {
    "id": "ball-state-university",
    "campusId": "2567ae60-6898-4652-a62a-13a73c18e2c5",
    "slug": "ball-state-university",
    "name": "Ball State University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACC 201",
    "c1": "#BA0C2F",
    "c2": "#FFFFFF",
    "aliases": []
  },
  {
    "id": "bay-path-university",
    "campusId": "e623f3ab-9b03-424f-9bdc-d3422a1ef17a",
    "slug": "bay-path-university",
    "name": "Bay Path University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACC 100",
    "c1": "#8B1538",
    "c2": "#FFD700",
    "aliases": []
  },
  {
    "id": "baylor",
    "campusId": "30dd76fa-6908-407a-b8d4-dcd75a9cfd47",
    "slug": "baylor-university",
    "name": "Baylor",
    "isSec": false,
    "conference": "Big 12",
    "courseCode": "ACC 2303",
    "c1": "#154734",
    "c2": "#FFB81C",
    "aliases": [
      "BU",
      "Baylor University"
    ]
  },
  {
    "id": "binghamton-university",
    "campusId": "d7abb1b4-197e-4556-88fd-b2fc800951a9",
    "slug": "binghamton-university",
    "name": "Binghamton University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 211",
    "c1": "#00703C",
    "c2": "#FFFFFF",
    "aliases": []
  },
  {
    "id": "brandeis-university",
    "campusId": "f8cd97cd-6ba9-4282-abf1-2c2828fb627c",
    "slug": "brandeis-university",
    "name": "Brandeis University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "BUS 6a",
    "c1": "#003478",
    "c2": "#FFFFFF",
    "aliases": []
  },
  {
    "id": "bryant-and-stratton-college",
    "campusId": "5df1c263-9cb3-4545-b4a6-eaca56a8fb8f",
    "slug": "bryant-and-stratton-college",
    "name": "Bryant & Stratton College",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 100",
    "c1": "#1E3A8A",
    "c2": "#F59E0B",
    "aliases": []
  },
  {
    "id": "cal-poly",
    "campusId": "9fcd2964-e58e-496b-9b14-63b9892506cd",
    "slug": "california-polytechnic-state-university",
    "name": "Cal Poly",
    "isSec": false,
    "conference": "Other",
    "courseCode": "BUS 2214",
    "c1": "#154734",
    "c2": "#BD8B13",
    "aliases": [
      "Cal Poly SLO",
      "cal poly san luis obispo",
      "California Polytechnic State University"
    ]
  },
  {
    "id": "calumet-college-of-saint-joseph",
    "campusId": "7dd29d13-ccd1-4e50-8595-2dd88a64b252",
    "slug": "calumet-college-of-saint-joseph",
    "name": "Calumet College of Saint Joseph",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 210",
    "c1": "#8B0000",
    "c2": "#C0C0C0",
    "aliases": []
  },
  {
    "id": "campbell-university",
    "campusId": "c3dd686d-977b-4495-9565-1b38202941c7",
    "slug": "campbell-university",
    "name": "Campbell University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 215",
    "c1": "#FF6600",
    "c2": "#000000",
    "aliases": []
  },
  {
    "id": "campbellsville-university",
    "campusId": "09468af0-2e5e-4758-b9db-9b8d8473720e",
    "slug": "campbellsville-university",
    "name": "Campbellsville University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACC 221",
    "c1": "#FF6600",
    "c2": "#000000",
    "aliases": []
  },
  {
    "id": "canisius-college",
    "campusId": "1a3169d1-2611-44de-8b14-2dee844afddd",
    "slug": "canisius-college",
    "name": "Canisius College",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACC 201",
    "c1": "#003366",
    "c2": "#FFD700",
    "aliases": []
  },
  {
    "id": "catawba-college",
    "campusId": "5adb35e0-976c-4f17-a3e2-2699525b98f3",
    "slug": "catawba-college",
    "name": "Catawba College",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACC 1901",
    "c1": "#003366",
    "c2": "#FFFFFF",
    "aliases": []
  },
  {
    "id": "cedar-crest-college",
    "campusId": "5aa53e5d-c9eb-48f0-9ce6-b89453127a96",
    "slug": "cedar-crest-college",
    "name": "Cedar Crest College",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACC 101",
    "c1": "#8B0000",
    "c2": "#FFD700",
    "aliases": []
  },
  {
    "id": "central-college",
    "campusId": "c3766dfa-b24b-4817-8c18-4a217e3f608f",
    "slug": "central-college",
    "name": "Central College",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 241",
    "c1": "#8B0000",
    "c2": "#FFD700",
    "aliases": []
  },
  {
    "id": "cerritos-college",
    "campusId": "c4181814-91e1-44b3-9f4a-dd2c2e895706",
    "slug": "cerritos-college",
    "name": "Cerritos College",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 101",
    "c1": "#003366",
    "c2": "#FFD700",
    "aliases": []
  },
  {
    "id": "chabot-college",
    "campusId": "ccee7297-0b61-4436-bd00-f71019547067",
    "slug": "chabot-college",
    "name": "Chabot College",
    "isSec": false,
    "conference": "Other",
    "courseCode": "BUS 1A",
    "c1": "#003366",
    "c2": "#FFD700",
    "aliases": []
  },
  {
    "id": "chaffey-college",
    "campusId": "17b27729-2428-4f20-8125-a1c17c6bc9da",
    "slug": "chaffey-college",
    "name": "Chaffey College",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCTG 1A",
    "c1": "#003366",
    "c2": "#FFD700",
    "aliases": []
  },
  {
    "id": "champlain-college",
    "campusId": "28b0fb4c-fe23-4b22-8d4f-9fcf9f5f3d5b",
    "slug": "champlain-college",
    "name": "Champlain College",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACC 110",
    "c1": "#003366",
    "c2": "#66CC99",
    "aliases": []
  },
  {
    "id": "city-college-of-san-francisco",
    "campusId": "aa693672-2bb7-4b81-847c-7b7be9f3ab10",
    "slug": "city-college-of-san-francisco",
    "name": "City College of San Francisco",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 1",
    "c1": "#003366",
    "c2": "#FFD700",
    "aliases": []
  },
  {
    "id": "claflin-university",
    "campusId": "200ff92f-14f1-4ea5-a816-ff3a713d62a1",
    "slug": "claflin-university",
    "name": "Claflin University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 210",
    "c1": "#8B0000",
    "c2": "#FFD700",
    "aliases": []
  },
  {
    "id": "clemson",
    "campusId": "b35abe46-764e-4b10-9cb4-d3523dd1a2ee",
    "slug": "clemson-university",
    "name": "Clemson",
    "isSec": false,
    "conference": "ACC",
    "courseCode": "ACCT 2010",
    "c1": "#F56600",
    "c2": "#522D80",
    "aliases": [
      "Clemson University"
    ]
  },
  {
    "id": "cleveland-state-university",
    "campusId": "c0aa702e-76fa-422a-86ba-13ab222dd072",
    "slug": "cleveland-state-university",
    "name": "Cleveland State University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACT 221",
    "c1": "#0F2044",
    "c2": "#FFFFFF",
    "aliases": []
  },
  {
    "id": "colorado",
    "campusId": "be0aadc8-b5e3-4af6-a75f-7284af0885f3",
    "slug": "university-of-colorado-boulder",
    "name": "Colorado",
    "isSec": false,
    "conference": "Big 12",
    "courseCode": "BCOR 2203",
    "c1": "#CFB87C",
    "c2": "#000000",
    "aliases": [
      "CU Boulder",
      "University of Colorado Boulder"
    ]
  },
  {
    "id": "colorado-state",
    "campusId": "90f8fda4-8901-441f-8c0d-3b1d69c60e63",
    "slug": "colorado-state-university",
    "name": "Colorado State",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACT 210",
    "c1": "#1E4D2B",
    "c2": "#C8C372",
    "aliases": [
      "Colorado State University"
    ]
  },
  {
    "id": "columbia-international-university",
    "campusId": "c31d46b4-aef4-4e03-862c-a9efc6924752",
    "slug": "columbia-international-university",
    "name": "Columbia International University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACC 2101",
    "c1": "#003366",
    "c2": "#FFD700",
    "aliases": []
  },
  {
    "id": "community-college-of-baltimore-county",
    "campusId": "aca746c3-6b65-4ce0-aac9-c0278c486da5",
    "slug": "community-college-of-baltimore-county",
    "name": "Community College of Baltimore County",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 101",
    "c1": "#003366",
    "c2": "#FF6600",
    "aliases": []
  },
  {
    "id": "concord-university",
    "campusId": "325865d7-5847-472d-abca-25fb1f4c81de",
    "slug": "concord-university",
    "name": "Concord University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 205",
    "c1": "#8B1538",
    "c2": "#FFD700",
    "aliases": []
  },
  {
    "id": "dallas-baptist-university",
    "campusId": "4f8c2b5d-5fb6-4140-8668-a3fa72fa4102",
    "slug": "dallas-baptist-university",
    "name": "Dallas Baptist University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 2301",
    "c1": "#003366",
    "c2": "#CC0000",
    "aliases": []
  },
  {
    "id": "de-anza-college",
    "campusId": "163adfda-42e6-4a63-9af0-2c63d4e871e5",
    "slug": "de-anza-college",
    "name": "De Anza College",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 1A",
    "c1": "#0066CC",
    "c2": "#003366",
    "aliases": []
  },
  {
    "id": "delaware",
    "campusId": "134547c6-fcf2-4a0f-9c0c-6612fb4408dc",
    "slug": "university-of-delaware",
    "name": "Delaware",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 207",
    "c1": "#00539F",
    "c2": "#FFD200",
    "aliases": [
      "University of Delaware"
    ]
  },
  {
    "id": "delaware-valley-university",
    "campusId": "f7429d11-c236-4c42-a5bb-72a9d1b654ed",
    "slug": "delaware-valley-university",
    "name": "Delaware Valley University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACC 1101",
    "c1": "#003366",
    "c2": "#FFD700",
    "aliases": []
  },
  {
    "id": "doane-university",
    "campusId": "33422353-e982-42b4-b0e4-26fbb9cf1d1e",
    "slug": "doane-university",
    "name": "Doane University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACC 103",
    "c1": "#C8102E",
    "c2": "#000000",
    "aliases": []
  },
  {
    "id": "drexel-university",
    "campusId": "71d2787f-9b4b-41c9-bd67-270890fb5db8",
    "slug": "drexel-university",
    "name": "Drexel University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 115",
    "c1": "#07294D",
    "c2": "#FFC600",
    "aliases": []
  },
  {
    "id": "east-texas-aandm-university",
    "campusId": "54036bcf-4050-45da-94e7-cb001da199a0",
    "slug": "east-texas-aandm-university",
    "name": "East Texas A&M University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 2301",
    "c1": "#003366",
    "c2": "#FFD700",
    "aliases": []
  },
  {
    "id": "eastern-michigan-university",
    "campusId": "f3b7ae70-62da-4b7c-886b-db819d133472",
    "slug": "eastern-michigan-university",
    "name": "Eastern Michigan University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACC 240",
    "c1": "#006633",
    "c2": "#FFFFFF",
    "aliases": []
  },
  {
    "id": "erskine-college",
    "campusId": "03bd72c1-3c7e-4b34-8f74-9b1da782f752",
    "slug": "erskine-college",
    "name": "Erskine College",
    "isSec": false,
    "conference": "Other",
    "courseCode": "BA 221",
    "c1": "#003366",
    "c2": "#FFD700",
    "aliases": []
  },
  {
    "id": "florida",
    "campusId": "4c5126b1-3fe0-48fe-a1db-1e41d06e4642",
    "slug": "university-of-florida",
    "name": "Florida",
    "isSec": true,
    "conference": "SEC",
    "courseCode": "ACG 2021",
    "c1": "#0021A5",
    "c2": "#FA4616",
    "aliases": [
      "UF",
      "Gators",
      "University of Florida"
    ]
  },
  {
    "id": "florida-atlantic-university",
    "campusId": "42c3eddd-939e-48ae-ba21-2d04bdadb84e",
    "slug": "florida-atlantic-university",
    "name": "Florida Atlantic University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACG 2021",
    "c1": "#003366",
    "c2": "#C8102E",
    "aliases": []
  },
  {
    "id": "florida-gulf-coast-university",
    "campusId": "f88bae89-d063-4a50-9351-f473303841c8",
    "slug": "florida-gulf-coast-university",
    "name": "Florida Gulf Coast University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACG 2021",
    "c1": "#003366",
    "c2": "#00A651",
    "aliases": []
  },
  {
    "id": "florida-international-university",
    "campusId": "a20b5f96-7a39-4a87-8fc8-30a577bac114",
    "slug": "florida-international-university",
    "name": "Florida International University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACG 2021",
    "c1": "#081E3F",
    "c2": "#B6862C",
    "aliases": []
  },
  {
    "id": "florida-state",
    "campusId": "63662ceb-5770-4dad-8c3f-0021f3924b98",
    "slug": "florida-state-university",
    "name": "Florida State",
    "isSec": false,
    "conference": "ACC",
    "courseCode": "ACG 2021",
    "c1": "#782F40",
    "c2": "#CEB888",
    "aliases": [
      "FSU",
      "Florida State University"
    ]
  },
  {
    "id": "fullerton-college",
    "campusId": "99cbe050-fe80-4f07-bc9f-4bc76099e9a3",
    "slug": "fullerton-college",
    "name": "Fullerton College",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 101AF",
    "c1": "#003876",
    "c2": "#FFD700",
    "aliases": []
  },
  {
    "id": "furman-university",
    "campusId": "c16a3be6-feed-4831-b038-35b4e1aacc63",
    "slug": "furman-university",
    "name": "Furman University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACC 111",
    "c1": "#663399",
    "c2": "#FFFFFF",
    "aliases": []
  },
  {
    "id": "george-mason-university",
    "campusId": "60e3b6bc-611e-4254-8b7c-7e8b45412159",
    "slug": "george-mason-university",
    "name": "George Mason University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 203",
    "c1": "#006633",
    "c2": "#FFCC33",
    "aliases": []
  },
  {
    "id": "george-washington-university",
    "campusId": "99b33713-d32a-4089-b16b-87a59166d2ed",
    "slug": "george-washington-university",
    "name": "George Washington University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCY 2001",
    "c1": "#033C5A",
    "c2": "#AA9868",
    "aliases": []
  },
  {
    "id": "georgia",
    "campusId": "3f570e37-5394-4058-baab-508948befedb",
    "slug": "university-of-georgia",
    "name": "Georgia",
    "isSec": true,
    "conference": "SEC",
    "courseCode": "ACCT 2101",
    "c1": "#BA0C2F",
    "c2": "#000000",
    "aliases": [
      "UGA",
      "Bulldogs",
      "University of Georgia"
    ]
  },
  {
    "id": "georgia-state-university",
    "campusId": "fea35ec6-5a55-4e27-9fe0-021c0a583253",
    "slug": "georgia-state-university",
    "name": "Georgia State University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 2101",
    "c1": "#0039A6",
    "c2": "#8B0000",
    "aliases": []
  },
  {
    "id": "georgia-tech",
    "campusId": "497c0c67-8e6a-4d5c-a1f2-2e7b78bce77f",
    "slug": "georgia-institute-of-technology",
    "name": "Georgia Tech",
    "isSec": false,
    "conference": "ACC",
    "courseCode": "ACCT 2101",
    "c1": "#B3A369",
    "c2": "#003057",
    "aliases": [
      "Georgia Institute of Technology"
    ]
  },
  {
    "id": "grambling-state-university",
    "campusId": "d1b0ef09-0c29-4fa5-b28a-28055f68a6f4",
    "slug": "grambling-state-university",
    "name": "Grambling State University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 201",
    "c1": "#FFD700",
    "c2": "#000000",
    "aliases": []
  },
  {
    "id": "hawaii-pacific-university",
    "campusId": "dc64b64b-d840-4bd0-98b2-d8b5e52a8b6d",
    "slug": "hawaii-pacific-university",
    "name": "Hawaii Pacific University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 2000",
    "c1": "#003366",
    "c2": "#FF6600",
    "aliases": []
  },
  {
    "id": "houston",
    "campusId": "9aad4852-d3b1-4091-8157-acf427d8c88a",
    "slug": "university-of-houston",
    "name": "Houston",
    "isSec": false,
    "conference": "Big 12",
    "courseCode": "ACCT 2301",
    "c1": "#C8102E",
    "c2": "#FFFFFF",
    "aliases": [
      "UH",
      "University of Houston"
    ]
  },
  {
    "id": "howard-university",
    "campusId": "0b7532ee-e905-4012-b835-ab99faf022d6",
    "slug": "howard-university",
    "name": "Howard University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 201",
    "c1": "#003A63",
    "c2": "#CC092F",
    "aliases": []
  },
  {
    "id": "illinois",
    "campusId": "f56a0047-8688-48a1-b671-22ebcf12eb28",
    "slug": "university-of-illinois-urbana-champaign",
    "name": "Illinois",
    "isSec": false,
    "conference": "Big Ten",
    "courseCode": "ACCY 201",
    "c1": "#FF5F05",
    "c2": "#13294B",
    "aliases": [
      "UIUC",
      "U of I",
      "university of illinois",
      "University of Illinois Urbana-Champaign"
    ]
  },
  {
    "id": "indiana",
    "campusId": "feab5578-893a-48c1-88c4-f4dc7616ac79",
    "slug": "indiana-university-bloomington",
    "name": "Indiana",
    "isSec": false,
    "conference": "Other",
    "courseCode": "BUS-A 201",
    "c1": "#990000",
    "c2": "#FFFFFF",
    "aliases": [
      "IU",
      "Indiana University",
      "Indiana University Bloomington"
    ]
  },
  {
    "id": "indiana-university-indianapolis",
    "campusId": "6f131e58-09ef-4618-a2c5-2aac3146324f",
    "slug": "indiana-university-indianapolis",
    "name": "Indiana University Indianapolis",
    "isSec": false,
    "conference": "Other",
    "courseCode": "BUS-A 201",
    "c1": "#990000",
    "c2": "#FFD100",
    "aliases": []
  },
  {
    "id": "indiana-university-northwest",
    "campusId": "892382c3-5770-41cb-b94f-8407abd92be8",
    "slug": "indiana-university-northwest",
    "name": "Indiana University Northwest",
    "isSec": false,
    "conference": "Other",
    "courseCode": "BUS-A 201",
    "c1": "#990000",
    "c2": "#FFFFFF",
    "aliases": []
  },
  {
    "id": "indiana-university-southeast",
    "campusId": "2f64caa2-688c-4c86-b6af-387d722c8315",
    "slug": "indiana-university-southeast",
    "name": "Indiana University Southeast",
    "isSec": false,
    "conference": "Other",
    "courseCode": "BUS-A 201",
    "c1": "#CC0033",
    "c2": "#000000",
    "aliases": []
  },
  {
    "id": "iowa",
    "campusId": "39e11bf9-6201-41d5-8c50-489b8259032a",
    "slug": "university-of-iowa",
    "name": "Iowa",
    "isSec": false,
    "conference": "Big Ten",
    "courseCode": "ACCT:2100",
    "c1": "#FFCD00",
    "c2": "#000000",
    "aliases": [
      "University of Iowa"
    ]
  },
  {
    "id": "iowa-state",
    "campusId": "4782ef17-0a49-4e4b-8856-40e748fe6004",
    "slug": "iowa-state-university",
    "name": "Iowa State",
    "isSec": false,
    "conference": "Big 12",
    "courseCode": "ACCT 2840",
    "c1": "#C8102E",
    "c2": "#F1BE48",
    "aliases": [
      "Iowa State University"
    ]
  },
  {
    "id": "jacksonville-state-university",
    "campusId": "01668df5-a744-4307-b733-2db6e8cde542",
    "slug": "jacksonville-state-university",
    "name": "Jacksonville State University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACC 200",
    "c1": "#CC092F",
    "c2": "#FFFFFF",
    "aliases": []
  },
  {
    "id": "jacksonville-university",
    "campusId": "46195ee9-9599-4f71-b624-079d1c2aedad",
    "slug": "jacksonville-university",
    "name": "Jacksonville University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 201",
    "c1": "#00205B",
    "c2": "#C8102E",
    "aliases": []
  },
  {
    "id": "james-madison",
    "campusId": "7d89723d-6d46-46c6-a059-e5875ff118a7",
    "slug": "james-madison-university",
    "name": "James Madison",
    "isSec": false,
    "conference": "Other",
    "courseCode": "COB 241",
    "c1": "#450084",
    "c2": "#CBB677",
    "aliases": [
      "JMU",
      "James Madison University"
    ]
  },
  {
    "id": "kansas",
    "campusId": "da89805a-e508-4bda-948c-e546dc78b110",
    "slug": "university-of-kansas",
    "name": "Kansas",
    "isSec": false,
    "conference": "Big 12",
    "courseCode": "ACCT 200",
    "c1": "#0051BA",
    "c2": "#E8000D",
    "aliases": [
      "KU",
      "University of Kansas"
    ]
  },
  {
    "id": "kansas-state",
    "campusId": "4dde3052-393d-4161-98da-23dde61901dd",
    "slug": "kansas-state-university",
    "name": "Kansas State",
    "isSec": false,
    "conference": "Big 12",
    "courseCode": "ACCTG 241",
    "c1": "#512888",
    "c2": "#FFFFFF",
    "aliases": [
      "K-State",
      "Kansas State University"
    ]
  },
  {
    "id": "kennesaw-state-university",
    "campusId": "3888d1aa-8bf8-4ca7-9b42-6e1528b5972f",
    "slug": "kennesaw-state-university",
    "name": "Kennesaw State University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 2101",
    "c1": "#FDBB30",
    "c2": "#0B1315",
    "aliases": []
  },
  {
    "id": "kentucky",
    "campusId": "ae339230-577e-4569-a7d1-d1e45d1cfe91",
    "slug": "university-of-kentucky",
    "name": "Kentucky",
    "isSec": true,
    "conference": "SEC",
    "courseCode": "ACC 201",
    "c1": "#0033A0",
    "c2": "#FFFFFF",
    "aliases": [
      "UK",
      "Wildcats",
      "University of Kentucky"
    ]
  },
  {
    "id": "lamar-university",
    "campusId": "503ab8f8-7be1-496d-9b82-2e4392bfd188",
    "slug": "lamar-university",
    "name": "Lamar University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 2301",
    "c1": "#C8102E",
    "c2": "#000000",
    "aliases": []
  },
  {
    "id": "liberty-university",
    "campusId": "a44a848d-4281-4780-8e29-955221802623",
    "slug": "liberty-university",
    "name": "Liberty University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 211",
    "c1": "#A41E35",
    "c2": "#003366",
    "aliases": []
  },
  {
    "id": "louisville",
    "campusId": "abad6121-4309-4f35-a13c-beba333d56dc",
    "slug": "university-of-louisville",
    "name": "Louisville",
    "isSec": false,
    "conference": "ACC",
    "courseCode": "ACCT 201",
    "c1": "#AD0000",
    "c2": "#FFFFFF",
    "aliases": [
      "UofL",
      "University of Louisville"
    ]
  },
  {
    "id": "loyola-university-chicago",
    "campusId": "ce1c0370-a602-4ae8-94a5-a45ab40cf0d2",
    "slug": "loyola-university-chicago",
    "name": "Loyola University Chicago",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 201",
    "c1": "#862633",
    "c2": "#FFC72A",
    "aliases": []
  },
  {
    "id": "loyola-university-new-orleans",
    "campusId": "e6d861bc-be3a-4470-9fef-05fe7bb9c81b",
    "slug": "loyola-university-new-orleans",
    "name": "Loyola University New Orleans",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT B202",
    "c1": "#8B0000",
    "c2": "#FFD700",
    "aliases": []
  },
  {
    "id": "lsu",
    "campusId": "698dd98f-dd92-46c1-8f28-e930568cb15d",
    "slug": "louisiana-state-university",
    "name": "LSU",
    "isSec": true,
    "conference": "SEC",
    "courseCode": "ACCT 2001",
    "c1": "#461D7C",
    "c2": "#FDD023",
    "aliases": [
      "Louisiana State",
      "Tigers",
      "Baton Rouge",
      "Louisiana State University"
    ]
  },
  {
    "id": "maryland",
    "campusId": "b2c34d1b-f623-4206-99e3-287f52e82fcd",
    "slug": "university-of-maryland",
    "name": "Maryland",
    "isSec": false,
    "conference": "Big Ten",
    "courseCode": "BMGT 220",
    "c1": "#E21833",
    "c2": "#FFD200",
    "aliases": [
      "UMD",
      "University of Maryland"
    ]
  },
  {
    "id": "massachusetts-institute-of-technology",
    "campusId": "de916521-862f-4160-a359-6e202af729c4",
    "slug": "massachusetts-institute-of-technology",
    "name": "Massachusetts Institute of Technology",
    "isSec": false,
    "conference": "Other",
    "courseCode": "15.501",
    "c1": "#8A1538",
    "c2": "#A31F34",
    "aliases": []
  },
  {
    "id": "miami",
    "campusId": "c2dbd5ac-8dbd-4488-92da-546c361fd88e",
    "slug": "university-of-miami",
    "name": "Miami",
    "isSec": false,
    "conference": "ACC",
    "courseCode": "ACC 211",
    "c1": "#F47321",
    "c2": "#005030",
    "aliases": [
      "Miami FL",
      "University of Miami"
    ]
  },
  {
    "id": "miami-oh",
    "campusId": "cc8d19b7-6f88-4162-af9b-629c9c9b91c0",
    "slug": "miami-university-ohio",
    "name": "Miami (OH)",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACC 221",
    "c1": "#C8102E",
    "c2": "#FFFFFF",
    "aliases": [
      "Miami Ohio",
      "Miami University"
    ]
  },
  {
    "id": "michigan-state",
    "campusId": "efe5a52b-cca0-43c5-b655-7e2d758945d8",
    "slug": "michigan-state-university",
    "name": "Michigan State",
    "isSec": false,
    "conference": "Big Ten",
    "courseCode": "ACC 201",
    "c1": "#18453B",
    "c2": "#FFFFFF",
    "aliases": [
      "Michigan State University"
    ]
  },
  {
    "id": "minnesota",
    "campusId": "6a03001e-d222-4c4e-9437-1cab7241feaa",
    "slug": "university-of-minnesota",
    "name": "Minnesota",
    "isSec": false,
    "conference": "Big Ten",
    "courseCode": "ACCT 2051",
    "c1": "#7A0019",
    "c2": "#FFCC33",
    "aliases": [
      "UMN",
      "University of Minnesota"
    ]
  },
  {
    "id": "mississippi-state",
    "campusId": "95246fc8-1ce6-409e-b454-d03c82766719",
    "slug": "mississippi-state-university",
    "name": "Mississippi State",
    "isSec": true,
    "conference": "SEC",
    "courseCode": "ACC 2013",
    "c1": "#660000",
    "c2": "#C8C8C8",
    "aliases": [
      "MSU",
      "Miss State",
      "Bulldogs",
      "Starkville",
      "Mississippi State University"
    ]
  },
  {
    "id": "missouri-southern-state-university",
    "campusId": "b92f3930-82f8-4470-9c8f-cf3f06f60ebf",
    "slug": "missouri-southern-state-university",
    "name": "Missouri Southern State University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "AC 201",
    "c1": "#003366",
    "c2": "#FFD700",
    "aliases": []
  },
  {
    "id": "missouri-state-university",
    "campusId": "6cec1e83-5cda-403b-8da6-2b7b004db570",
    "slug": "missouri-state-university",
    "name": "Missouri State University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACC 201",
    "c1": "#5E0009",
    "c2": "#FFFFFF",
    "aliases": []
  },
  {
    "id": "mizzou",
    "campusId": "f16686c2-edc6-43f8-9638-6890f52c829a",
    "slug": "university-of-missouri",
    "name": "Mizzou",
    "isSec": true,
    "conference": "SEC",
    "courseCode": "ACCTCY 2026",
    "c1": "#F1B82D",
    "c2": "#000000",
    "aliases": [
      "Missouri",
      "MU",
      "Tigers",
      "University of Missouri"
    ]
  },
  {
    "id": "montana-state-university",
    "campusId": "fdf5e2e4-ed2d-4fd4-8d46-2d3cc88c0cbc",
    "slug": "montana-state-university",
    "name": "Montana State University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACTG 201",
    "c1": "#00205B",
    "c2": "#BF995B",
    "aliases": []
  },
  {
    "id": "morehouse-college",
    "campusId": "22af1952-1da1-45e4-8128-b977774a7936",
    "slug": "morehouse-college",
    "name": "Morehouse College",
    "isSec": false,
    "conference": "Other",
    "courseCode": "HBA 201",
    "c1": "#800020",
    "c2": "#FFFFFF",
    "aliases": []
  },
  {
    "id": "nc-state",
    "campusId": "26fec746-f7a8-48d0-8ac6-3bda7c78d82f",
    "slug": "north-carolina-state-university",
    "name": "NC State",
    "isSec": false,
    "conference": "ACC",
    "courseCode": "ACC 210",
    "c1": "#CC0000",
    "c2": "#FFFFFF",
    "aliases": [
      "NCSU",
      "North Carolina State University"
    ]
  },
  {
    "id": "nebraska",
    "campusId": "2e0aaa41-7bd2-453d-9a9d-32c53074cc9c",
    "slug": "university-of-nebraska-lincoln",
    "name": "Nebraska",
    "isSec": false,
    "conference": "Big Ten",
    "courseCode": "ACCT 201",
    "c1": "#D00000",
    "c2": "#F5F1E7",
    "aliases": [
      "university of nebraska",
      "University of Nebraska-Lincoln"
    ]
  },
  {
    "id": "nelson-university",
    "campusId": "f2efedd3-7d70-4aaf-9346-cc5f46f5be05",
    "slug": "nelson-university",
    "name": "Nelson University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACC 2213",
    "c1": "#003366",
    "c2": "#FFFFFF",
    "aliases": []
  },
  {
    "id": "new-york-university",
    "campusId": "62f42404-8006-4fa6-9068-516683198e09",
    "slug": "new-york-university",
    "name": "New York University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT-UB 1",
    "c1": "#57068c",
    "c2": "#ffffff",
    "aliases": []
  },
  {
    "id": "north-carolina",
    "campusId": "ffef200f-6667-455f-a599-08987f16e7fa",
    "slug": "university-of-north-carolina-at-chapel-hill",
    "name": "North Carolina",
    "isSec": false,
    "conference": "ACC",
    "courseCode": "BUSI 407",
    "c1": "#4B9CD3",
    "c2": "#13294B",
    "aliases": [
      "UNC",
      "university of north carolina",
      "University of North Carolina at Chapel Hill"
    ]
  },
  {
    "id": "north-dakota-state-university",
    "campusId": "247b6ca0-f442-4b46-9093-595086f24a23",
    "slug": "north-dakota-state-university",
    "name": "North Dakota State University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 200",
    "c1": "#006633",
    "c2": "#FFCC33",
    "aliases": []
  },
  {
    "id": "northeastern-university",
    "campusId": "3d62ef87-3f1a-4060-826c-97586e2d3ede",
    "slug": "northeastern-university",
    "name": "Northeastern University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 1201",
    "c1": "#C8102E",
    "c2": "#000000",
    "aliases": []
  },
  {
    "id": "northwestern",
    "campusId": "d0190710-b330-4159-9927-65a9c37409eb",
    "slug": "northwestern-university",
    "name": "Northwestern",
    "isSec": false,
    "conference": "Big Ten",
    "courseCode": "ACCOUNT 201",
    "c1": "#4E2A84",
    "c2": "#FFFFFF",
    "aliases": [
      "NU",
      "Northwestern University"
    ]
  },
  {
    "id": "northwestern-state-university",
    "campusId": "ae5fb538-c4d4-4b5a-a2f7-faff90b27b12",
    "slug": "northwestern-state-university",
    "name": "Northwestern State University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 2000",
    "c1": "#663399",
    "c2": "#FFA500",
    "aliases": []
  },
  {
    "id": "oakland-community-college",
    "campusId": "f8ac653e-067b-4df9-aa85-52a834d3bf8f",
    "slug": "oakland-community-college",
    "name": "Oakland Community College",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACC 1810",
    "c1": "#003366",
    "c2": "#0066CC",
    "aliases": []
  },
  {
    "id": "ohio-state",
    "campusId": "1e6b6504-3a9c-44e2-81a9-ee961f66563a",
    "slug": "ohio-state-university",
    "name": "Ohio State",
    "isSec": false,
    "conference": "Big Ten",
    "courseCode": "ACCTMIS 2200",
    "c1": "#BA0C2F",
    "c2": "#A7B1B7",
    "aliases": [
      "tOSU",
      "Ohio State University"
    ]
  },
  {
    "id": "oklahoma",
    "campusId": "91e62f9c-43b0-41f3-a84d-002824754da6",
    "slug": "university-of-oklahoma",
    "name": "Oklahoma",
    "isSec": true,
    "conference": "SEC",
    "courseCode": "ACCT 2113",
    "c1": "#841617",
    "c2": "#FDF9D8",
    "aliases": [
      "OU",
      "Sooners",
      "University of Oklahoma"
    ]
  },
  {
    "id": "oklahoma-state",
    "campusId": "d8ed77fe-4aac-444b-9815-261642ee1052",
    "slug": "oklahoma-state-university",
    "name": "Oklahoma State",
    "isSec": false,
    "conference": "Big 12",
    "courseCode": "ACCT 2103",
    "c1": "#FE5C00",
    "c2": "#000000",
    "aliases": [
      "Okie State",
      "Oklahoma State University"
    ]
  },
  {
    "id": "old-dominion-university",
    "campusId": "18f4bb62-8715-4e8f-941d-748768316b75",
    "slug": "old-dominion-university",
    "name": "Old Dominion University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 201",
    "c1": "#003366",
    "c2": "#C5C5C5",
    "aliases": []
  },
  {
    "id": "ole-miss",
    "campusId": "7b92a320-b196-43f2-a241-77a0805816fe",
    "slug": "university-of-mississippi",
    "name": "Ole Miss",
    "isSec": true,
    "conference": "SEC",
    "courseCode": "ACCY 201",
    "c1": "#14213D",
    "c2": "#CE1126",
    "aliases": [
      "University of Mississippi",
      "UM",
      "OM",
      "Rebels",
      "Oxford"
    ]
  },
  {
    "id": "orange-coast-college",
    "campusId": "64eba2ec-0147-42d0-bf3a-cb4fbd597666",
    "slug": "orange-coast-college",
    "name": "Orange Coast College",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT A101",
    "c1": "#E85D04",
    "c2": "#003F7F",
    "aliases": []
  },
  {
    "id": "oregon",
    "campusId": "62187d7a-6154-4167-9c3d-04fecdc57354",
    "slug": "university-of-oregon",
    "name": "Oregon",
    "isSec": false,
    "conference": "Big Ten",
    "courseCode": "BA 211Z",
    "c1": "#007030",
    "c2": "#FEE11A",
    "aliases": [
      "UO",
      "University of Oregon"
    ]
  },
  {
    "id": "oregon-state",
    "campusId": "0f207a42-7b5b-46f3-8d9b-7b753a0451fe",
    "slug": "oregon-state-university",
    "name": "Oregon State",
    "isSec": false,
    "conference": "Other",
    "courseCode": "BA 211Z",
    "c1": "#D73F09",
    "c2": "#000000",
    "aliases": [
      "Oregon State University"
    ]
  },
  {
    "id": "ottawa-university",
    "campusId": "960ac540-be74-4a05-8d1c-e84de0c293e8",
    "slug": "ottawa-university",
    "name": "Ottawa University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACC 20364",
    "c1": "#003366",
    "c2": "#FFD700",
    "aliases": []
  },
  {
    "id": "penn-state",
    "campusId": "afb9cd13-7cd5-48fb-8416-e358d02bc2ae",
    "slug": "pennsylvania-state-university",
    "name": "Penn State",
    "isSec": false,
    "conference": "Big Ten",
    "courseCode": "ACCTG 211",
    "c1": "#001E44",
    "c2": "#FFFFFF",
    "aliases": [
      "PSU",
      "Penn St",
      "Pennsylvania State University"
    ]
  },
  {
    "id": "penn-state-york",
    "campusId": "277031ea-17f5-47ee-b8e4-51e4e9f008b2",
    "slug": "penn-state-york",
    "name": "Penn State York",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCTG 211",
    "c1": "#041E42",
    "c2": "#FFFFFF",
    "aliases": []
  },
  {
    "id": "pittsburgh",
    "campusId": "2668a8b5-52c6-4a41-b2df-a83f29330d3b",
    "slug": "university-of-pittsburgh",
    "name": "Pittsburgh",
    "isSec": false,
    "conference": "ACC",
    "courseCode": "BUSACC 0030",
    "c1": "#003594",
    "c2": "#FFB81C",
    "aliases": [
      "Pitt",
      "University of Pittsburgh"
    ]
  },
  {
    "id": "rhode-island-college",
    "campusId": "217f80e3-e73d-44b5-b442-996200638993",
    "slug": "rhode-island-college",
    "name": "Rhode Island College",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 201",
    "c1": "#003366",
    "c2": "#FFD700",
    "aliases": []
  },
  {
    "id": "rochester-institute-of-technology",
    "campusId": "82ddec8e-3ba1-43c1-a445-7efee49786e8",
    "slug": "rochester-institute-of-technology",
    "name": "Rochester Institute of Technology",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 110",
    "c1": "#F76902",
    "c2": "#594236",
    "aliases": []
  },
  {
    "id": "rockhurst-university",
    "campusId": "09de9381-4821-4dd2-af13-9b0dab76009d",
    "slug": "rockhurst-university",
    "name": "Rockhurst University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "AC 2010",
    "c1": "#003366",
    "c2": "#C8102E",
    "aliases": []
  },
  {
    "id": "rutgers",
    "campusId": "f2bb9523-3512-405c-bcc1-ee2ae517f08c",
    "slug": "rutgers-university",
    "name": "Rutgers",
    "isSec": false,
    "conference": "Big Ten",
    "courseCode": "33:010:272",
    "c1": "#CC0033",
    "c2": "#FFFFFF",
    "aliases": [
      "Rutgers University"
    ]
  },
  {
    "id": "salisbury-university",
    "campusId": "ec4f4635-fa9b-41eb-ac1c-5c61a8722b97",
    "slug": "salisbury-university",
    "name": "Salisbury University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 201",
    "c1": "#003366",
    "c2": "#FFD700",
    "aliases": []
  },
  {
    "id": "sam-houston-state-university",
    "campusId": "9619e982-14a0-4a2a-b768-75a1443715ff",
    "slug": "sam-houston-state-university",
    "name": "Sam Houston State University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 2301",
    "c1": "#FF6A00",
    "c2": "#FFFFFF",
    "aliases": []
  },
  {
    "id": "san-diego-state",
    "campusId": "7325256b-319c-4948-b5a0-5f2016f38dca",
    "slug": "san-diego-state-university",
    "name": "San Diego State",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCTG 201",
    "c1": "#A6192E",
    "c2": "#FFFFFF",
    "aliases": [
      "SDSU",
      "San Diego State University"
    ]
  },
  {
    "id": "san-francisco-state-university",
    "campusId": "599b6c9e-4316-48a3-a647-7e0a782e7ed2",
    "slug": "san-francisco-state-university",
    "name": "San Francisco State University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 100",
    "c1": "#4A2C7C",
    "c2": "#FFB81C",
    "aliases": []
  },
  {
    "id": "savannah-state-university",
    "campusId": "acde21cd-fdf6-410a-a141-a09eaaf24bac",
    "slug": "savannah-state-university",
    "name": "Savannah State University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 2101",
    "c1": "#003366",
    "c2": "#FF6600",
    "aliases": []
  },
  {
    "id": "seattle-university",
    "campusId": "e7215e61-04b3-4e36-afa7-06e3b898126c",
    "slug": "seattle-university",
    "name": "Seattle University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 2300",
    "c1": "#AA0000",
    "c2": "#FFFFFF",
    "aliases": []
  },
  {
    "id": "seminole-state-college-of-florida",
    "campusId": "7d9df2aa-4485-48e4-86f7-bfd409b9ef35",
    "slug": "seminole-state-college-of-florida",
    "name": "Seminole State College of Florida",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACG 2021",
    "c1": "#003366",
    "c2": "#FF6600",
    "aliases": []
  },
  {
    "id": "smu",
    "campusId": "fb5f2ade-df5d-4e16-9557-33d1232ffaba",
    "slug": "southern-methodist-university",
    "name": "SMU",
    "isSec": false,
    "conference": "ACC",
    "courseCode": "ACCT 2301",
    "c1": "#CC0035",
    "c2": "#FFFFFF",
    "aliases": [
      "Southern Methodist University"
    ]
  },
  {
    "id": "south-carolina",
    "campusId": "5f5bd18d-b92f-4d56-aced-23bce4c983d5",
    "slug": "university-of-south-carolina",
    "name": "South Carolina",
    "isSec": true,
    "conference": "SEC",
    "courseCode": "ACCT 225",
    "c1": "#73000A",
    "c2": "#000000",
    "aliases": [
      "USC",
      "South Carolina Gamecocks",
      "Gamecocks",
      "University of South Carolina"
    ]
  },
  {
    "id": "southeastern-oklahoma-state-university",
    "campusId": "916ffb4e-6b04-49cf-a8fb-3ab2a6706dd1",
    "slug": "southeastern-oklahoma-state-university",
    "name": "Southeastern Oklahoma State University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 2103",
    "c1": "#003366",
    "c2": "#FFD700",
    "aliases": []
  },
  {
    "id": "spalding-university",
    "campusId": "2c482aba-f2cb-4133-b4bf-f3e05b1ac071",
    "slug": "spalding-university",
    "name": "Spalding University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACC 261",
    "c1": "#003366",
    "c2": "#FFD700",
    "aliases": []
  },
  {
    "id": "stephen-f-austin-state-university",
    "campusId": "fefc04a6-4fad-4a75-a7ff-1bf58ff91bec",
    "slug": "stephen-f-austin-state-university",
    "name": "Stephen F. Austin State University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 2301",
    "c1": "#663399",
    "c2": "#FFFFFF",
    "aliases": []
  },
  {
    "id": "suffolk-county-community-college",
    "campusId": "88939f16-1d5a-42f4-86bd-77c8ddcd3d1f",
    "slug": "suffolk-county-community-college",
    "name": "Suffolk County Community College",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACC 101",
    "c1": "#003366",
    "c2": "#FFD700",
    "aliases": []
  },
  {
    "id": "suffolk-university",
    "campusId": "ac82bfcf-5d9d-45a3-a652-89b5f992485f",
    "slug": "suffolk-university",
    "name": "Suffolk University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 201",
    "c1": "#003DA5",
    "c2": "#FFD100",
    "aliases": []
  },
  {
    "id": "suny-fredonia",
    "campusId": "18b2b639-de5a-41a6-b7b8-0e05f579b533",
    "slug": "suny-fredonia",
    "name": "SUNY Fredonia",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 201",
    "c1": "#003366",
    "c2": "#FFD700",
    "aliases": []
  },
  {
    "id": "syracuse",
    "campusId": "4528bb03-6544-43ad-bb02-17a0f21130f9",
    "slug": "syracuse-university",
    "name": "Syracuse",
    "isSec": false,
    "conference": "ACC",
    "courseCode": "ACC 151",
    "c1": "#F76900",
    "c2": "#000E54",
    "aliases": [
      "Syracuse University"
    ]
  },
  {
    "id": "tcu",
    "campusId": "8a987f3f-ef08-4f2f-be5c-d18e032b6796",
    "slug": "texas-christian-university",
    "name": "TCU",
    "isSec": false,
    "conference": "Big 12",
    "courseCode": "ACCT 20353",
    "c1": "#4D1979",
    "c2": "#FFFFFF",
    "aliases": [
      "Texas Christian University"
    ]
  },
  {
    "id": "tennessee",
    "campusId": "9c4775be-7d82-4a3e-840c-349c5e15d8e8",
    "slug": "university-of-tennessee-knoxville",
    "name": "Tennessee",
    "isSec": true,
    "conference": "SEC",
    "courseCode": "ACCT 200",
    "c1": "#FF8200",
    "c2": "#FFFFFF",
    "aliases": [
      "UT Knoxville",
      "Vols",
      "Volunteers",
      "University of Tennessee, Knoxville"
    ]
  },
  {
    "id": "texas",
    "campusId": "faad6039-be72-4f5c-8ad5-ca7b95e2889f",
    "slug": "university-of-texas-at-austin",
    "name": "Texas",
    "isSec": true,
    "conference": "SEC",
    "courseCode": "ACC 311",
    "c1": "#BF5700",
    "c2": "#FFFFFF",
    "aliases": [
      "UT Austin",
      "UT",
      "Longhorns",
      "University of Texas at Austin"
    ]
  },
  {
    "id": "texas-aandm",
    "campusId": "92e4a5d9-eeb3-4065-ac8a-5a4390fbc584",
    "slug": "texas-aandm-university",
    "name": "Texas A&M",
    "isSec": true,
    "conference": "SEC",
    "courseCode": "ACCT 229",
    "c1": "#500000",
    "c2": "#FFFFFF",
    "aliases": [
      "A&M",
      "TAMU",
      "Aggies",
      "College Station",
      "Texas A&M University"
    ]
  },
  {
    "id": "texas-state-university",
    "campusId": "1ad51593-c384-497f-9c1d-ea8afb34d5b5",
    "slug": "texas-state-university",
    "name": "Texas State University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACC 2361",
    "c1": "#501214",
    "c2": "#6A2C91",
    "aliases": []
  },
  {
    "id": "texas-tech",
    "campusId": "e7fff2aa-78fe-459f-9211-2584fae1f5ee",
    "slug": "texas-tech-university",
    "name": "Texas Tech",
    "isSec": false,
    "conference": "Big 12",
    "courseCode": "ACCT 2300",
    "c1": "#E90802",
    "c2": "#000000",
    "aliases": [
      "TTU",
      "Texas Tech University"
    ]
  },
  {
    "id": "texas-woman-s-university",
    "campusId": "bb30b97a-81d3-4ce5-8683-3805c66ff85f",
    "slug": "texas-woman-s-university",
    "name": "Texas Woman's University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 2043",
    "c1": "#5C2E91",
    "c2": "#FFD700",
    "aliases": []
  },
  {
    "id": "the-university-of-texas-at-arlington",
    "campusId": "c34899c1-0fcd-4a20-b9a9-5cec52734b70",
    "slug": "the-university-of-texas-at-arlington",
    "name": "The University of Texas at Arlington",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 2301",
    "c1": "#003366",
    "c2": "#FF6600",
    "aliases": []
  },
  {
    "id": "the-university-of-texas-at-dallas",
    "campusId": "408b44a5-1704-40d5-965d-dc02cb78f55c",
    "slug": "the-university-of-texas-at-dallas",
    "name": "The University of Texas at Dallas",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 2301",
    "c1": "#C75B12",
    "c2": "#00703C",
    "aliases": []
  },
  {
    "id": "the-university-of-texas-at-san-antonio",
    "campusId": "980fcc26-676e-4e05-883e-8ab55867020a",
    "slug": "the-university-of-texas-at-san-antonio",
    "name": "The University of Texas at San Antonio",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACC 2013",
    "c1": "#F15A22",
    "c2": "#0C2340",
    "aliases": []
  },
  {
    "id": "the-university-of-texas-rio-grande-valley",
    "campusId": "8f13bb14-57bf-4d27-92a5-51f638c18ecc",
    "slug": "the-university-of-texas-rio-grande-valley",
    "name": "The University of Texas Rio Grande Valley",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 2301",
    "c1": "#FF6A00",
    "c2": "#003C71",
    "aliases": []
  },
  {
    "id": "towson-university",
    "campusId": "acae37b2-a2b4-41cb-a205-4e807df400e4",
    "slug": "towson-university",
    "name": "Towson University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 201",
    "c1": "#000000",
    "c2": "#FFCC00",
    "aliases": []
  },
  {
    "id": "troy-university",
    "campusId": "4d5deb87-3fe2-4437-9c93-4830ca167366",
    "slug": "troy-university",
    "name": "Troy University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACT 2291",
    "c1": "#8B0000",
    "c2": "#C0C0C0",
    "aliases": []
  },
  {
    "id": "tulsa-community-college",
    "campusId": "7148ae85-ca10-4541-89d6-dfb8dce8b24a",
    "slug": "tulsa-community-college",
    "name": "Tulsa Community College",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 2213",
    "c1": "#003366",
    "c2": "#FF6600",
    "aliases": []
  },
  {
    "id": "ucf",
    "campusId": "9fc579bc-bed2-4e8b-9c89-0958f7edda42",
    "slug": "university-of-central-florida",
    "name": "UCF",
    "isSec": false,
    "conference": "Big 12",
    "courseCode": "ACG 2021",
    "c1": "#000000",
    "c2": "#FFC904",
    "aliases": [
      "University of Central Florida"
    ]
  },
  {
    "id": "university-of-colorado-colorado-springs",
    "campusId": "85e0b395-ec04-418c-a583-3a1e88df2c7c",
    "slug": "university-of-colorado-colorado-springs",
    "name": "University of Colorado Colorado Springs",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 2010",
    "c1": "#CFB87C",
    "c2": "#1E4D72",
    "aliases": []
  },
  {
    "id": "university-of-connecticut",
    "campusId": "49672cb7-7f1e-4090-98e9-e192431aaeab",
    "slug": "university-of-connecticut",
    "name": "University of Connecticut",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 2001",
    "c1": "#000E2F",
    "c2": "#FFFFFF",
    "aliases": []
  },
  {
    "id": "university-of-houston-downtown",
    "campusId": "76eb1308-7c24-45e6-b436-aef5a7dc40af",
    "slug": "university-of-houston-downtown",
    "name": "University of Houston - Downtown",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACC 2301",
    "c1": "#C8102E",
    "c2": "#0C2340",
    "aliases": []
  },
  {
    "id": "university-of-idaho",
    "campusId": "fa9fb190-4098-47eb-8dce-5ef934435b3d",
    "slug": "university-of-idaho",
    "name": "University of Idaho",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 201",
    "c1": "#FFB300",
    "c2": "#8B8B8B",
    "aliases": []
  },
  {
    "id": "university-of-illinois-chicago",
    "campusId": "9af2ea11-48be-4d06-b454-7949013dbe14",
    "slug": "university-of-illinois-chicago",
    "name": "University of Illinois Chicago",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACTG 210",
    "c1": "#C8102E",
    "c2": "#001E62",
    "aliases": []
  },
  {
    "id": "university-of-la-verne",
    "campusId": "80ae185c-a39a-4506-9f54-adefebf47662",
    "slug": "university-of-la-verne",
    "name": "University of La Verne",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 201",
    "c1": "#8B0000",
    "c2": "#FFD700",
    "aliases": []
  },
  {
    "id": "university-of-mary-washington",
    "campusId": "f777aeb5-db85-49a8-8f49-7f8936d17abf",
    "slug": "university-of-mary-washington",
    "name": "University of Mary Washington",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 101",
    "c1": "#003366",
    "c2": "#CCCCCC",
    "aliases": []
  },
  {
    "id": "university-of-massachusetts-dartmouth",
    "campusId": "b7b28289-86f4-4cdc-90da-39211bcd1cc3",
    "slug": "university-of-massachusetts-dartmouth",
    "name": "University of Massachusetts Dartmouth",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACT 211",
    "c1": "#003DA5",
    "c2": "#FFD100",
    "aliases": []
  },
  {
    "id": "university-of-massachusetts-lowell",
    "campusId": "b1e37925-8407-4abd-9826-11c8191a905a",
    "slug": "university-of-massachusetts-lowell",
    "name": "University of Massachusetts Lowell",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT.2010",
    "c1": "#003F7F",
    "c2": "#C8102E",
    "aliases": []
  },
  {
    "id": "university-of-missouri-st-louis",
    "campusId": "23805d96-0063-4b26-aba8-a02a866086a4",
    "slug": "university-of-missourist-louis",
    "name": "University of Missouri–St. Louis",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCTNG 2400",
    "c1": "#FFCC00",
    "c2": "#003366",
    "aliases": []
  },
  {
    "id": "university-of-nevada-las-vegas",
    "campusId": "21cad3ab-fb66-4efb-b338-430cbbdd41e9",
    "slug": "university-of-nevada-las-vegas",
    "name": "University of Nevada, Las Vegas",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACC 201",
    "c1": "#E31837",
    "c2": "#9FA1A4",
    "aliases": []
  },
  {
    "id": "university-of-north-alabama",
    "campusId": "d37a8470-046b-439a-9185-53b027865f35",
    "slug": "university-of-north-alabama",
    "name": "University of North Alabama",
    "isSec": false,
    "conference": "Other",
    "courseCode": "AC 291",
    "c1": "#46166B",
    "c2": "#DB9F11",
    "aliases": []
  },
  {
    "id": "university-of-north-carolina-at-charlotte",
    "campusId": "7f9727f8-72ca-414d-9192-c8b52566450f",
    "slug": "university-of-north-carolina-at-charlotte",
    "name": "University of North Carolina at Charlotte",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 2121",
    "c1": "#00703C",
    "c2": "#B3A369",
    "aliases": []
  },
  {
    "id": "university-of-north-carolina-at-greensboro",
    "campusId": "4762f036-6410-449b-8251-87eac11624d9",
    "slug": "university-of-north-carolina-at-greensboro",
    "name": "University of North Carolina at Greensboro",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACC 201",
    "c1": "#003366",
    "c2": "#FFD700",
    "aliases": []
  },
  {
    "id": "university-of-north-texas",
    "campusId": "48d46940-2cd8-4cfd-a9a3-b4c00bd3f9bc",
    "slug": "university-of-north-texas",
    "name": "University of North Texas",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 2010",
    "c1": "#00853E",
    "c2": "#FFFFFF",
    "aliases": []
  },
  {
    "id": "university-of-north-texas-at-dallas",
    "campusId": "cf743bf8-b71e-4298-bb5c-c1b374f0eb8a",
    "slug": "university-of-north-texas-at-dallas",
    "name": "University of North Texas at Dallas",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 2301",
    "c1": "#00853E",
    "c2": "#FFFFFF",
    "aliases": []
  },
  {
    "id": "university-of-pennsylvania",
    "campusId": "d1a63c43-c944-4ed3-a377-40e899ce290e",
    "slug": "university-of-pennsylvania",
    "name": "University of Pennsylvania",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 1010",
    "c1": "#011F5B",
    "c2": "#990000",
    "aliases": []
  },
  {
    "id": "university-of-south-carolina-upstate",
    "campusId": "2353c499-87b3-4ddc-8c33-f595c39f79a2",
    "slug": "university-of-south-carolina-upstate",
    "name": "University of South Carolina Upstate",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT U225",
    "c1": "#73000A",
    "c2": "#000000",
    "aliases": []
  },
  {
    "id": "university-of-south-florida",
    "campusId": "ae2ba2d1-a457-42b0-840d-83d83a6ad39b",
    "slug": "university-of-south-florida",
    "name": "University of South Florida",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACG 2021",
    "c1": "#00471B",
    "c2": "#CFC493",
    "aliases": []
  },
  {
    "id": "university-of-southern-indiana",
    "campusId": "e615f07f-9c76-4594-be28-2f1e2551ba10",
    "slug": "university-of-southern-indiana",
    "name": "University of Southern Indiana",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 201",
    "c1": "#003366",
    "c2": "#FF6600",
    "aliases": []
  },
  {
    "id": "university-of-southern-mississippi",
    "campusId": "2dedca50-1bac-4bb5-9820-9aa41c1617fb",
    "slug": "university-of-southern-mississippi",
    "name": "University of Southern Mississippi",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACC 200",
    "c1": "#FFCC00",
    "c2": "#000000",
    "aliases": []
  },
  {
    "id": "university-of-st-thomas",
    "campusId": "5c3debe3-95b4-4dd9-8680-23c8c72c1077",
    "slug": "university-of-st-thomas",
    "name": "University of St. Thomas",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 2301",
    "c1": "#663399",
    "c2": "#C5C5C5",
    "aliases": []
  },
  {
    "id": "university-of-texas-at-el-paso",
    "campusId": "8258c5bb-9425-4e60-9996-61f5713e9f2b",
    "slug": "university-of-texas-at-el-paso",
    "name": "University of Texas at El Paso",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 2301",
    "c1": "#FF8200",
    "c2": "#041E42",
    "aliases": []
  },
  {
    "id": "university-of-toledo",
    "campusId": "94f67099-2561-4fd8-92af-ed730e8db5ac",
    "slug": "university-of-toledo",
    "name": "University of Toledo",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 2100",
    "c1": "#003E7E",
    "c2": "#FFD700",
    "aliases": []
  },
  {
    "id": "university-of-vermont",
    "campusId": "47d4b417-0631-4081-ae04-95578efb9f62",
    "slug": "university-of-vermont",
    "name": "University of Vermont",
    "isSec": false,
    "conference": "Other",
    "courseCode": "BUS 1610",
    "c1": "#005640",
    "c2": "#FFB500",
    "aliases": []
  },
  {
    "id": "university-of-west-georgia",
    "campusId": "6584645d-3558-480f-826e-b786ffbbf310",
    "slug": "university-of-west-georgia",
    "name": "University of West Georgia",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 2101",
    "c1": "#004990",
    "c2": "#C8102E",
    "aliases": []
  },
  {
    "id": "university-of-wisconsin-milwaukee",
    "campusId": "398c1e45-85ba-4330-97e8-04d7c88c9cde",
    "slug": "university-of-wisconsinmilwaukee",
    "name": "University of Wisconsin–Milwaukee",
    "isSec": false,
    "conference": "Other",
    "courseCode": "BUS ADM 201",
    "c1": "#003366",
    "c2": "#FFD700",
    "aliases": []
  },
  {
    "id": "university-of-wisconsin-oshkosh",
    "campusId": "088edb1d-097d-4182-abd0-6bd91bd2b485",
    "slug": "university-of-wisconsinoshkosh",
    "name": "University of Wisconsin–Oshkosh",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 206",
    "c1": "#FFB71B",
    "c2": "#000000",
    "aliases": []
  },
  {
    "id": "university-of-wisconsin-stevens-point",
    "campusId": "35187e01-7447-437e-a012-ac68815b1a24",
    "slug": "university-of-wisconsinstevens-point",
    "name": "University of Wisconsin–Stevens Point",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 210",
    "c1": "#4B2E83",
    "c2": "#FFC72C",
    "aliases": []
  },
  {
    "id": "usc",
    "campusId": "bb80faac-ecaf-418a-abe3-46582214289e",
    "slug": "university-of-southern-california",
    "name": "USC",
    "isSec": false,
    "conference": "Big Ten",
    "courseCode": "BUAD 280",
    "c1": "#990000",
    "c2": "#FFCC00",
    "aliases": [
      "Southern Cal",
      "University of Southern California"
    ]
  },
  {
    "id": "utah",
    "campusId": "9fbac3ba-bd9c-4fa9-bbf3-6f2580d78616",
    "slug": "university-of-utah",
    "name": "Utah",
    "isSec": false,
    "conference": "Big 12",
    "courseCode": "ACCTG 2600",
    "c1": "#BE0000",
    "c2": "#FFFFFF",
    "aliases": [
      "University of Utah"
    ]
  },
  {
    "id": "utah-tech-university",
    "campusId": "1d6d2c96-2d39-4387-ad42-b0172a297eae",
    "slug": "utah-tech-university",
    "name": "Utah Tech University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 2010",
    "c1": "#C8102E",
    "c2": "#002B5B",
    "aliases": []
  },
  {
    "id": "vanderbilt",
    "campusId": "972451c3-bc5e-48d7-9f88-868a55378efa",
    "slug": "vanderbilt-university",
    "name": "Vanderbilt",
    "isSec": true,
    "conference": "SEC",
    "courseCode": "BUS 1100",
    "c1": "#1B1B1B",
    "c2": "#C9A227",
    "aliases": [
      "Vandy",
      "Commodores",
      "Vanderbilt University"
    ]
  },
  {
    "id": "virginia",
    "campusId": "a71aeefa-4c87-4ac3-ad74-e321c0b91615",
    "slug": "university-of-virginia",
    "name": "Virginia",
    "isSec": false,
    "conference": "ACC",
    "courseCode": "COMM 2010",
    "c1": "#E57200",
    "c2": "#232D4B",
    "aliases": [
      "UVA",
      "University of Virginia"
    ]
  },
  {
    "id": "virginia-tech",
    "campusId": "0bba23e3-06ae-438a-af5f-1a7f1f178f15",
    "slug": "virginia-tech",
    "name": "Virginia Tech",
    "isSec": false,
    "conference": "ACC",
    "courseCode": "ACIS 2115",
    "c1": "#861F41",
    "c2": "#E5751F",
    "aliases": []
  },
  {
    "id": "walla-walla-university",
    "campusId": "a3ad66ae-47ef-466d-9cbb-2c0bbe2680de",
    "slug": "walla-walla-university",
    "name": "Walla Walla University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 201",
    "c1": "#003087",
    "c2": "#FFD700",
    "aliases": []
  },
  {
    "id": "washington",
    "campusId": "79d3cbc6-a7c7-4192-87ee-200fee33ff1c",
    "slug": "university-of-washington",
    "name": "Washington",
    "isSec": false,
    "conference": "Big Ten",
    "courseCode": "ACCTG 215",
    "c1": "#4B2E83",
    "c2": "#B7A57A",
    "aliases": [
      "University of Washington"
    ]
  },
  {
    "id": "west-virginia",
    "campusId": "3ad2e7cb-9d47-434f-899f-37cabe4fcba8",
    "slug": "west-virginia-university",
    "name": "West Virginia",
    "isSec": false,
    "conference": "Big 12",
    "courseCode": "ACCT 201",
    "c1": "#002855",
    "c2": "#EAAA00",
    "aliases": [
      "WVU",
      "West Virginia University"
    ]
  },
  {
    "id": "western-colorado-university",
    "campusId": "3448114c-075e-4d97-87a2-f555c22d2e22",
    "slug": "western-colorado-university",
    "name": "Western Colorado University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACC 201",
    "c1": "#4B2E83",
    "c2": "#FFD700",
    "aliases": []
  },
  {
    "id": "western-kentucky-university",
    "campusId": "9961c567-684f-4fc4-bfea-f701a46b101d",
    "slug": "western-kentucky-university",
    "name": "Western Kentucky University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 200",
    "c1": "#C8102E",
    "c2": "#FFFFFF",
    "aliases": []
  },
  {
    "id": "wilmington-college",
    "campusId": "ac57b18f-f6c2-424c-85dd-873eb8dddef0",
    "slug": "wilmington-college",
    "name": "Wilmington College",
    "isSec": false,
    "conference": "Other",
    "courseCode": "EC 238",
    "c1": "#003366",
    "c2": "#FFFFFF",
    "aliases": []
  },
  {
    "id": "winston-salem-state-university",
    "campusId": "21fab442-05d9-42ac-a3bd-5edbd0731cb1",
    "slug": "winston-salem-state-university",
    "name": "Winston-Salem State University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACC 2316",
    "c1": "#A71930",
    "c2": "#FFD700",
    "aliases": []
  },
  {
    "id": "wisconsin",
    "campusId": "1757afcf-5163-49f0-9e94-131c666882bc",
    "slug": "university-of-wisconsin-madison",
    "name": "Wisconsin",
    "isSec": false,
    "conference": "Big Ten",
    "courseCode": "AIS 100",
    "c1": "#C5050C",
    "c2": "#FFFFFF",
    "aliases": [
      "university of wisconsin",
      "University of Wisconsin-Madison"
    ]
  },
  {
    "id": "woodbury-university",
    "campusId": "608ea94c-7e50-4f73-96a8-abb53d78e1ea",
    "slug": "woodbury-university",
    "name": "Woodbury University",
    "isSec": false,
    "conference": "Other",
    "courseCode": "ACCT 205",
    "c1": "#8B1538",
    "c2": "#FFFFFF",
    "aliases": []
  }
];
