// MOUNTAIN PALETTE — the campus recolour rule for public/brand/mt-cook.svg.
//
// The mountain is two hue families — lit faces (the artwork's reds → the campus PRIMARY) and
// shaded faces (its blues → the campus SECONDARY) — and its texture is the per-path lightness
// variation inside each family. scripts/mountain-asset.ts bucketed that variation into ≤ 10 steps
// per family and recorded each step's lightness OFFSET from the family's median shade (the table
// between the @generated markers below). mountainPalette() re-applies those offsets to ANY
// school's pair: the median step is the school colour untouched, the other steps are the same
// colour moved by the same amount the artwork moved — so every campus gets the same mountain.
//
// The one guard is the bolt's light-colour rule (bolt-palette.whyTooLight): a white / cream /
// silver secondary (Tennessee, Alabama, Nebraska…) would have its lit steps blow out into the page
// cream. Rather than a second rule, the same test picks a LOWER ceiling, and the whole family is
// compressed to fit under it with ordering intact — so the face reads as pale stone, still
// textured, never a white hole.
import { LIGHT_LIGHTNESS, NEAR_WHITE_LIGHTNESS } from "./bolt/bolt-config";
import { hexToRgb, rgbToHex, whyTooLight } from "./bolt/bolt-palette";

/** One lightness step of one family: `offset` is HSL-L relative to the family median, `share` is
 *  the fraction of that family's fills the step paints (a highlight speck is not the mountain). */
export type MountainStep = { family: "p" | "s"; step: number; offset: number; share: number };

/** `--mtn-p-3`, `--mtn-s-0` … the custom-property names the SVG fills read. */
export const STEP_VAR_PREFIX = "--mtn-";

/** The mountain as shipped — Mt Cook's own red and blue medians, so the default palette is the
 *  artwork itself. Matches styles.css `--bolt-primary` / `--bolt-secondary` on the generic home. */
export const DEFAULT_MOUNTAIN_PRIMARY = "#C62828";
export const DEFAULT_MOUNTAIN_SECONDARY = "#1565C0";

/** A step painting at least this share of its family is CORE — the fit keeps the core inside the
 *  bounds outright; the specks outside it (a five-path pink glint, two lilac ridges) are soft-
 *  clamped instead, so they can never drag the whole face away from the school colour. */
export const CORE_MIN_SHARE = 0.02;
/** Width of the soft-clamp zone below the ceiling / above the floor. */
export const SOFT_ZONE = 0.08;
/** Darkest any step may go (HSL L). A shadow face at 0 lightness is a hole, not a shadow. */
export const MOUNTAIN_FLOOR_LIGHTNESS = 0.05;
/** Ceiling for a colour that PASSES the bolt's light test — just under near-white. */
export const MOUNTAIN_CEILING_LIGHTNESS = NEAR_WHITE_LIGHTNESS - 0.04;
/** Ceiling for a colour that FAILS it (white / cream / silver): the bolt's "merely light" line,
 *  so the brightest face of a white-secondary school is a readable pale stone, not page cream. */
export const MOUNTAIN_LIGHT_CEILING_LIGHTNESS = LIGHT_LIGHTNESS + 0.14;

// @generated-start
// generated by scripts/mountain-asset.ts from mt cook textured.svg — do not hand-edit
export const MOUNTAIN_STEPS: readonly MountainStep[] = [
  { family: "p", step: 0, offset: -0.2663, share: 0.0156 },
  { family: "p", step: 1, offset: -0.169, share: 0.0663 },
  { family: "p", step: 2, offset: -0.1098, share: 0.1638 },
  { family: "p", step: 3, offset: -0.0242, share: 0.3069 },
  { family: "p", step: 4, offset: 0.0381, share: 0.1977 },
  { family: "p", step: 5, offset: 0.0999, share: 0.2159 },
  { family: "p", step: 6, offset: 0.1739, share: 0.0273 },
  { family: "p", step: 7, offset: 0.4333, share: 0.0065 },
  { family: "s", step: 0, offset: -0.0745, share: 0.1963 },
  { family: "s", step: 1, offset: -0.024, share: 0.1575 },
  { family: "s", step: 2, offset: 0.0165, share: 0.317 },
  { family: "s", step: 3, offset: 0.0898, share: 0.3027 },
  { family: "s", step: 4, offset: 0.1329, share: 0.0102 },
  { family: "s", step: 5, offset: 0.2863, share: 0.0041 },
  { family: "s", step: 6, offset: 0.4539, share: 0.0123 },
];
/** Tight viewBox of the artwork plus where the summit sits, as a fraction of that box. */
export const MOUNTAIN_GEOMETRY = { viewBox: [0, 164, 976, 909] as const, peakX: 0.4767, aspect: 0.9314 } as const;
// @generated-end

// ── hsl helpers (bolt-palette keeps its own private; the mountain needs L in and L out) ───────

function rgbToHsl(r: number, g: number, b: number): { h: number; s: number; l: number } {
  const R = r / 255,
    G = g / 255,
    B = b / 255;
  const mx = Math.max(R, G, B),
    mn = Math.min(R, G, B),
    d = mx - mn;
  const l = (mx + mn) / 2;
  if (d === 0) return { h: 0, s: 0, l };
  const s = d / (1 - Math.abs(2 * l - 1));
  let h: number;
  if (mx === R) h = ((G - B) / d) % 6;
  else if (mx === G) h = (B - R) / d + 2;
  else h = (R - G) / d + 4;
  return { h: (h * 60 + 360) % 360, s, l };
}

function hslToHex(h: number, s: number, l: number): string {
  const c = (1 - Math.abs(2 * l - 1)) * s;
  const hp = (((h % 360) + 360) % 360) / 60;
  const x = c * (1 - Math.abs((hp % 2) - 1));
  const [r1, g1, b1] =
    hp < 1 ? [c, x, 0] : hp < 2 ? [x, c, 0] : hp < 3 ? [0, c, x] : hp < 4 ? [0, x, c] : hp < 5 ? [x, 0, c] : [c, 0, x];
  const m = l - c / 2;
  return rgbToHex((r1 + m) * 255, (g1 + m) * 255, (b1 + m) * 255);
}

/** Strictly monotone squash of `x` into (lo, hi): identity through the comfortable middle, an
 *  exponential approach to the bound inside the SOFT_ZONE at each end. Never reaches the bound,
 *  never reorders two inputs. */
export function softClamp(x: number, lo: number, hi: number): number {
  const zone = Math.min(SOFT_ZONE, (hi - lo) / 2);
  const top = hi - zone,
    bottom = lo + zone;
  if (x > top) return top + zone * (1 - Math.exp(-(x - top) / zone));
  if (x < bottom) return bottom - zone * (1 - Math.exp(-(bottom - x) / zone));
  return x;
}

/** HSL lightness of every step of one family for a given base colour.
 *
 *  The ANCHOR (where the median step lands) is the base's own lightness — the school colour is
 *  painted as-is — unless the CORE steps would spill past the floor or the ceiling, in which case
 *  the anchor slides just far enough (white slides down to pale stone, black up to charcoal), and
 *  if the core is wider than the room the offsets shrink together. Every step is then soft-
 *  clamped, which only bites on the specks. Ordering is preserved throughout: the scale is
 *  positive, every step moves by the same factor, and the squash is strictly monotone. */
export function fitFamily(baseHex: string, steps: readonly Pick<MountainStep, "offset" | "share">[]): number[] {
  const rgb = hexToRgb(baseHex);
  const l = rgb ? rgbToHsl(...rgb).l : 0.5;
  const ceiling = whyTooLight(baseHex) ? MOUNTAIN_LIGHT_CEILING_LIGHTNESS : MOUNTAIN_CEILING_LIGHTNESS;
  const floor = MOUNTAIN_FLOOR_LIGHTNESS;
  const core = steps.filter((s) => s.share >= CORE_MIN_SHARE).map((s) => s.offset);
  const minOff = Math.min(0, ...core),
    maxOff = Math.max(0, ...core);
  const span = maxOff - minOff;
  const scale = span > 0 ? Math.min(1, (ceiling - floor) / span) : 1;
  const anchor = Math.max(floor - minOff * scale, Math.min(ceiling - maxOff * scale, l));
  return steps.map((s) => softClamp(anchor + s.offset * scale, floor, ceiling));
}

function stepsOf(family: MountainStep["family"]): MountainStep[] {
  return MOUNTAIN_STEPS.filter((s) => s.family === family);
}

/** No-JS-resolution path: when the base is a CSS expression (a var()) rather than a hex we can
 *  measure, approximate the lightness offset with color-mix toward white / black. The clamp
 *  cannot apply here — MountainBackdrop resolves vars to hex first precisely so it does. */
function mixToward(base: string, offset: number): string {
  if (Math.abs(offset) < 0.005) return base;
  const pct = Math.min(90, Math.round(Math.abs(offset) * 160));
  return `color-mix(in oklab, ${base} ${100 - pct}%, ${offset > 0 ? "white" : "black"})`;
}

/** THE ENTRY POINT: `--mtn-*` custom properties for one campus pair. Hex in → hex out (fitted);
 *  anything else in (a var(), a colour name) → color-mix expressions, hue kept by the browser. */
export function mountainPalette(
  c1: string = DEFAULT_MOUNTAIN_PRIMARY,
  c2: string = DEFAULT_MOUNTAIN_SECONDARY,
): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [family, base] of [
    ["p", c1],
    ["s", c2],
  ] as const) {
    const steps = stepsOf(family);
    const rgb = hexToRgb(base);
    if (rgb) {
      const { h, s } = rgbToHsl(...rgb);
      const ls = fitFamily(base, steps);
      steps.forEach((st, i) => {
        out[`${STEP_VAR_PREFIX}${family}-${st.step}`] = hslToHex(h, s, ls[i]);
      });
    } else {
      for (const st of steps) out[`${STEP_VAR_PREFIX}${family}-${st.step}`] = mixToward(base, st.offset);
    }
  }
  return out;
}
