// Regenerate public/sitemap.xml from the DB — `bun run sitemap:gen`.
// Static public routes + one <url> per PUBLIC (foundations) scenario page. Run on build
// (or whenever foundations content changes) so the sitemap stays in sync without hand-edits.

import { createClient } from "@supabase/supabase-js";
import { resolve } from "node:path";

const ORIGIN = "https://surviveaccounting.com";
const PUBLIC_FAMILY = "foundations";

const sb = createClient(
  process.env.SUPABASE_URL ?? process.env.VITE_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
  { auth: { persistSession: false } },
);

// Static public routes. /order is intentionally noindex → excluded.
const STATIC: { path: string; changefreq: string; priority: string }[] = [
  { path: "/", changefreq: "weekly", priority: "1.0" },
  { path: "/study", changefreq: "weekly", priority: "0.8" },
  { path: "/study/foundations", changefreq: "weekly", priority: "0.8" },
  { path: "/beyond", changefreq: "monthly", priority: "0.5" },
  { path: "/privacy", changefreq: "yearly", priority: "0.3" },
  { path: "/terms", changefreq: "yearly", priority: "0.3" },
];

async function foundationsScenarioPaths(): Promise<string[]> {
  const { data: course } = await sb.from("courses").select("id").eq("course_family", PUBLIC_FAMILY).maybeSingle();
  if (!course) return [];
  const { data: chs } = await sb.from("chapters").select("id").eq("course_id", (course as any).id);
  const chapterIds = ((chs ?? []) as any[]).map((c) => c.id);
  if (chapterIds.length === 0) return [];
  const { data: scs } = await (sb.from("je_scenarios") as any).select("slug").in("chapter_id", chapterIds);
  return ((scs ?? []) as { slug: string }[]).map((s) => `/study/scenarios/${s.slug}`).sort();
}

function urlEl(path: string, changefreq: string, priority: string): string {
  return `  <url>\n    <loc>${ORIGIN}${path}</loc>\n    <changefreq>${changefreq}</changefreq>\n    <priority>${priority}</priority>\n  </url>`;
}

const scenarioPaths = await foundationsScenarioPaths();
const body = [
  ...STATIC.map((r) => urlEl(r.path, r.changefreq, r.priority)),
  ...scenarioPaths.map((p) => urlEl(p, "monthly", "0.7")),
].join("\n");

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/gen-sitemap.ts (bun run sitemap:gen). Do not hand-edit.
     Static public routes + one <url> per public (foundations) scenario page. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${body}
</urlset>
`;

const out = resolve(import.meta.dir, "../public/sitemap.xml");
await Bun.write(out, xml);
console.log(`wrote ${out} — ${STATIC.length} static + ${scenarioPaths.length} foundations scenario URLs`);
