// Vite plugin — exposes the build-time QA template version map as the virtual
// module `virtual:site-qa-versions` (default export: { templateId: hash }).
//
// /admin/site-qa server code imports this map and compares each template's
// current hash against the hash stored at last verification. Computed once at
// build/dev start from the source tree (which is fully present then) and baked
// into the bundle, so the serverless runtime never touches the filesystem.
//
// Wired in vite.config.ts via defineConfig({ vite: { plugins: [siteQaVersions()] } }).
import type { Plugin } from "vite";

import { computeTemplateVersions } from "../src/lib/site-qa/versions.node";

const VIRTUAL_ID = "virtual:site-qa-versions";
const RESOLVED_ID = "\0" + VIRTUAL_ID;

export function siteQaVersions(): Plugin {
  let cached: string | null = null;
  return {
    name: "site-qa-versions",
    resolveId(id) {
      return id === VIRTUAL_ID ? RESOLVED_ID : null;
    },
    load(id) {
      if (id !== RESOLVED_ID) return null;
      if (cached == null) {
        const payload = {
          builtAt: new Date().toISOString(),
          templates: computeTemplateVersions(process.cwd()),
        };
        cached = `// generated by scripts/vite-site-qa.ts\nexport default ${JSON.stringify(payload)};\n`;
      }
      return cached;
    },
  };
}

export default siteQaVersions;
