/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as ThankyouRouteImport } from './routes/thankyou'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StudyRouteImport } from './routes/study'
import { Route as StartRouteImport } from './routes/start'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as OutreachRouteImport } from './routes/outreach'
import { Route as OrderRouteImport } from './routes/order'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as JeRouteImport } from './routes/je'
import { Route as CeqRouteImport } from './routes/ceq'
import { Route as BeyondRouteImport } from './routes/beyond'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OutreachIndexRouteImport } from './routes/outreach.index'
import { Route as TSlugRouteImport } from './routes/t.$slug'
import { Route as StudyFoundationsRouteImport } from './routes/study_.foundations'
import { Route as StudyDashboardRouteImport } from './routes/study_.dashboard'
import { Route as StudyCanvasRouteImport } from './routes/study_.canvas'
import { Route as OutreachVideoArchiveRouteImport } from './routes/outreach.video-archive'
import { Route as OutreachStudentsRouteImport } from './routes/outreach.students'
import { Route as OutreachResearchRouteImport } from './routes/outreach.research'
import { Route as OutreachRedditRouteImport } from './routes/outreach.reddit'
import { Route as OutreachProfintelScheduleRouteImport } from './routes/outreach.profintel-schedule'
import { Route as OutreachProfintelMetricsRouteImport } from './routes/outreach.profintel-metrics'
import { Route as OutreachProfintelRouteImport } from './routes/outreach.profintel'
import { Route as OutreachParentGroupsRouteImport } from './routes/outreach.parent-groups'
import { Route as OutreachOrdersRouteImport } from './routes/outreach.orders'
import { Route as OutreachLeadfinderLeaderboardRouteImport } from './routes/outreach.leadfinder-leaderboard'
import { Route as OutreachLeadfinderBatchRouteImport } from './routes/outreach.leadfinder-batch'
import { Route as OutreachLandingRouteImport } from './routes/outreach.landing'
import { Route as OutreachGreekOrgsRouteImport } from './routes/outreach.greek-orgs'
import { Route as OutreachCampusesRouteImport } from './routes/outreach.campuses'
import { Route as OutreachCampaignTargetsRouteImport } from './routes/outreach.campaign-targets'
import { Route as OutreachCampaignMetricsRouteImport } from './routes/outreach.campaign-metrics'
import { Route as OutreachBackupsRouteImport } from './routes/outreach.backups'
import { Route as OutreachActiveRosterRouteImport } from './routes/outreach.active-roster'
import { Route as OrderShortRefRouteImport } from './routes/order.$shortRef'
import { Route as OShortRefRouteImport } from './routes/o.$shortRef'
import { Route as JeSplatRouteImport } from './routes/je.$'
import { Route as CeqCreateRouteImport } from './routes/ceq.create'
import { Route as OutreachLeadfinderIndexRouteImport } from './routes/outreach.leadfinder.index'
import { Route as StudyScenariosSlugRouteImport } from './routes/study_.scenarios.$slug'
import { Route as OutreachSchoolSlugRouteImport } from './routes/outreach_.school.$slug'
import { Route as OutreachLeadfinderCampusIdRouteImport } from './routes/outreach.leadfinder.$campusId'
import { Route as OutreachGreekOrgsVendorQueueRouteImport } from './routes/outreach.greek-orgs_.vendor-queue'
import { Route as OutreachGreekOrgsQueueRouteImport } from './routes/outreach.greek-orgs_.queue'
import { Route as OutreachGreekOrgsPeopleQueueRouteImport } from './routes/outreach.greek-orgs_.people-queue'
import { Route as CeqIdTutorRouteImport } from './routes/ceq.$id.tutor'
import { Route as CeqIdEditRouteImport } from './routes/ceq.$id.edit'
import { Route as CeqCourseSlugChapterSlugRouteImport } from './routes/ceq.$courseSlug.$chapterSlug'
import { Route as ApiCronWeeklyDigestRouteImport } from './routes/api.cron.weekly-digest'
import { Route as ApiCronBackupRouteImport } from './routes/api.cron.backup'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankyouRoute = ThankyouRouteImport.update({
  id: '/thankyou',
  path: '/thankyou',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const OutreachRoute = OutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const JeRoute = JeRouteImport.update({
  id: '/je',
  path: '/je',
  getParentRoute: () => rootRouteImport,
} as any)
const CeqRoute = CeqRouteImport.update({
  id: '/ceq',
  path: '/ceq',
  getParentRoute: () => rootRouteImport,
} as any)
const BeyondRoute = BeyondRouteImport.update({
  id: '/beyond',
  path: '/beyond',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OutreachIndexRoute = OutreachIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OutreachRoute,
} as any)
const TSlugRoute = TSlugRouteImport.update({
  id: '/t/$slug',
  path: '/t/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyFoundationsRoute = StudyFoundationsRouteImport.update({
  id: '/study_/foundations',
  path: '/study/foundations',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyDashboardRoute = StudyDashboardRouteImport.update({
  id: '/study_/dashboard',
  path: '/study/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyCanvasRoute = StudyCanvasRouteImport.update({
  id: '/study_/canvas',
  path: '/study/canvas',
  getParentRoute: () => rootRouteImport,
} as any)
const OutreachVideoArchiveRoute = OutreachVideoArchiveRouteImport.update({
  id: '/video-archive',
  path: '/video-archive',
  getParentRoute: () => OutreachRoute,
} as any)
const OutreachStudentsRoute = OutreachStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => OutreachRoute,
} as any)
const OutreachResearchRoute = OutreachResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => OutreachRoute,
} as any)
const OutreachRedditRoute = OutreachRedditRouteImport.update({
  id: '/reddit',
  path: '/reddit',
  getParentRoute: () => OutreachRoute,
} as any)
const OutreachProfintelScheduleRoute =
  OutreachProfintelScheduleRouteImport.update({
    id: '/profintel-schedule',
    path: '/profintel-schedule',
    getParentRoute: () => OutreachRoute,
  } as any)
const OutreachProfintelMetricsRoute =
  OutreachProfintelMetricsRouteImport.update({
    id: '/profintel-metrics',
    path: '/profintel-metrics',
    getParentRoute: () => OutreachRoute,
  } as any)
const OutreachProfintelRoute = OutreachProfintelRouteImport.update({
  id: '/profintel',
  path: '/profintel',
  getParentRoute: () => OutreachRoute,
} as any)
const OutreachParentGroupsRoute = OutreachParentGroupsRouteImport.update({
  id: '/parent-groups',
  path: '/parent-groups',
  getParentRoute: () => OutreachRoute,
} as any)
const OutreachOrdersRoute = OutreachOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => OutreachRoute,
} as any)
const OutreachLeadfinderLeaderboardRoute =
  OutreachLeadfinderLeaderboardRouteImport.update({
    id: '/leadfinder-leaderboard',
    path: '/leadfinder-leaderboard',
    getParentRoute: () => OutreachRoute,
  } as any)
const OutreachLeadfinderBatchRoute = OutreachLeadfinderBatchRouteImport.update({
  id: '/leadfinder-batch',
  path: '/leadfinder-batch',
  getParentRoute: () => OutreachRoute,
} as any)
const OutreachLandingRoute = OutreachLandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => OutreachRoute,
} as any)
const OutreachGreekOrgsRoute = OutreachGreekOrgsRouteImport.update({
  id: '/greek-orgs',
  path: '/greek-orgs',
  getParentRoute: () => OutreachRoute,
} as any)
const OutreachCampusesRoute = OutreachCampusesRouteImport.update({
  id: '/campuses',
  path: '/campuses',
  getParentRoute: () => OutreachRoute,
} as any)
const OutreachCampaignTargetsRoute = OutreachCampaignTargetsRouteImport.update({
  id: '/campaign-targets',
  path: '/campaign-targets',
  getParentRoute: () => OutreachRoute,
} as any)
const OutreachCampaignMetricsRoute = OutreachCampaignMetricsRouteImport.update({
  id: '/campaign-metrics',
  path: '/campaign-metrics',
  getParentRoute: () => OutreachRoute,
} as any)
const OutreachBackupsRoute = OutreachBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => OutreachRoute,
} as any)
const OutreachActiveRosterRoute = OutreachActiveRosterRouteImport.update({
  id: '/active-roster',
  path: '/active-roster',
  getParentRoute: () => OutreachRoute,
} as any)
const OrderShortRefRoute = OrderShortRefRouteImport.update({
  id: '/$shortRef',
  path: '/$shortRef',
  getParentRoute: () => OrderRoute,
} as any)
const OShortRefRoute = OShortRefRouteImport.update({
  id: '/o/$shortRef',
  path: '/o/$shortRef',
  getParentRoute: () => rootRouteImport,
} as any)
const JeSplatRoute = JeSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => JeRoute,
} as any)
const CeqCreateRoute = CeqCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => CeqRoute,
} as any)
const OutreachLeadfinderIndexRoute = OutreachLeadfinderIndexRouteImport.update({
  id: '/leadfinder/',
  path: '/leadfinder/',
  getParentRoute: () => OutreachRoute,
} as any)
const StudyScenariosSlugRoute = StudyScenariosSlugRouteImport.update({
  id: '/study_/scenarios/$slug',
  path: '/study/scenarios/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OutreachSchoolSlugRoute = OutreachSchoolSlugRouteImport.update({
  id: '/outreach_/school/$slug',
  path: '/outreach/school/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OutreachLeadfinderCampusIdRoute =
  OutreachLeadfinderCampusIdRouteImport.update({
    id: '/leadfinder/$campusId',
    path: '/leadfinder/$campusId',
    getParentRoute: () => OutreachRoute,
  } as any)
const OutreachGreekOrgsVendorQueueRoute =
  OutreachGreekOrgsVendorQueueRouteImport.update({
    id: '/greek-orgs_/vendor-queue',
    path: '/greek-orgs/vendor-queue',
    getParentRoute: () => OutreachRoute,
  } as any)
const OutreachGreekOrgsQueueRoute = OutreachGreekOrgsQueueRouteImport.update({
  id: '/greek-orgs_/queue',
  path: '/greek-orgs/queue',
  getParentRoute: () => OutreachRoute,
} as any)
const OutreachGreekOrgsPeopleQueueRoute =
  OutreachGreekOrgsPeopleQueueRouteImport.update({
    id: '/greek-orgs_/people-queue',
    path: '/greek-orgs/people-queue',
    getParentRoute: () => OutreachRoute,
  } as any)
const CeqIdTutorRoute = CeqIdTutorRouteImport.update({
  id: '/$id/tutor',
  path: '/$id/tutor',
  getParentRoute: () => CeqRoute,
} as any)
const CeqIdEditRoute = CeqIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => CeqRoute,
} as any)
const CeqCourseSlugChapterSlugRoute =
  CeqCourseSlugChapterSlugRouteImport.update({
    id: '/$courseSlug/$chapterSlug',
    path: '/$courseSlug/$chapterSlug',
    getParentRoute: () => CeqRoute,
  } as any)
const ApiCronWeeklyDigestRoute = ApiCronWeeklyDigestRouteImport.update({
  id: '/api/cron/weekly-digest',
  path: '/api/cron/weekly-digest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronBackupRoute = ApiCronBackupRouteImport.update({
  id: '/api/cron/backup',
  path: '/api/cron/backup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/beyond': typeof BeyondRoute
  '/ceq': typeof CeqRouteWithChildren
  '/je': typeof JeRouteWithChildren
  '/onboard': typeof OnboardRoute
  '/order': typeof OrderRouteWithChildren
  '/outreach': typeof OutreachRouteWithChildren
  '/preview': typeof PreviewRoute
  '/privacy': typeof PrivacyRoute
  '/start': typeof StartRoute
  '/study': typeof StudyRoute
  '/terms': typeof TermsRoute
  '/thankyou': typeof ThankyouRoute
  '/welcome': typeof WelcomeRoute
  '/ceq/create': typeof CeqCreateRoute
  '/je/$': typeof JeSplatRoute
  '/o/$shortRef': typeof OShortRefRoute
  '/order/$shortRef': typeof OrderShortRefRoute
  '/outreach/active-roster': typeof OutreachActiveRosterRoute
  '/outreach/backups': typeof OutreachBackupsRoute
  '/outreach/campaign-metrics': typeof OutreachCampaignMetricsRoute
  '/outreach/campaign-targets': typeof OutreachCampaignTargetsRoute
  '/outreach/campuses': typeof OutreachCampusesRoute
  '/outreach/greek-orgs': typeof OutreachGreekOrgsRoute
  '/outreach/landing': typeof OutreachLandingRoute
  '/outreach/leadfinder-batch': typeof OutreachLeadfinderBatchRoute
  '/outreach/leadfinder-leaderboard': typeof OutreachLeadfinderLeaderboardRoute
  '/outreach/orders': typeof OutreachOrdersRoute
  '/outreach/parent-groups': typeof OutreachParentGroupsRoute
  '/outreach/profintel': typeof OutreachProfintelRoute
  '/outreach/profintel-metrics': typeof OutreachProfintelMetricsRoute
  '/outreach/profintel-schedule': typeof OutreachProfintelScheduleRoute
  '/outreach/reddit': typeof OutreachRedditRoute
  '/outreach/research': typeof OutreachResearchRoute
  '/outreach/students': typeof OutreachStudentsRoute
  '/outreach/video-archive': typeof OutreachVideoArchiveRoute
  '/study/canvas': typeof StudyCanvasRoute
  '/study/dashboard': typeof StudyDashboardRoute
  '/study/foundations': typeof StudyFoundationsRoute
  '/t/$slug': typeof TSlugRoute
  '/outreach/': typeof OutreachIndexRoute
  '/api/cron/backup': typeof ApiCronBackupRoute
  '/api/cron/weekly-digest': typeof ApiCronWeeklyDigestRoute
  '/ceq/$courseSlug/$chapterSlug': typeof CeqCourseSlugChapterSlugRoute
  '/ceq/$id/edit': typeof CeqIdEditRoute
  '/ceq/$id/tutor': typeof CeqIdTutorRoute
  '/outreach/greek-orgs/people-queue': typeof OutreachGreekOrgsPeopleQueueRoute
  '/outreach/greek-orgs/queue': typeof OutreachGreekOrgsQueueRoute
  '/outreach/greek-orgs/vendor-queue': typeof OutreachGreekOrgsVendorQueueRoute
  '/outreach/leadfinder/$campusId': typeof OutreachLeadfinderCampusIdRoute
  '/outreach/school/$slug': typeof OutreachSchoolSlugRoute
  '/study/scenarios/$slug': typeof StudyScenariosSlugRoute
  '/outreach/leadfinder/': typeof OutreachLeadfinderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beyond': typeof BeyondRoute
  '/ceq': typeof CeqRouteWithChildren
  '/je': typeof JeRouteWithChildren
  '/onboard': typeof OnboardRoute
  '/order': typeof OrderRouteWithChildren
  '/preview': typeof PreviewRoute
  '/privacy': typeof PrivacyRoute
  '/start': typeof StartRoute
  '/study': typeof StudyRoute
  '/terms': typeof TermsRoute
  '/thankyou': typeof ThankyouRoute
  '/welcome': typeof WelcomeRoute
  '/ceq/create': typeof CeqCreateRoute
  '/je/$': typeof JeSplatRoute
  '/o/$shortRef': typeof OShortRefRoute
  '/order/$shortRef': typeof OrderShortRefRoute
  '/outreach/active-roster': typeof OutreachActiveRosterRoute
  '/outreach/backups': typeof OutreachBackupsRoute
  '/outreach/campaign-metrics': typeof OutreachCampaignMetricsRoute
  '/outreach/campaign-targets': typeof OutreachCampaignTargetsRoute
  '/outreach/campuses': typeof OutreachCampusesRoute
  '/outreach/greek-orgs': typeof OutreachGreekOrgsRoute
  '/outreach/landing': typeof OutreachLandingRoute
  '/outreach/leadfinder-batch': typeof OutreachLeadfinderBatchRoute
  '/outreach/leadfinder-leaderboard': typeof OutreachLeadfinderLeaderboardRoute
  '/outreach/orders': typeof OutreachOrdersRoute
  '/outreach/parent-groups': typeof OutreachParentGroupsRoute
  '/outreach/profintel': typeof OutreachProfintelRoute
  '/outreach/profintel-metrics': typeof OutreachProfintelMetricsRoute
  '/outreach/profintel-schedule': typeof OutreachProfintelScheduleRoute
  '/outreach/reddit': typeof OutreachRedditRoute
  '/outreach/research': typeof OutreachResearchRoute
  '/outreach/students': typeof OutreachStudentsRoute
  '/outreach/video-archive': typeof OutreachVideoArchiveRoute
  '/study/canvas': typeof StudyCanvasRoute
  '/study/dashboard': typeof StudyDashboardRoute
  '/study/foundations': typeof StudyFoundationsRoute
  '/t/$slug': typeof TSlugRoute
  '/outreach': typeof OutreachIndexRoute
  '/api/cron/backup': typeof ApiCronBackupRoute
  '/api/cron/weekly-digest': typeof ApiCronWeeklyDigestRoute
  '/ceq/$courseSlug/$chapterSlug': typeof CeqCourseSlugChapterSlugRoute
  '/ceq/$id/edit': typeof CeqIdEditRoute
  '/ceq/$id/tutor': typeof CeqIdTutorRoute
  '/outreach/greek-orgs/people-queue': typeof OutreachGreekOrgsPeopleQueueRoute
  '/outreach/greek-orgs/queue': typeof OutreachGreekOrgsQueueRoute
  '/outreach/greek-orgs/vendor-queue': typeof OutreachGreekOrgsVendorQueueRoute
  '/outreach/leadfinder/$campusId': typeof OutreachLeadfinderCampusIdRoute
  '/outreach/school/$slug': typeof OutreachSchoolSlugRoute
  '/study/scenarios/$slug': typeof StudyScenariosSlugRoute
  '/outreach/leadfinder': typeof OutreachLeadfinderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/beyond': typeof BeyondRoute
  '/ceq': typeof CeqRouteWithChildren
  '/je': typeof JeRouteWithChildren
  '/onboard': typeof OnboardRoute
  '/order': typeof OrderRouteWithChildren
  '/outreach': typeof OutreachRouteWithChildren
  '/preview': typeof PreviewRoute
  '/privacy': typeof PrivacyRoute
  '/start': typeof StartRoute
  '/study': typeof StudyRoute
  '/terms': typeof TermsRoute
  '/thankyou': typeof ThankyouRoute
  '/welcome': typeof WelcomeRoute
  '/ceq/create': typeof CeqCreateRoute
  '/je/$': typeof JeSplatRoute
  '/o/$shortRef': typeof OShortRefRoute
  '/order/$shortRef': typeof OrderShortRefRoute
  '/outreach/active-roster': typeof OutreachActiveRosterRoute
  '/outreach/backups': typeof OutreachBackupsRoute
  '/outreach/campaign-metrics': typeof OutreachCampaignMetricsRoute
  '/outreach/campaign-targets': typeof OutreachCampaignTargetsRoute
  '/outreach/campuses': typeof OutreachCampusesRoute
  '/outreach/greek-orgs': typeof OutreachGreekOrgsRoute
  '/outreach/landing': typeof OutreachLandingRoute
  '/outreach/leadfinder-batch': typeof OutreachLeadfinderBatchRoute
  '/outreach/leadfinder-leaderboard': typeof OutreachLeadfinderLeaderboardRoute
  '/outreach/orders': typeof OutreachOrdersRoute
  '/outreach/parent-groups': typeof OutreachParentGroupsRoute
  '/outreach/profintel': typeof OutreachProfintelRoute
  '/outreach/profintel-metrics': typeof OutreachProfintelMetricsRoute
  '/outreach/profintel-schedule': typeof OutreachProfintelScheduleRoute
  '/outreach/reddit': typeof OutreachRedditRoute
  '/outreach/research': typeof OutreachResearchRoute
  '/outreach/students': typeof OutreachStudentsRoute
  '/outreach/video-archive': typeof OutreachVideoArchiveRoute
  '/study_/canvas': typeof StudyCanvasRoute
  '/study_/dashboard': typeof StudyDashboardRoute
  '/study_/foundations': typeof StudyFoundationsRoute
  '/t/$slug': typeof TSlugRoute
  '/outreach/': typeof OutreachIndexRoute
  '/api/cron/backup': typeof ApiCronBackupRoute
  '/api/cron/weekly-digest': typeof ApiCronWeeklyDigestRoute
  '/ceq/$courseSlug/$chapterSlug': typeof CeqCourseSlugChapterSlugRoute
  '/ceq/$id/edit': typeof CeqIdEditRoute
  '/ceq/$id/tutor': typeof CeqIdTutorRoute
  '/outreach/greek-orgs_/people-queue': typeof OutreachGreekOrgsPeopleQueueRoute
  '/outreach/greek-orgs_/queue': typeof OutreachGreekOrgsQueueRoute
  '/outreach/greek-orgs_/vendor-queue': typeof OutreachGreekOrgsVendorQueueRoute
  '/outreach/leadfinder/$campusId': typeof OutreachLeadfinderCampusIdRoute
  '/outreach_/school/$slug': typeof OutreachSchoolSlugRoute
  '/study_/scenarios/$slug': typeof StudyScenariosSlugRoute
  '/outreach/leadfinder/': typeof OutreachLeadfinderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/beyond'
    | '/ceq'
    | '/je'
    | '/onboard'
    | '/order'
    | '/outreach'
    | '/preview'
    | '/privacy'
    | '/start'
    | '/study'
    | '/terms'
    | '/thankyou'
    | '/welcome'
    | '/ceq/create'
    | '/je/$'
    | '/o/$shortRef'
    | '/order/$shortRef'
    | '/outreach/active-roster'
    | '/outreach/backups'
    | '/outreach/campaign-metrics'
    | '/outreach/campaign-targets'
    | '/outreach/campuses'
    | '/outreach/greek-orgs'
    | '/outreach/landing'
    | '/outreach/leadfinder-batch'
    | '/outreach/leadfinder-leaderboard'
    | '/outreach/orders'
    | '/outreach/parent-groups'
    | '/outreach/profintel'
    | '/outreach/profintel-metrics'
    | '/outreach/profintel-schedule'
    | '/outreach/reddit'
    | '/outreach/research'
    | '/outreach/students'
    | '/outreach/video-archive'
    | '/study/canvas'
    | '/study/dashboard'
    | '/study/foundations'
    | '/t/$slug'
    | '/outreach/'
    | '/api/cron/backup'
    | '/api/cron/weekly-digest'
    | '/ceq/$courseSlug/$chapterSlug'
    | '/ceq/$id/edit'
    | '/ceq/$id/tutor'
    | '/outreach/greek-orgs/people-queue'
    | '/outreach/greek-orgs/queue'
    | '/outreach/greek-orgs/vendor-queue'
    | '/outreach/leadfinder/$campusId'
    | '/outreach/school/$slug'
    | '/study/scenarios/$slug'
    | '/outreach/leadfinder/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/beyond'
    | '/ceq'
    | '/je'
    | '/onboard'
    | '/order'
    | '/preview'
    | '/privacy'
    | '/start'
    | '/study'
    | '/terms'
    | '/thankyou'
    | '/welcome'
    | '/ceq/create'
    | '/je/$'
    | '/o/$shortRef'
    | '/order/$shortRef'
    | '/outreach/active-roster'
    | '/outreach/backups'
    | '/outreach/campaign-metrics'
    | '/outreach/campaign-targets'
    | '/outreach/campuses'
    | '/outreach/greek-orgs'
    | '/outreach/landing'
    | '/outreach/leadfinder-batch'
    | '/outreach/leadfinder-leaderboard'
    | '/outreach/orders'
    | '/outreach/parent-groups'
    | '/outreach/profintel'
    | '/outreach/profintel-metrics'
    | '/outreach/profintel-schedule'
    | '/outreach/reddit'
    | '/outreach/research'
    | '/outreach/students'
    | '/outreach/video-archive'
    | '/study/canvas'
    | '/study/dashboard'
    | '/study/foundations'
    | '/t/$slug'
    | '/outreach'
    | '/api/cron/backup'
    | '/api/cron/weekly-digest'
    | '/ceq/$courseSlug/$chapterSlug'
    | '/ceq/$id/edit'
    | '/ceq/$id/tutor'
    | '/outreach/greek-orgs/people-queue'
    | '/outreach/greek-orgs/queue'
    | '/outreach/greek-orgs/vendor-queue'
    | '/outreach/leadfinder/$campusId'
    | '/outreach/school/$slug'
    | '/study/scenarios/$slug'
    | '/outreach/leadfinder'
  id:
    | '__root__'
    | '/'
    | '/beyond'
    | '/ceq'
    | '/je'
    | '/onboard'
    | '/order'
    | '/outreach'
    | '/preview'
    | '/privacy'
    | '/start'
    | '/study'
    | '/terms'
    | '/thankyou'
    | '/welcome'
    | '/ceq/create'
    | '/je/$'
    | '/o/$shortRef'
    | '/order/$shortRef'
    | '/outreach/active-roster'
    | '/outreach/backups'
    | '/outreach/campaign-metrics'
    | '/outreach/campaign-targets'
    | '/outreach/campuses'
    | '/outreach/greek-orgs'
    | '/outreach/landing'
    | '/outreach/leadfinder-batch'
    | '/outreach/leadfinder-leaderboard'
    | '/outreach/orders'
    | '/outreach/parent-groups'
    | '/outreach/profintel'
    | '/outreach/profintel-metrics'
    | '/outreach/profintel-schedule'
    | '/outreach/reddit'
    | '/outreach/research'
    | '/outreach/students'
    | '/outreach/video-archive'
    | '/study_/canvas'
    | '/study_/dashboard'
    | '/study_/foundations'
    | '/t/$slug'
    | '/outreach/'
    | '/api/cron/backup'
    | '/api/cron/weekly-digest'
    | '/ceq/$courseSlug/$chapterSlug'
    | '/ceq/$id/edit'
    | '/ceq/$id/tutor'
    | '/outreach/greek-orgs_/people-queue'
    | '/outreach/greek-orgs_/queue'
    | '/outreach/greek-orgs_/vendor-queue'
    | '/outreach/leadfinder/$campusId'
    | '/outreach_/school/$slug'
    | '/study_/scenarios/$slug'
    | '/outreach/leadfinder/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BeyondRoute: typeof BeyondRoute
  CeqRoute: typeof CeqRouteWithChildren
  JeRoute: typeof JeRouteWithChildren
  OnboardRoute: typeof OnboardRoute
  OrderRoute: typeof OrderRouteWithChildren
  OutreachRoute: typeof OutreachRouteWithChildren
  PreviewRoute: typeof PreviewRoute
  PrivacyRoute: typeof PrivacyRoute
  StartRoute: typeof StartRoute
  StudyRoute: typeof StudyRoute
  TermsRoute: typeof TermsRoute
  ThankyouRoute: typeof ThankyouRoute
  WelcomeRoute: typeof WelcomeRoute
  OShortRefRoute: typeof OShortRefRoute
  StudyCanvasRoute: typeof StudyCanvasRoute
  StudyDashboardRoute: typeof StudyDashboardRoute
  StudyFoundationsRoute: typeof StudyFoundationsRoute
  TSlugRoute: typeof TSlugRoute
  ApiCronBackupRoute: typeof ApiCronBackupRoute
  ApiCronWeeklyDigestRoute: typeof ApiCronWeeklyDigestRoute
  OutreachSchoolSlugRoute: typeof OutreachSchoolSlugRoute
  StudyScenariosSlugRoute: typeof StudyScenariosSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thankyou': {
      id: '/thankyou'
      path: '/thankyou'
      fullPath: '/thankyou'
      preLoaderRoute: typeof ThankyouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outreach': {
      id: '/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof OutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/je': {
      id: '/je'
      path: '/je'
      fullPath: '/je'
      preLoaderRoute: typeof JeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ceq': {
      id: '/ceq'
      path: '/ceq'
      fullPath: '/ceq'
      preLoaderRoute: typeof CeqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beyond': {
      id: '/beyond'
      path: '/beyond'
      fullPath: '/beyond'
      preLoaderRoute: typeof BeyondRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outreach/': {
      id: '/outreach/'
      path: '/'
      fullPath: '/outreach/'
      preLoaderRoute: typeof OutreachIndexRouteImport
      parentRoute: typeof OutreachRoute
    }
    '/t/$slug': {
      id: '/t/$slug'
      path: '/t/$slug'
      fullPath: '/t/$slug'
      preLoaderRoute: typeof TSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study_/foundations': {
      id: '/study_/foundations'
      path: '/study/foundations'
      fullPath: '/study/foundations'
      preLoaderRoute: typeof StudyFoundationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study_/dashboard': {
      id: '/study_/dashboard'
      path: '/study/dashboard'
      fullPath: '/study/dashboard'
      preLoaderRoute: typeof StudyDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study_/canvas': {
      id: '/study_/canvas'
      path: '/study/canvas'
      fullPath: '/study/canvas'
      preLoaderRoute: typeof StudyCanvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outreach/video-archive': {
      id: '/outreach/video-archive'
      path: '/video-archive'
      fullPath: '/outreach/video-archive'
      preLoaderRoute: typeof OutreachVideoArchiveRouteImport
      parentRoute: typeof OutreachRoute
    }
    '/outreach/students': {
      id: '/outreach/students'
      path: '/students'
      fullPath: '/outreach/students'
      preLoaderRoute: typeof OutreachStudentsRouteImport
      parentRoute: typeof OutreachRoute
    }
    '/outreach/research': {
      id: '/outreach/research'
      path: '/research'
      fullPath: '/outreach/research'
      preLoaderRoute: typeof OutreachResearchRouteImport
      parentRoute: typeof OutreachRoute
    }
    '/outreach/reddit': {
      id: '/outreach/reddit'
      path: '/reddit'
      fullPath: '/outreach/reddit'
      preLoaderRoute: typeof OutreachRedditRouteImport
      parentRoute: typeof OutreachRoute
    }
    '/outreach/profintel-schedule': {
      id: '/outreach/profintel-schedule'
      path: '/profintel-schedule'
      fullPath: '/outreach/profintel-schedule'
      preLoaderRoute: typeof OutreachProfintelScheduleRouteImport
      parentRoute: typeof OutreachRoute
    }
    '/outreach/profintel-metrics': {
      id: '/outreach/profintel-metrics'
      path: '/profintel-metrics'
      fullPath: '/outreach/profintel-metrics'
      preLoaderRoute: typeof OutreachProfintelMetricsRouteImport
      parentRoute: typeof OutreachRoute
    }
    '/outreach/profintel': {
      id: '/outreach/profintel'
      path: '/profintel'
      fullPath: '/outreach/profintel'
      preLoaderRoute: typeof OutreachProfintelRouteImport
      parentRoute: typeof OutreachRoute
    }
    '/outreach/parent-groups': {
      id: '/outreach/parent-groups'
      path: '/parent-groups'
      fullPath: '/outreach/parent-groups'
      preLoaderRoute: typeof OutreachParentGroupsRouteImport
      parentRoute: typeof OutreachRoute
    }
    '/outreach/orders': {
      id: '/outreach/orders'
      path: '/orders'
      fullPath: '/outreach/orders'
      preLoaderRoute: typeof OutreachOrdersRouteImport
      parentRoute: typeof OutreachRoute
    }
    '/outreach/leadfinder-leaderboard': {
      id: '/outreach/leadfinder-leaderboard'
      path: '/leadfinder-leaderboard'
      fullPath: '/outreach/leadfinder-leaderboard'
      preLoaderRoute: typeof OutreachLeadfinderLeaderboardRouteImport
      parentRoute: typeof OutreachRoute
    }
    '/outreach/leadfinder-batch': {
      id: '/outreach/leadfinder-batch'
      path: '/leadfinder-batch'
      fullPath: '/outreach/leadfinder-batch'
      preLoaderRoute: typeof OutreachLeadfinderBatchRouteImport
      parentRoute: typeof OutreachRoute
    }
    '/outreach/landing': {
      id: '/outreach/landing'
      path: '/landing'
      fullPath: '/outreach/landing'
      preLoaderRoute: typeof OutreachLandingRouteImport
      parentRoute: typeof OutreachRoute
    }
    '/outreach/greek-orgs': {
      id: '/outreach/greek-orgs'
      path: '/greek-orgs'
      fullPath: '/outreach/greek-orgs'
      preLoaderRoute: typeof OutreachGreekOrgsRouteImport
      parentRoute: typeof OutreachRoute
    }
    '/outreach/campuses': {
      id: '/outreach/campuses'
      path: '/campuses'
      fullPath: '/outreach/campuses'
      preLoaderRoute: typeof OutreachCampusesRouteImport
      parentRoute: typeof OutreachRoute
    }
    '/outreach/campaign-targets': {
      id: '/outreach/campaign-targets'
      path: '/campaign-targets'
      fullPath: '/outreach/campaign-targets'
      preLoaderRoute: typeof OutreachCampaignTargetsRouteImport
      parentRoute: typeof OutreachRoute
    }
    '/outreach/campaign-metrics': {
      id: '/outreach/campaign-metrics'
      path: '/campaign-metrics'
      fullPath: '/outreach/campaign-metrics'
      preLoaderRoute: typeof OutreachCampaignMetricsRouteImport
      parentRoute: typeof OutreachRoute
    }
    '/outreach/backups': {
      id: '/outreach/backups'
      path: '/backups'
      fullPath: '/outreach/backups'
      preLoaderRoute: typeof OutreachBackupsRouteImport
      parentRoute: typeof OutreachRoute
    }
    '/outreach/active-roster': {
      id: '/outreach/active-roster'
      path: '/active-roster'
      fullPath: '/outreach/active-roster'
      preLoaderRoute: typeof OutreachActiveRosterRouteImport
      parentRoute: typeof OutreachRoute
    }
    '/order/$shortRef': {
      id: '/order/$shortRef'
      path: '/$shortRef'
      fullPath: '/order/$shortRef'
      preLoaderRoute: typeof OrderShortRefRouteImport
      parentRoute: typeof OrderRoute
    }
    '/o/$shortRef': {
      id: '/o/$shortRef'
      path: '/o/$shortRef'
      fullPath: '/o/$shortRef'
      preLoaderRoute: typeof OShortRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/je/$': {
      id: '/je/$'
      path: '/$'
      fullPath: '/je/$'
      preLoaderRoute: typeof JeSplatRouteImport
      parentRoute: typeof JeRoute
    }
    '/ceq/create': {
      id: '/ceq/create'
      path: '/create'
      fullPath: '/ceq/create'
      preLoaderRoute: typeof CeqCreateRouteImport
      parentRoute: typeof CeqRoute
    }
    '/outreach/leadfinder/': {
      id: '/outreach/leadfinder/'
      path: '/leadfinder'
      fullPath: '/outreach/leadfinder/'
      preLoaderRoute: typeof OutreachLeadfinderIndexRouteImport
      parentRoute: typeof OutreachRoute
    }
    '/study_/scenarios/$slug': {
      id: '/study_/scenarios/$slug'
      path: '/study/scenarios/$slug'
      fullPath: '/study/scenarios/$slug'
      preLoaderRoute: typeof StudyScenariosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outreach_/school/$slug': {
      id: '/outreach_/school/$slug'
      path: '/outreach/school/$slug'
      fullPath: '/outreach/school/$slug'
      preLoaderRoute: typeof OutreachSchoolSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outreach/leadfinder/$campusId': {
      id: '/outreach/leadfinder/$campusId'
      path: '/leadfinder/$campusId'
      fullPath: '/outreach/leadfinder/$campusId'
      preLoaderRoute: typeof OutreachLeadfinderCampusIdRouteImport
      parentRoute: typeof OutreachRoute
    }
    '/outreach/greek-orgs_/vendor-queue': {
      id: '/outreach/greek-orgs_/vendor-queue'
      path: '/greek-orgs/vendor-queue'
      fullPath: '/outreach/greek-orgs/vendor-queue'
      preLoaderRoute: typeof OutreachGreekOrgsVendorQueueRouteImport
      parentRoute: typeof OutreachRoute
    }
    '/outreach/greek-orgs_/queue': {
      id: '/outreach/greek-orgs_/queue'
      path: '/greek-orgs/queue'
      fullPath: '/outreach/greek-orgs/queue'
      preLoaderRoute: typeof OutreachGreekOrgsQueueRouteImport
      parentRoute: typeof OutreachRoute
    }
    '/outreach/greek-orgs_/people-queue': {
      id: '/outreach/greek-orgs_/people-queue'
      path: '/greek-orgs/people-queue'
      fullPath: '/outreach/greek-orgs/people-queue'
      preLoaderRoute: typeof OutreachGreekOrgsPeopleQueueRouteImport
      parentRoute: typeof OutreachRoute
    }
    '/ceq/$id/tutor': {
      id: '/ceq/$id/tutor'
      path: '/$id/tutor'
      fullPath: '/ceq/$id/tutor'
      preLoaderRoute: typeof CeqIdTutorRouteImport
      parentRoute: typeof CeqRoute
    }
    '/ceq/$id/edit': {
      id: '/ceq/$id/edit'
      path: '/$id/edit'
      fullPath: '/ceq/$id/edit'
      preLoaderRoute: typeof CeqIdEditRouteImport
      parentRoute: typeof CeqRoute
    }
    '/ceq/$courseSlug/$chapterSlug': {
      id: '/ceq/$courseSlug/$chapterSlug'
      path: '/$courseSlug/$chapterSlug'
      fullPath: '/ceq/$courseSlug/$chapterSlug'
      preLoaderRoute: typeof CeqCourseSlugChapterSlugRouteImport
      parentRoute: typeof CeqRoute
    }
    '/api/cron/weekly-digest': {
      id: '/api/cron/weekly-digest'
      path: '/api/cron/weekly-digest'
      fullPath: '/api/cron/weekly-digest'
      preLoaderRoute: typeof ApiCronWeeklyDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/backup': {
      id: '/api/cron/backup'
      path: '/api/cron/backup'
      fullPath: '/api/cron/backup'
      preLoaderRoute: typeof ApiCronBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CeqRouteChildren {
  CeqCreateRoute: typeof CeqCreateRoute
  CeqCourseSlugChapterSlugRoute: typeof CeqCourseSlugChapterSlugRoute
  CeqIdEditRoute: typeof CeqIdEditRoute
  CeqIdTutorRoute: typeof CeqIdTutorRoute
}

const CeqRouteChildren: CeqRouteChildren = {
  CeqCreateRoute: CeqCreateRoute,
  CeqCourseSlugChapterSlugRoute: CeqCourseSlugChapterSlugRoute,
  CeqIdEditRoute: CeqIdEditRoute,
  CeqIdTutorRoute: CeqIdTutorRoute,
}

const CeqRouteWithChildren = CeqRoute._addFileChildren(CeqRouteChildren)

interface JeRouteChildren {
  JeSplatRoute: typeof JeSplatRoute
}

const JeRouteChildren: JeRouteChildren = {
  JeSplatRoute: JeSplatRoute,
}

const JeRouteWithChildren = JeRoute._addFileChildren(JeRouteChildren)

interface OrderRouteChildren {
  OrderShortRefRoute: typeof OrderShortRefRoute
}

const OrderRouteChildren: OrderRouteChildren = {
  OrderShortRefRoute: OrderShortRefRoute,
}

const OrderRouteWithChildren = OrderRoute._addFileChildren(OrderRouteChildren)

interface OutreachRouteChildren {
  OutreachActiveRosterRoute: typeof OutreachActiveRosterRoute
  OutreachBackupsRoute: typeof OutreachBackupsRoute
  OutreachCampaignMetricsRoute: typeof OutreachCampaignMetricsRoute
  OutreachCampaignTargetsRoute: typeof OutreachCampaignTargetsRoute
  OutreachCampusesRoute: typeof OutreachCampusesRoute
  OutreachGreekOrgsRoute: typeof OutreachGreekOrgsRoute
  OutreachLandingRoute: typeof OutreachLandingRoute
  OutreachLeadfinderBatchRoute: typeof OutreachLeadfinderBatchRoute
  OutreachLeadfinderLeaderboardRoute: typeof OutreachLeadfinderLeaderboardRoute
  OutreachOrdersRoute: typeof OutreachOrdersRoute
  OutreachParentGroupsRoute: typeof OutreachParentGroupsRoute
  OutreachProfintelRoute: typeof OutreachProfintelRoute
  OutreachProfintelMetricsRoute: typeof OutreachProfintelMetricsRoute
  OutreachProfintelScheduleRoute: typeof OutreachProfintelScheduleRoute
  OutreachRedditRoute: typeof OutreachRedditRoute
  OutreachResearchRoute: typeof OutreachResearchRoute
  OutreachStudentsRoute: typeof OutreachStudentsRoute
  OutreachVideoArchiveRoute: typeof OutreachVideoArchiveRoute
  OutreachIndexRoute: typeof OutreachIndexRoute
  OutreachGreekOrgsPeopleQueueRoute: typeof OutreachGreekOrgsPeopleQueueRoute
  OutreachGreekOrgsQueueRoute: typeof OutreachGreekOrgsQueueRoute
  OutreachGreekOrgsVendorQueueRoute: typeof OutreachGreekOrgsVendorQueueRoute
  OutreachLeadfinderCampusIdRoute: typeof OutreachLeadfinderCampusIdRoute
  OutreachLeadfinderIndexRoute: typeof OutreachLeadfinderIndexRoute
}

const OutreachRouteChildren: OutreachRouteChildren = {
  OutreachActiveRosterRoute: OutreachActiveRosterRoute,
  OutreachBackupsRoute: OutreachBackupsRoute,
  OutreachCampaignMetricsRoute: OutreachCampaignMetricsRoute,
  OutreachCampaignTargetsRoute: OutreachCampaignTargetsRoute,
  OutreachCampusesRoute: OutreachCampusesRoute,
  OutreachGreekOrgsRoute: OutreachGreekOrgsRoute,
  OutreachLandingRoute: OutreachLandingRoute,
  OutreachLeadfinderBatchRoute: OutreachLeadfinderBatchRoute,
  OutreachLeadfinderLeaderboardRoute: OutreachLeadfinderLeaderboardRoute,
  OutreachOrdersRoute: OutreachOrdersRoute,
  OutreachParentGroupsRoute: OutreachParentGroupsRoute,
  OutreachProfintelRoute: OutreachProfintelRoute,
  OutreachProfintelMetricsRoute: OutreachProfintelMetricsRoute,
  OutreachProfintelScheduleRoute: OutreachProfintelScheduleRoute,
  OutreachRedditRoute: OutreachRedditRoute,
  OutreachResearchRoute: OutreachResearchRoute,
  OutreachStudentsRoute: OutreachStudentsRoute,
  OutreachVideoArchiveRoute: OutreachVideoArchiveRoute,
  OutreachIndexRoute: OutreachIndexRoute,
  OutreachGreekOrgsPeopleQueueRoute: OutreachGreekOrgsPeopleQueueRoute,
  OutreachGreekOrgsQueueRoute: OutreachGreekOrgsQueueRoute,
  OutreachGreekOrgsVendorQueueRoute: OutreachGreekOrgsVendorQueueRoute,
  OutreachLeadfinderCampusIdRoute: OutreachLeadfinderCampusIdRoute,
  OutreachLeadfinderIndexRoute: OutreachLeadfinderIndexRoute,
}

const OutreachRouteWithChildren = OutreachRoute._addFileChildren(
  OutreachRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BeyondRoute: BeyondRoute,
  CeqRoute: CeqRouteWithChildren,
  JeRoute: JeRouteWithChildren,
  OnboardRoute: OnboardRoute,
  OrderRoute: OrderRouteWithChildren,
  OutreachRoute: OutreachRouteWithChildren,
  PreviewRoute: PreviewRoute,
  PrivacyRoute: PrivacyRoute,
  StartRoute: StartRoute,
  StudyRoute: StudyRoute,
  TermsRoute: TermsRoute,
  ThankyouRoute: ThankyouRoute,
  WelcomeRoute: WelcomeRoute,
  OShortRefRoute: OShortRefRoute,
  StudyCanvasRoute: StudyCanvasRoute,
  StudyDashboardRoute: StudyDashboardRoute,
  StudyFoundationsRoute: StudyFoundationsRoute,
  TSlugRoute: TSlugRoute,
  ApiCronBackupRoute: ApiCronBackupRoute,
  ApiCronWeeklyDigestRoute: ApiCronWeeklyDigestRoute,
  OutreachSchoolSlugRoute: OutreachSchoolSlugRoute,
  StudyScenariosSlugRoute: StudyScenariosSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
