/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as ThankyouRouteImport } from './routes/thankyou'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StartRouteImport } from './routes/start'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as OutreachRouteImport } from './routes/outreach'
import { Route as OrderRouteImport } from './routes/order'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as JeRouteImport } from './routes/je'
import { Route as CeqRouteImport } from './routes/ceq'
import { Route as BeyondRouteImport } from './routes/beyond'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OutreachIndexRouteImport } from './routes/outreach.index'
import { Route as TSlugRouteImport } from './routes/t.$slug'
import { Route as OutreachStudentsRouteImport } from './routes/outreach.students'
import { Route as OutreachResearchRouteImport } from './routes/outreach.research'
import { Route as OutreachProfintelScheduleRouteImport } from './routes/outreach.profintel-schedule'
import { Route as OutreachProfintelRouteImport } from './routes/outreach.profintel'
import { Route as OutreachOrdersRouteImport } from './routes/outreach.orders'
import { Route as OutreachLeadfinderLeaderboardRouteImport } from './routes/outreach.leadfinder-leaderboard'
import { Route as OutreachLeadfinderBatchRouteImport } from './routes/outreach.leadfinder-batch'
import { Route as OutreachLandingRouteImport } from './routes/outreach.landing'
import { Route as OutreachCampusesRouteImport } from './routes/outreach.campuses'
import { Route as OutreachCampaignTargetsRouteImport } from './routes/outreach.campaign-targets'
import { Route as OutreachCampaignMetricsRouteImport } from './routes/outreach.campaign-metrics'
import { Route as OrderShortRefRouteImport } from './routes/order.$shortRef'
import { Route as OShortRefRouteImport } from './routes/o.$shortRef'
import { Route as CeqCreateRouteImport } from './routes/ceq.create'
import { Route as OutreachLeadfinderIndexRouteImport } from './routes/outreach.leadfinder.index'
import { Route as OutreachSchoolSlugRouteImport } from './routes/outreach_.school.$slug'
import { Route as OutreachLeadfinderCampusIdRouteImport } from './routes/outreach.leadfinder.$campusId'
import { Route as CeqIdTutorRouteImport } from './routes/ceq.$id.tutor'
import { Route as CeqIdEditRouteImport } from './routes/ceq.$id.edit'
import { Route as CeqCourseSlugChapterSlugRouteImport } from './routes/ceq.$courseSlug.$chapterSlug'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankyouRoute = ThankyouRouteImport.update({
  id: '/thankyou',
  path: '/thankyou',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const OutreachRoute = OutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const JeRoute = JeRouteImport.update({
  id: '/je',
  path: '/je',
  getParentRoute: () => rootRouteImport,
} as any)
const CeqRoute = CeqRouteImport.update({
  id: '/ceq',
  path: '/ceq',
  getParentRoute: () => rootRouteImport,
} as any)
const BeyondRoute = BeyondRouteImport.update({
  id: '/beyond',
  path: '/beyond',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OutreachIndexRoute = OutreachIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OutreachRoute,
} as any)
const TSlugRoute = TSlugRouteImport.update({
  id: '/t/$slug',
  path: '/t/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OutreachStudentsRoute = OutreachStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => OutreachRoute,
} as any)
const OutreachResearchRoute = OutreachResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => OutreachRoute,
} as any)
const OutreachProfintelScheduleRoute =
  OutreachProfintelScheduleRouteImport.update({
    id: '/profintel-schedule',
    path: '/profintel-schedule',
    getParentRoute: () => OutreachRoute,
  } as any)
const OutreachProfintelRoute = OutreachProfintelRouteImport.update({
  id: '/profintel',
  path: '/profintel',
  getParentRoute: () => OutreachRoute,
} as any)
const OutreachOrdersRoute = OutreachOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => OutreachRoute,
} as any)
const OutreachLeadfinderLeaderboardRoute =
  OutreachLeadfinderLeaderboardRouteImport.update({
    id: '/leadfinder-leaderboard',
    path: '/leadfinder-leaderboard',
    getParentRoute: () => OutreachRoute,
  } as any)
const OutreachLeadfinderBatchRoute = OutreachLeadfinderBatchRouteImport.update({
  id: '/leadfinder-batch',
  path: '/leadfinder-batch',
  getParentRoute: () => OutreachRoute,
} as any)
const OutreachLandingRoute = OutreachLandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => OutreachRoute,
} as any)
const OutreachCampusesRoute = OutreachCampusesRouteImport.update({
  id: '/campuses',
  path: '/campuses',
  getParentRoute: () => OutreachRoute,
} as any)
const OutreachCampaignTargetsRoute = OutreachCampaignTargetsRouteImport.update({
  id: '/campaign-targets',
  path: '/campaign-targets',
  getParentRoute: () => OutreachRoute,
} as any)
const OutreachCampaignMetricsRoute = OutreachCampaignMetricsRouteImport.update({
  id: '/campaign-metrics',
  path: '/campaign-metrics',
  getParentRoute: () => OutreachRoute,
} as any)
const OrderShortRefRoute = OrderShortRefRouteImport.update({
  id: '/$shortRef',
  path: '/$shortRef',
  getParentRoute: () => OrderRoute,
} as any)
const OShortRefRoute = OShortRefRouteImport.update({
  id: '/o/$shortRef',
  path: '/o/$shortRef',
  getParentRoute: () => rootRouteImport,
} as any)
const CeqCreateRoute = CeqCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => CeqRoute,
} as any)
const OutreachLeadfinderIndexRoute = OutreachLeadfinderIndexRouteImport.update({
  id: '/leadfinder/',
  path: '/leadfinder/',
  getParentRoute: () => OutreachRoute,
} as any)
const OutreachSchoolSlugRoute = OutreachSchoolSlugRouteImport.update({
  id: '/outreach_/school/$slug',
  path: '/outreach/school/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OutreachLeadfinderCampusIdRoute =
  OutreachLeadfinderCampusIdRouteImport.update({
    id: '/leadfinder/$campusId',
    path: '/leadfinder/$campusId',
    getParentRoute: () => OutreachRoute,
  } as any)
const CeqIdTutorRoute = CeqIdTutorRouteImport.update({
  id: '/$id/tutor',
  path: '/$id/tutor',
  getParentRoute: () => CeqRoute,
} as any)
const CeqIdEditRoute = CeqIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => CeqRoute,
} as any)
const CeqCourseSlugChapterSlugRoute =
  CeqCourseSlugChapterSlugRouteImport.update({
    id: '/$courseSlug/$chapterSlug',
    path: '/$courseSlug/$chapterSlug',
    getParentRoute: () => CeqRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/beyond': typeof BeyondRoute
  '/ceq': typeof CeqRouteWithChildren
  '/je': typeof JeRoute
  '/onboard': typeof OnboardRoute
  '/order': typeof OrderRouteWithChildren
  '/outreach': typeof OutreachRouteWithChildren
  '/preview': typeof PreviewRoute
  '/privacy': typeof PrivacyRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/thankyou': typeof ThankyouRoute
  '/welcome': typeof WelcomeRoute
  '/ceq/create': typeof CeqCreateRoute
  '/o/$shortRef': typeof OShortRefRoute
  '/order/$shortRef': typeof OrderShortRefRoute
  '/outreach/campaign-metrics': typeof OutreachCampaignMetricsRoute
  '/outreach/campaign-targets': typeof OutreachCampaignTargetsRoute
  '/outreach/campuses': typeof OutreachCampusesRoute
  '/outreach/landing': typeof OutreachLandingRoute
  '/outreach/leadfinder-batch': typeof OutreachLeadfinderBatchRoute
  '/outreach/leadfinder-leaderboard': typeof OutreachLeadfinderLeaderboardRoute
  '/outreach/orders': typeof OutreachOrdersRoute
  '/outreach/profintel': typeof OutreachProfintelRoute
  '/outreach/profintel-schedule': typeof OutreachProfintelScheduleRoute
  '/outreach/research': typeof OutreachResearchRoute
  '/outreach/students': typeof OutreachStudentsRoute
  '/t/$slug': typeof TSlugRoute
  '/outreach/': typeof OutreachIndexRoute
  '/ceq/$courseSlug/$chapterSlug': typeof CeqCourseSlugChapterSlugRoute
  '/ceq/$id/edit': typeof CeqIdEditRoute
  '/ceq/$id/tutor': typeof CeqIdTutorRoute
  '/outreach/leadfinder/$campusId': typeof OutreachLeadfinderCampusIdRoute
  '/outreach/school/$slug': typeof OutreachSchoolSlugRoute
  '/outreach/leadfinder/': typeof OutreachLeadfinderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beyond': typeof BeyondRoute
  '/ceq': typeof CeqRouteWithChildren
  '/je': typeof JeRoute
  '/onboard': typeof OnboardRoute
  '/order': typeof OrderRouteWithChildren
  '/preview': typeof PreviewRoute
  '/privacy': typeof PrivacyRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/thankyou': typeof ThankyouRoute
  '/welcome': typeof WelcomeRoute
  '/ceq/create': typeof CeqCreateRoute
  '/o/$shortRef': typeof OShortRefRoute
  '/order/$shortRef': typeof OrderShortRefRoute
  '/outreach/campaign-metrics': typeof OutreachCampaignMetricsRoute
  '/outreach/campaign-targets': typeof OutreachCampaignTargetsRoute
  '/outreach/campuses': typeof OutreachCampusesRoute
  '/outreach/landing': typeof OutreachLandingRoute
  '/outreach/leadfinder-batch': typeof OutreachLeadfinderBatchRoute
  '/outreach/leadfinder-leaderboard': typeof OutreachLeadfinderLeaderboardRoute
  '/outreach/orders': typeof OutreachOrdersRoute
  '/outreach/profintel': typeof OutreachProfintelRoute
  '/outreach/profintel-schedule': typeof OutreachProfintelScheduleRoute
  '/outreach/research': typeof OutreachResearchRoute
  '/outreach/students': typeof OutreachStudentsRoute
  '/t/$slug': typeof TSlugRoute
  '/outreach': typeof OutreachIndexRoute
  '/ceq/$courseSlug/$chapterSlug': typeof CeqCourseSlugChapterSlugRoute
  '/ceq/$id/edit': typeof CeqIdEditRoute
  '/ceq/$id/tutor': typeof CeqIdTutorRoute
  '/outreach/leadfinder/$campusId': typeof OutreachLeadfinderCampusIdRoute
  '/outreach/school/$slug': typeof OutreachSchoolSlugRoute
  '/outreach/leadfinder': typeof OutreachLeadfinderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/beyond': typeof BeyondRoute
  '/ceq': typeof CeqRouteWithChildren
  '/je': typeof JeRoute
  '/onboard': typeof OnboardRoute
  '/order': typeof OrderRouteWithChildren
  '/outreach': typeof OutreachRouteWithChildren
  '/preview': typeof PreviewRoute
  '/privacy': typeof PrivacyRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/thankyou': typeof ThankyouRoute
  '/welcome': typeof WelcomeRoute
  '/ceq/create': typeof CeqCreateRoute
  '/o/$shortRef': typeof OShortRefRoute
  '/order/$shortRef': typeof OrderShortRefRoute
  '/outreach/campaign-metrics': typeof OutreachCampaignMetricsRoute
  '/outreach/campaign-targets': typeof OutreachCampaignTargetsRoute
  '/outreach/campuses': typeof OutreachCampusesRoute
  '/outreach/landing': typeof OutreachLandingRoute
  '/outreach/leadfinder-batch': typeof OutreachLeadfinderBatchRoute
  '/outreach/leadfinder-leaderboard': typeof OutreachLeadfinderLeaderboardRoute
  '/outreach/orders': typeof OutreachOrdersRoute
  '/outreach/profintel': typeof OutreachProfintelRoute
  '/outreach/profintel-schedule': typeof OutreachProfintelScheduleRoute
  '/outreach/research': typeof OutreachResearchRoute
  '/outreach/students': typeof OutreachStudentsRoute
  '/t/$slug': typeof TSlugRoute
  '/outreach/': typeof OutreachIndexRoute
  '/ceq/$courseSlug/$chapterSlug': typeof CeqCourseSlugChapterSlugRoute
  '/ceq/$id/edit': typeof CeqIdEditRoute
  '/ceq/$id/tutor': typeof CeqIdTutorRoute
  '/outreach/leadfinder/$campusId': typeof OutreachLeadfinderCampusIdRoute
  '/outreach_/school/$slug': typeof OutreachSchoolSlugRoute
  '/outreach/leadfinder/': typeof OutreachLeadfinderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/beyond'
    | '/ceq'
    | '/je'
    | '/onboard'
    | '/order'
    | '/outreach'
    | '/preview'
    | '/privacy'
    | '/start'
    | '/terms'
    | '/thankyou'
    | '/welcome'
    | '/ceq/create'
    | '/o/$shortRef'
    | '/order/$shortRef'
    | '/outreach/campaign-metrics'
    | '/outreach/campaign-targets'
    | '/outreach/campuses'
    | '/outreach/landing'
    | '/outreach/leadfinder-batch'
    | '/outreach/leadfinder-leaderboard'
    | '/outreach/orders'
    | '/outreach/profintel'
    | '/outreach/profintel-schedule'
    | '/outreach/research'
    | '/outreach/students'
    | '/t/$slug'
    | '/outreach/'
    | '/ceq/$courseSlug/$chapterSlug'
    | '/ceq/$id/edit'
    | '/ceq/$id/tutor'
    | '/outreach/leadfinder/$campusId'
    | '/outreach/school/$slug'
    | '/outreach/leadfinder/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/beyond'
    | '/ceq'
    | '/je'
    | '/onboard'
    | '/order'
    | '/preview'
    | '/privacy'
    | '/start'
    | '/terms'
    | '/thankyou'
    | '/welcome'
    | '/ceq/create'
    | '/o/$shortRef'
    | '/order/$shortRef'
    | '/outreach/campaign-metrics'
    | '/outreach/campaign-targets'
    | '/outreach/campuses'
    | '/outreach/landing'
    | '/outreach/leadfinder-batch'
    | '/outreach/leadfinder-leaderboard'
    | '/outreach/orders'
    | '/outreach/profintel'
    | '/outreach/profintel-schedule'
    | '/outreach/research'
    | '/outreach/students'
    | '/t/$slug'
    | '/outreach'
    | '/ceq/$courseSlug/$chapterSlug'
    | '/ceq/$id/edit'
    | '/ceq/$id/tutor'
    | '/outreach/leadfinder/$campusId'
    | '/outreach/school/$slug'
    | '/outreach/leadfinder'
  id:
    | '__root__'
    | '/'
    | '/beyond'
    | '/ceq'
    | '/je'
    | '/onboard'
    | '/order'
    | '/outreach'
    | '/preview'
    | '/privacy'
    | '/start'
    | '/terms'
    | '/thankyou'
    | '/welcome'
    | '/ceq/create'
    | '/o/$shortRef'
    | '/order/$shortRef'
    | '/outreach/campaign-metrics'
    | '/outreach/campaign-targets'
    | '/outreach/campuses'
    | '/outreach/landing'
    | '/outreach/leadfinder-batch'
    | '/outreach/leadfinder-leaderboard'
    | '/outreach/orders'
    | '/outreach/profintel'
    | '/outreach/profintel-schedule'
    | '/outreach/research'
    | '/outreach/students'
    | '/t/$slug'
    | '/outreach/'
    | '/ceq/$courseSlug/$chapterSlug'
    | '/ceq/$id/edit'
    | '/ceq/$id/tutor'
    | '/outreach/leadfinder/$campusId'
    | '/outreach_/school/$slug'
    | '/outreach/leadfinder/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BeyondRoute: typeof BeyondRoute
  CeqRoute: typeof CeqRouteWithChildren
  JeRoute: typeof JeRoute
  OnboardRoute: typeof OnboardRoute
  OrderRoute: typeof OrderRouteWithChildren
  OutreachRoute: typeof OutreachRouteWithChildren
  PreviewRoute: typeof PreviewRoute
  PrivacyRoute: typeof PrivacyRoute
  StartRoute: typeof StartRoute
  TermsRoute: typeof TermsRoute
  ThankyouRoute: typeof ThankyouRoute
  WelcomeRoute: typeof WelcomeRoute
  OShortRefRoute: typeof OShortRefRoute
  TSlugRoute: typeof TSlugRoute
  OutreachSchoolSlugRoute: typeof OutreachSchoolSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thankyou': {
      id: '/thankyou'
      path: '/thankyou'
      fullPath: '/thankyou'
      preLoaderRoute: typeof ThankyouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outreach': {
      id: '/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof OutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/je': {
      id: '/je'
      path: '/je'
      fullPath: '/je'
      preLoaderRoute: typeof JeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ceq': {
      id: '/ceq'
      path: '/ceq'
      fullPath: '/ceq'
      preLoaderRoute: typeof CeqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beyond': {
      id: '/beyond'
      path: '/beyond'
      fullPath: '/beyond'
      preLoaderRoute: typeof BeyondRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outreach/': {
      id: '/outreach/'
      path: '/'
      fullPath: '/outreach/'
      preLoaderRoute: typeof OutreachIndexRouteImport
      parentRoute: typeof OutreachRoute
    }
    '/t/$slug': {
      id: '/t/$slug'
      path: '/t/$slug'
      fullPath: '/t/$slug'
      preLoaderRoute: typeof TSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outreach/students': {
      id: '/outreach/students'
      path: '/students'
      fullPath: '/outreach/students'
      preLoaderRoute: typeof OutreachStudentsRouteImport
      parentRoute: typeof OutreachRoute
    }
    '/outreach/research': {
      id: '/outreach/research'
      path: '/research'
      fullPath: '/outreach/research'
      preLoaderRoute: typeof OutreachResearchRouteImport
      parentRoute: typeof OutreachRoute
    }
    '/outreach/profintel-schedule': {
      id: '/outreach/profintel-schedule'
      path: '/profintel-schedule'
      fullPath: '/outreach/profintel-schedule'
      preLoaderRoute: typeof OutreachProfintelScheduleRouteImport
      parentRoute: typeof OutreachRoute
    }
    '/outreach/profintel': {
      id: '/outreach/profintel'
      path: '/profintel'
      fullPath: '/outreach/profintel'
      preLoaderRoute: typeof OutreachProfintelRouteImport
      parentRoute: typeof OutreachRoute
    }
    '/outreach/orders': {
      id: '/outreach/orders'
      path: '/orders'
      fullPath: '/outreach/orders'
      preLoaderRoute: typeof OutreachOrdersRouteImport
      parentRoute: typeof OutreachRoute
    }
    '/outreach/leadfinder-leaderboard': {
      id: '/outreach/leadfinder-leaderboard'
      path: '/leadfinder-leaderboard'
      fullPath: '/outreach/leadfinder-leaderboard'
      preLoaderRoute: typeof OutreachLeadfinderLeaderboardRouteImport
      parentRoute: typeof OutreachRoute
    }
    '/outreach/leadfinder-batch': {
      id: '/outreach/leadfinder-batch'
      path: '/leadfinder-batch'
      fullPath: '/outreach/leadfinder-batch'
      preLoaderRoute: typeof OutreachLeadfinderBatchRouteImport
      parentRoute: typeof OutreachRoute
    }
    '/outreach/landing': {
      id: '/outreach/landing'
      path: '/landing'
      fullPath: '/outreach/landing'
      preLoaderRoute: typeof OutreachLandingRouteImport
      parentRoute: typeof OutreachRoute
    }
    '/outreach/campuses': {
      id: '/outreach/campuses'
      path: '/campuses'
      fullPath: '/outreach/campuses'
      preLoaderRoute: typeof OutreachCampusesRouteImport
      parentRoute: typeof OutreachRoute
    }
    '/outreach/campaign-targets': {
      id: '/outreach/campaign-targets'
      path: '/campaign-targets'
      fullPath: '/outreach/campaign-targets'
      preLoaderRoute: typeof OutreachCampaignTargetsRouteImport
      parentRoute: typeof OutreachRoute
    }
    '/outreach/campaign-metrics': {
      id: '/outreach/campaign-metrics'
      path: '/campaign-metrics'
      fullPath: '/outreach/campaign-metrics'
      preLoaderRoute: typeof OutreachCampaignMetricsRouteImport
      parentRoute: typeof OutreachRoute
    }
    '/order/$shortRef': {
      id: '/order/$shortRef'
      path: '/$shortRef'
      fullPath: '/order/$shortRef'
      preLoaderRoute: typeof OrderShortRefRouteImport
      parentRoute: typeof OrderRoute
    }
    '/o/$shortRef': {
      id: '/o/$shortRef'
      path: '/o/$shortRef'
      fullPath: '/o/$shortRef'
      preLoaderRoute: typeof OShortRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ceq/create': {
      id: '/ceq/create'
      path: '/create'
      fullPath: '/ceq/create'
      preLoaderRoute: typeof CeqCreateRouteImport
      parentRoute: typeof CeqRoute
    }
    '/outreach/leadfinder/': {
      id: '/outreach/leadfinder/'
      path: '/leadfinder'
      fullPath: '/outreach/leadfinder/'
      preLoaderRoute: typeof OutreachLeadfinderIndexRouteImport
      parentRoute: typeof OutreachRoute
    }
    '/outreach_/school/$slug': {
      id: '/outreach_/school/$slug'
      path: '/outreach/school/$slug'
      fullPath: '/outreach/school/$slug'
      preLoaderRoute: typeof OutreachSchoolSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outreach/leadfinder/$campusId': {
      id: '/outreach/leadfinder/$campusId'
      path: '/leadfinder/$campusId'
      fullPath: '/outreach/leadfinder/$campusId'
      preLoaderRoute: typeof OutreachLeadfinderCampusIdRouteImport
      parentRoute: typeof OutreachRoute
    }
    '/ceq/$id/tutor': {
      id: '/ceq/$id/tutor'
      path: '/$id/tutor'
      fullPath: '/ceq/$id/tutor'
      preLoaderRoute: typeof CeqIdTutorRouteImport
      parentRoute: typeof CeqRoute
    }
    '/ceq/$id/edit': {
      id: '/ceq/$id/edit'
      path: '/$id/edit'
      fullPath: '/ceq/$id/edit'
      preLoaderRoute: typeof CeqIdEditRouteImport
      parentRoute: typeof CeqRoute
    }
    '/ceq/$courseSlug/$chapterSlug': {
      id: '/ceq/$courseSlug/$chapterSlug'
      path: '/$courseSlug/$chapterSlug'
      fullPath: '/ceq/$courseSlug/$chapterSlug'
      preLoaderRoute: typeof CeqCourseSlugChapterSlugRouteImport
      parentRoute: typeof CeqRoute
    }
  }
}

interface CeqRouteChildren {
  CeqCreateRoute: typeof CeqCreateRoute
  CeqCourseSlugChapterSlugRoute: typeof CeqCourseSlugChapterSlugRoute
  CeqIdEditRoute: typeof CeqIdEditRoute
  CeqIdTutorRoute: typeof CeqIdTutorRoute
}

const CeqRouteChildren: CeqRouteChildren = {
  CeqCreateRoute: CeqCreateRoute,
  CeqCourseSlugChapterSlugRoute: CeqCourseSlugChapterSlugRoute,
  CeqIdEditRoute: CeqIdEditRoute,
  CeqIdTutorRoute: CeqIdTutorRoute,
}

const CeqRouteWithChildren = CeqRoute._addFileChildren(CeqRouteChildren)

interface OrderRouteChildren {
  OrderShortRefRoute: typeof OrderShortRefRoute
}

const OrderRouteChildren: OrderRouteChildren = {
  OrderShortRefRoute: OrderShortRefRoute,
}

const OrderRouteWithChildren = OrderRoute._addFileChildren(OrderRouteChildren)

interface OutreachRouteChildren {
  OutreachCampaignMetricsRoute: typeof OutreachCampaignMetricsRoute
  OutreachCampaignTargetsRoute: typeof OutreachCampaignTargetsRoute
  OutreachCampusesRoute: typeof OutreachCampusesRoute
  OutreachLandingRoute: typeof OutreachLandingRoute
  OutreachLeadfinderBatchRoute: typeof OutreachLeadfinderBatchRoute
  OutreachLeadfinderLeaderboardRoute: typeof OutreachLeadfinderLeaderboardRoute
  OutreachOrdersRoute: typeof OutreachOrdersRoute
  OutreachProfintelRoute: typeof OutreachProfintelRoute
  OutreachProfintelScheduleRoute: typeof OutreachProfintelScheduleRoute
  OutreachResearchRoute: typeof OutreachResearchRoute
  OutreachStudentsRoute: typeof OutreachStudentsRoute
  OutreachIndexRoute: typeof OutreachIndexRoute
  OutreachLeadfinderCampusIdRoute: typeof OutreachLeadfinderCampusIdRoute
  OutreachLeadfinderIndexRoute: typeof OutreachLeadfinderIndexRoute
}

const OutreachRouteChildren: OutreachRouteChildren = {
  OutreachCampaignMetricsRoute: OutreachCampaignMetricsRoute,
  OutreachCampaignTargetsRoute: OutreachCampaignTargetsRoute,
  OutreachCampusesRoute: OutreachCampusesRoute,
  OutreachLandingRoute: OutreachLandingRoute,
  OutreachLeadfinderBatchRoute: OutreachLeadfinderBatchRoute,
  OutreachLeadfinderLeaderboardRoute: OutreachLeadfinderLeaderboardRoute,
  OutreachOrdersRoute: OutreachOrdersRoute,
  OutreachProfintelRoute: OutreachProfintelRoute,
  OutreachProfintelScheduleRoute: OutreachProfintelScheduleRoute,
  OutreachResearchRoute: OutreachResearchRoute,
  OutreachStudentsRoute: OutreachStudentsRoute,
  OutreachIndexRoute: OutreachIndexRoute,
  OutreachLeadfinderCampusIdRoute: OutreachLeadfinderCampusIdRoute,
  OutreachLeadfinderIndexRoute: OutreachLeadfinderIndexRoute,
}

const OutreachRouteWithChildren = OutreachRoute._addFileChildren(
  OutreachRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BeyondRoute: BeyondRoute,
  CeqRoute: CeqRouteWithChildren,
  JeRoute: JeRoute,
  OnboardRoute: OnboardRoute,
  OrderRoute: OrderRouteWithChildren,
  OutreachRoute: OutreachRouteWithChildren,
  PreviewRoute: PreviewRoute,
  PrivacyRoute: PrivacyRoute,
  StartRoute: StartRoute,
  TermsRoute: TermsRoute,
  ThankyouRoute: ThankyouRoute,
  WelcomeRoute: WelcomeRoute,
  OShortRefRoute: OShortRefRoute,
  TSlugRoute: TSlugRoute,
  OutreachSchoolSlugRoute: OutreachSchoolSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
