-- 0004: RLS — pragmatic playground policies. Tighten before real launch.

alter table public.account_aliases enable row level security;
alter table public.banked_questions enable row level security;
alter table public.campus_courses enable row level security;
alter table public.campus_intelligence enable row level security;
alter table public.campus_landing_pages enable row level security;
alter table public.campus_tam_estimates enable row level security;
alter table public.campuses enable row level security;
alter table public.ceq_concepts enable row level security;
alter table public.ceq_teaching_blocks enable row level security;
alter table public.ceq_tutoring_notes enable row level security;
alter table public.ceqs enable row level security;
alter table public.chapter_accounts enable row level security;
alter table public.chapter_exam_mistakes enable row level security;
alter table public.chapter_formulas enable row level security;
alter table public.chapter_je_categories enable row level security;
alter table public.chapter_journal_entries enable row level security;
alter table public.chapter_key_terms enable row level security;
alter table public.chapter_purpose enable row level security;
alter table public.chapter_topics enable row level security;
alter table public.chapters enable row level security;
alter table public.chart_of_accounts enable row level security;
alter table public.company_names enable row level security;
alter table public.concepts enable row level security;
alter table public.contact_messages enable row level security;
alter table public.course_textbooks enable row level security;
alter table public.courses enable row level security;
alter table public.dissector_problems enable row level security;
alter table public.entry_builder_accounts enable row level security;
alter table public.entry_builder_items enable row level security;
alter table public.entry_builder_sets enable row level security;
alter table public.flashcard_decks enable row level security;
alter table public.flashcards enable row level security;
alter table public.formula_items enable row level security;
alter table public.formula_sets enable row level security;
alter table public.landing_page_leads enable row level security;
alter table public.newsletter_subscribers enable row level security;
alter table public.outreach_email_events enable row level security;
alter table public.outreach_email_templates enable row level security;
alter table public.outreach_leads enable row level security;
alter table public.outreach_saved_views enable row level security;
alter table public.outreach_schools enable row level security;
alter table public.outreach_send_log enable row level security;
alter table public.outreach_student_leads enable row level security;
alter table public.outreach_va_campus_assignments enable row level security;
alter table public.outreach_waitlist_signups enable row level security;
alter table public.session_prep_submissions enable row level security;
alter table public.student_emails enable row level security;
alter table public.teaching_asset_ceq_flags enable row level security;
alter table public.teaching_asset_ceq_part_focus enable row level security;
alter table public.teaching_asset_concepts enable row level security;
alter table public.teaching_assets enable row level security;
alter table public.textbooks enable row level security;
alter table public.va_accounts enable row level security;

create policy "auth all account_aliases" on public.account_aliases for all to authenticated using (true) with check (true);
create policy "auth all banked_questions" on public.banked_questions for all to authenticated using (true) with check (true);
create policy "auth all campus_courses" on public.campus_courses for all to authenticated using (true) with check (true);
create policy "auth all campus_intelligence" on public.campus_intelligence for all to authenticated using (true) with check (true);
create policy "auth all campus_landing_pages" on public.campus_landing_pages for all to authenticated using (true) with check (true);
create policy "auth all campus_tam_estimates" on public.campus_tam_estimates for all to authenticated using (true) with check (true);
create policy "auth all campuses" on public.campuses for all to authenticated using (true) with check (true);
create policy "auth all ceq_concepts" on public.ceq_concepts for all to authenticated using (true) with check (true);
create policy "auth all ceq_teaching_blocks" on public.ceq_teaching_blocks for all to authenticated using (true) with check (true);
create policy "auth all ceq_tutoring_notes" on public.ceq_tutoring_notes for all to authenticated using (true) with check (true);
create policy "auth all ceqs" on public.ceqs for all to authenticated using (true) with check (true);
create policy "auth all chapter_accounts" on public.chapter_accounts for all to authenticated using (true) with check (true);
create policy "auth all chapter_exam_mistakes" on public.chapter_exam_mistakes for all to authenticated using (true) with check (true);
create policy "auth all chapter_formulas" on public.chapter_formulas for all to authenticated using (true) with check (true);
create policy "auth all chapter_je_categories" on public.chapter_je_categories for all to authenticated using (true) with check (true);
create policy "auth all chapter_journal_entries" on public.chapter_journal_entries for all to authenticated using (true) with check (true);
create policy "auth all chapter_key_terms" on public.chapter_key_terms for all to authenticated using (true) with check (true);
create policy "auth all chapter_purpose" on public.chapter_purpose for all to authenticated using (true) with check (true);
create policy "auth all chapter_topics" on public.chapter_topics for all to authenticated using (true) with check (true);
create policy "auth all chapters" on public.chapters for all to authenticated using (true) with check (true);
create policy "auth all chart_of_accounts" on public.chart_of_accounts for all to authenticated using (true) with check (true);
create policy "auth all company_names" on public.company_names for all to authenticated using (true) with check (true);
create policy "auth all concepts" on public.concepts for all to authenticated using (true) with check (true);
create policy "auth all contact_messages" on public.contact_messages for all to authenticated using (true) with check (true);
create policy "auth all course_textbooks" on public.course_textbooks for all to authenticated using (true) with check (true);
create policy "auth all courses" on public.courses for all to authenticated using (true) with check (true);
create policy "auth all dissector_problems" on public.dissector_problems for all to authenticated using (true) with check (true);
create policy "auth all entry_builder_accounts" on public.entry_builder_accounts for all to authenticated using (true) with check (true);
create policy "auth all entry_builder_items" on public.entry_builder_items for all to authenticated using (true) with check (true);
create policy "auth all entry_builder_sets" on public.entry_builder_sets for all to authenticated using (true) with check (true);
create policy "auth all flashcard_decks" on public.flashcard_decks for all to authenticated using (true) with check (true);
create policy "auth all flashcards" on public.flashcards for all to authenticated using (true) with check (true);
create policy "auth all formula_items" on public.formula_items for all to authenticated using (true) with check (true);
create policy "auth all formula_sets" on public.formula_sets for all to authenticated using (true) with check (true);
create policy "auth all landing_page_leads" on public.landing_page_leads for all to authenticated using (true) with check (true);
create policy "auth all newsletter_subscribers" on public.newsletter_subscribers for all to authenticated using (true) with check (true);
create policy "auth all outreach_email_events" on public.outreach_email_events for all to authenticated using (true) with check (true);
create policy "auth all outreach_email_templates" on public.outreach_email_templates for all to authenticated using (true) with check (true);
create policy "auth all outreach_leads" on public.outreach_leads for all to authenticated using (true) with check (true);
create policy "auth all outreach_saved_views" on public.outreach_saved_views for all to authenticated using (true) with check (true);
create policy "auth all outreach_schools" on public.outreach_schools for all to authenticated using (true) with check (true);
create policy "auth all outreach_send_log" on public.outreach_send_log for all to authenticated using (true) with check (true);
create policy "auth all outreach_student_leads" on public.outreach_student_leads for all to authenticated using (true) with check (true);
create policy "auth all outreach_va_campus_assignments" on public.outreach_va_campus_assignments for all to authenticated using (true) with check (true);
create policy "auth all outreach_waitlist_signups" on public.outreach_waitlist_signups for all to authenticated using (true) with check (true);
create policy "auth all session_prep_submissions" on public.session_prep_submissions for all to authenticated using (true) with check (true);
create policy "auth all student_emails" on public.student_emails for all to authenticated using (true) with check (true);
create policy "auth all teaching_asset_ceq_flags" on public.teaching_asset_ceq_flags for all to authenticated using (true) with check (true);
create policy "auth all teaching_asset_ceq_part_focus" on public.teaching_asset_ceq_part_focus for all to authenticated using (true) with check (true);
create policy "auth all teaching_asset_concepts" on public.teaching_asset_concepts for all to authenticated using (true) with check (true);
create policy "auth all teaching_assets" on public.teaching_assets for all to authenticated using (true) with check (true);
create policy "auth all textbooks" on public.textbooks for all to authenticated using (true) with check (true);
create policy "auth all va_accounts" on public.va_accounts for all to authenticated using (true) with check (true);

create policy "anon read campuses" on public.campuses for select to anon using (true);
create policy "anon read outreach_schools" on public.outreach_schools for select to anon using (true);
create policy "anon read campus_landing_pages" on public.campus_landing_pages for select to anon using (true);
create policy "anon read campus_courses" on public.campus_courses for select to anon using (true);
create policy "anon read courses" on public.courses for select to anon using (true);

create policy "anon insert contact_messages" on public.contact_messages for insert to anon with check (true);
create policy "anon insert landing_page_leads" on public.landing_page_leads for insert to anon with check (true);
create policy "anon insert newsletter_subscribers" on public.newsletter_subscribers for insert to anon with check (true);
create policy "anon insert outreach_student_leads" on public.outreach_student_leads for insert to anon with check (true);
create policy "anon insert outreach_waitlist_signups" on public.outreach_waitlist_signups for insert to anon with check (true);
create policy "anon insert session_prep_submissions" on public.session_prep_submissions for insert to anon with check (true);
create policy "anon insert student_emails" on public.student_emails for insert to anon with check (true);