-- 0001: Outreach schema
-- Generated from old project's Supabase types (June 2026 branch).
-- All columns nullable except id/created_at/updated_at for maximum import compatibility;
-- tighten constraints after migration if desired.

create table if not exists public.va_accounts (
  id uuid primary key default gen_random_uuid(),
  account_status text,
  assigned_chapter_id text,
  assigned_course_id text,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  email text,
  first_action_at timestamptz,
  first_login_at timestamptz,
  full_name text,
  last_action_at timestamptz,
  role text,
  test_assigned_at timestamptz,
  user_id text
);

create table if not exists public.courses (
  id uuid primary key default gen_random_uuid(),
  code text,
  course_name text,
  created_at timestamptz not null default now(),
  description text,
  slug text
);

create table if not exists public.campuses (
  id uuid primary key default gen_random_uuid(),
  accounting_department_name text,
  adoption_count_intermediate numeric,
  adoption_count_intro numeric,
  adoption_count_total numeric,
  adoption_group text,
  adoption_rank_intermediate numeric,
  adoption_rank_intro numeric,
  adoption_source text,
  adoption_sources jsonb,
  adoption_tracks jsonb,
  ai_enrichment_raw_json jsonb,
  ai_enrichment_status text,
  annual_tuition_in_state_cents numeric,
  annual_tuition_out_state_cents numeric,
  approval_status text,
  approved_at timestamptz,
  approved_by text,
  archived_at timestamptz,
  archived_by text,
  assigned_at timestamptz,
  assigned_to text,
  assignment_batch text,
  assignment_notes text,
  assignment_status text,
  auto_name text,
  best_contact_type text,
  business_school_name text,
  canonical_name text,
  cheer text,
  city text,
  color_primary text,
  color_secondary text,
  color_tertiary text,
  colors_reviewed boolean,
  confidence_score numeric,
  country text,
  country_code text,
  course_aliases_json jsonb,
  course_code_notes text,
  course_codes_json jsonb,
  course_codes_reviewed boolean,
  course_family_codes_json jsonb,
  course_family_status_json jsonb,
  course_family_titles_json jsonb,
  created_at timestamptz not null default now(),
  domains text[],
  due_date date,
  email_domain text,
  enriched_at timestamptz,
  enrichment_confidence_notes text,
  enrollment_source text,
  enrollment_source_year text,
  enrollment_updated_at timestamptz,
  generated_theme_json jsonb,
  hipolabs_raw_json jsonb,
  hipolabs_status text,
  institution_name text,
  institution_type text,
  international boolean,
  ipeds_unitid numeric,
  is_active boolean,
  is_sec boolean,
  landing_page_approved_at timestamptz,
  landing_page_approved_by text,
  landing_page_notes text,
  landing_page_reviewed boolean,
  landing_page_status text,
  last_outreach_at timestamptz,
  market_priority text,
  marketing_notes text,
  mascot text,
  mascot_cheer text,
  name text,
  next_action text,
  outreach_notes text,
  outreach_status text,
  preview_slug text,
  priority_score numeric,
  priority_tier text,
  ready_for_outreach boolean,
  region text,
  review_notes text,
  rmp_last_checked_at timestamptz,
  rmp_match_confidence numeric,
  rmp_match_notes text,
  rmp_match_status text,
  rmp_raw_matches_json jsonb,
  rmp_school_id text,
  rmp_school_name text,
  rmp_school_url text,
  school_type text,
  scorecard_school_name text,
  semester_end date,
  semester_start date,
  short_name text,
  slug text,
  state text,
  status text,
  stripe_coupon_id text,
  subreddit text,
  subreddit_confidence numeric,
  textbook_notes text,
  textbook_status text,
  textbook_track text,
  timezone text,
  total_enrollment numeric,
  tuition_currency text,
  tuition_estimated_at timestamptz,
  tuition_notes text,
  tuition_source text,
  tuition_source_url text,
  undergrad_enrollment numeric,
  updated_at timestamptz not null default now(),
  use_school_colors boolean,
  warm_connection_notes text,
  website_url text
);

create table if not exists public.campus_courses (
  id uuid primary key default gen_random_uuid(),
  campus_id uuid references public.campuses(id) on delete cascade,
  course_id uuid references public.courses(id) on delete cascade,
  course_match_confidence numeric,
  course_match_notes text,
  created_at timestamptz not null default now(),
  display_order numeric,
  is_active boolean,
  local_course_code text,
  local_course_name text,
  override_chapter_price_cents numeric,
  override_semester_price_cents numeric,
  source text
);

create table if not exists public.outreach_schools (
  id uuid primary key default gen_random_uuid(),
  course_codes text[],
  created_at timestamptz not null default now(),
  landing_page_status text,
  mascot text,
  school_colors text[],
  school_name text,
  slug text,
  updated_at timestamptz not null default now(),
  waitlist_count numeric
);

create table if not exists public.campus_landing_pages (
  id uuid primary key default gen_random_uuid(),
  booking_link text,
  color_review_status text,
  course_codes text[],
  created_at timestamptz not null default now(),
  fallback_to_default_colors boolean,
  mascot text,
  notes text,
  primary_color text,
  school_name text,
  secondary_color text,
  slug text,
  status text,
  updated_at timestamptz not null default now(),
  use_school_colors boolean
);

create table if not exists public.outreach_leads (
  id uuid primary key default gen_random_uuid(),
  affiliation text,
  bounced_at timestamptz,
  campus_id uuid references public.campuses(id) on delete set null,
  clicks_count numeric,
  complained_at timestamptz,
  course_notes text,
  created_at timestamptz not null default now(),
  delivered_at timestamptz,
  department text,
  email text,
  first_clicked_at timestamptz,
  first_name text,
  first_opened_at timestamptz,
  follow_up_1_sent_at timestamptz,
  follow_up_2_sent_at timestamptz,
  follow_up_3_sent_at timestamptz,
  is_phd boolean,
  last_message_id text,
  last_name text,
  notes text,
  opens_count numeric,
  replied_at timestamptz,
  school_id uuid references public.outreach_schools(id) on delete set null,
  sent_at timestamptz,
  sequence_stopped_at timestamptz,
  sequence_stopped_reason text,
  skip_landing_page boolean,
  source text,
  status text,
  updated_at timestamptz not null default now()
);

create table if not exists public.outreach_email_templates (
  id uuid primary key default gen_random_uuid(),
  body text,
  created_at timestamptz not null default now(),
  is_active boolean,
  is_locked boolean,
  kind text,
  name text,
  subject text,
  updated_at timestamptz not null default now(),
  variant text
);

create table if not exists public.outreach_email_events (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  event_type text,
  lead_id uuid references public.outreach_leads(id) on delete cascade,
  message_id text,
  payload jsonb
);

create table if not exists public.outreach_send_log (
  id uuid primary key default gen_random_uuid(),
  lead_id uuid references public.outreach_leads(id) on delete cascade,
  sender_email text,
  sent_at timestamptz
);

create table if not exists public.outreach_va_campus_assignments (
  id uuid primary key default gen_random_uuid(),
  assigned_by_email text,
  assigned_for_date date,
  campus_id uuid references public.campuses(id) on delete cascade,
  created_at timestamptz not null default now(),
  notes text,
  va_account_id uuid references public.va_accounts(id) on delete cascade
);

create table if not exists public.outreach_saved_views (
  id uuid primary key default gen_random_uuid(),
  builtin_key text,
  created_at timestamptz not null default now(),
  filters jsonb,
  is_builtin boolean,
  is_shared boolean,
  name text,
  sort_order numeric,
  updated_at timestamptz not null default now(),
  user_id text
);

create table if not exists public.outreach_student_leads (
  id uuid primary key default gen_random_uuid(),
  campus_id uuid references public.campuses(id) on delete set null,
  campus_slug text,
  course_code text,
  created_at timestamptz not null default now(),
  email text,
  referrer text,
  school_name text,
  source text,
  updated_at timestamptz not null default now(),
  user_agent text
);

create table if not exists public.outreach_waitlist_signups (
  id uuid primary key default gen_random_uuid(),
  course text,
  created_at timestamptz not null default now(),
  email text,
  name text,
  need_help_with text,
  school_id uuid references public.outreach_schools(id) on delete set null
);

create table if not exists public.campus_tam_estimates (
  id uuid primary key default gen_random_uuid(),
  accounting_completions numeric,
  accounting_major_estimate numeric,
  adoption_count_intermediate numeric,
  adoption_count_intro numeric,
  adoption_count_total numeric,
  adoption_sources jsonb,
  adoption_tracks jsonb,
  ai_summary text,
  assumptions_json jsonb,
  business_completions numeric,
  business_school_enrollment numeric,
  campus_id uuid references public.campuses(id) on delete cascade,
  confidence_label text,
  confidence_score numeric,
  created_at timestamptz not null default now(),
  estimated_at timestamptz,
  manual_intermediate1_estimate numeric,
  manual_intermediate2_estimate numeric,
  manual_intro1_estimate numeric,
  manual_intro2_estimate numeric,
  manual_notes text,
  raw_source_json jsonb,
  source_type text,
  source_url text,
  source_year text,
  tam_intermediate1_base numeric,
  tam_intermediate1_high numeric,
  tam_intermediate1_low numeric,
  tam_intermediate2_base numeric,
  tam_intermediate2_high numeric,
  tam_intermediate2_low numeric,
  tam_intro1_base numeric,
  tam_intro1_high numeric,
  tam_intro1_low numeric,
  tam_intro2_base numeric,
  tam_intro2_high numeric,
  tam_intro2_low numeric,
  tam_notes text,
  tam_score numeric,
  tam_tier text,
  tam_total_base numeric,
  tam_total_high numeric,
  tam_total_low numeric,
  total_enrollment numeric,
  undergraduate_enrollment numeric,
  updated_at timestamptz not null default now()
);

create table if not exists public.campus_intelligence (
  id uuid primary key default gen_random_uuid(),
  adoption_count_intermediate numeric,
  adoption_count_intro numeric,
  adoption_count_total numeric,
  adoption_rank_intermediate numeric,
  adoption_rank_intro numeric,
  adoption_sources jsonb,
  adoption_tracks jsonb,
  ai_opportunity_notes text,
  ai_risk_notes text,
  ai_summary text,
  bap_presence_score numeric,
  best_contact_type text,
  campus_id uuid references public.campuses(id) on delete cascade,
  campus_name text,
  city text,
  content_priority_score numeric,
  conversion_signal_score numeric,
  country text,
  country_code text,
  created_at timestamptz not null default now(),
  existing_paid_signup_count numeric,
  existing_signup_count numeric,
  greek_presence_score numeric,
  institution_name text,
  institution_type text,
  international boolean,
  is_high_value_market boolean,
  is_international_experimental boolean,
  is_target_market boolean,
  landing_page_priority_score numeric,
  market_priority text,
  market_region text,
  metadata jsonb,
  outreach_notes text,
  outreach_readiness_score numeric,
  outreach_status text,
  priority_score numeric,
  priority_tier text,
  professor_signal_score numeric,
  raw_source_json jsonb,
  reddit_accounting_mentions numeric,
  reddit_confidence numeric,
  reddit_mentions numeric,
  region text,
  seo_priority_score numeric,
  social_signal_score numeric,
  source_raw_count numeric,
  source_raw_location text,
  source_raw_name text,
  source_raw_rank numeric,
  state text,
  tam_confidence_label text,
  tam_score numeric,
  tam_tier text,
  tam_total_base numeric,
  updated_at timestamptz not null default now(),
  warm_connection_notes text
);

create unique index if not exists campuses_slug_key on public.campuses(slug);
create unique index if not exists outreach_schools_slug_key on public.outreach_schools(slug);
create unique index if not exists campus_landing_pages_slug_key on public.campus_landing_pages(slug);
create index if not exists outreach_leads_campus_idx on public.outreach_leads(campus_id);
create index if not exists ova_date_idx on public.outreach_va_campus_assignments(assigned_for_date);